// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//  **** IMPORTANT NOTE ****
//
//  The proto of BT data has to match exactly the g3 proto, including tag
//  number.

// *** IMPORTANT NOTE ***
// Keep this in sync with the same proto in datacommonsorg/import.
// Eventually we need to move the shared protos out to a separate repo.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: debug.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Severity level of the message.
type Log_Level int32

const (
	Log_LEVEL_UNSPECIFIED Log_Level = 0
	Log_LEVEL_INFO        Log_Level = 1
	Log_LEVEL_WARNING     Log_Level = 2
	Log_LEVEL_ERROR       Log_Level = 3
	Log_LEVEL_FATAL       Log_Level = 4
)

// Enum value maps for Log_Level.
var (
	Log_Level_name = map[int32]string{
		0: "LEVEL_UNSPECIFIED",
		1: "LEVEL_INFO",
		2: "LEVEL_WARNING",
		3: "LEVEL_ERROR",
		4: "LEVEL_FATAL",
	}
	Log_Level_value = map[string]int32{
		"LEVEL_UNSPECIFIED": 0,
		"LEVEL_INFO":        1,
		"LEVEL_WARNING":     2,
		"LEVEL_ERROR":       3,
		"LEVEL_FATAL":       4,
	}
)

func (x Log_Level) Enum() *Log_Level {
	p := new(Log_Level)
	*p = x
	return p
}

func (x Log_Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Log_Level) Descriptor() protoreflect.EnumDescriptor {
	return file_debug_proto_enumTypes[0].Descriptor()
}

func (Log_Level) Type() protoreflect.EnumType {
	return &file_debug_proto_enumTypes[0]
}

func (x Log_Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Log_Level) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Log_Level(num)
	return nil
}

// Deprecated: Use Log_Level.Descriptor instead.
func (Log_Level) EnumDescriptor() ([]byte, []int) {
	return file_debug_proto_rawDescGZIP(), []int{0, 0}
}

// A log of import processing with details on any warnings, errors, etc.
type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Log_Entry           `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	CounterSet    *Log_CounterSet        `protobuf:"bytes,2,opt,name=counter_set,json=counterSet" json:"counter_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_debug_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_debug_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_debug_proto_rawDescGZIP(), []int{0}
}

func (x *Log) GetEntries() []*Log_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Log) GetCounterSet() *Log_CounterSet {
	if x != nil {
		return x.CounterSet
	}
	return nil
}

type Log_Location struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the file. Could be a full path or not. Typically, this is
	// an MCF file or CSV.
	File *string `protobuf:"bytes,1,opt,name=file" json:"file,omitempty"`
	// Line number in file, starting from 1.  Matches the row number in
	// CSV (since we do not handle newlines in values).
	LineNumber *int64 `protobuf:"varint,2,opt,name=line_number,json=lineNumber" json:"line_number,omitempty"`
	// Column number in line, starting from 1. Can be empty.
	ColumnNumber *int64 `protobuf:"varint,3,opt,name=column_number,json=columnNumber" json:"column_number,omitempty"`
	// Column name set when the input is a CSV. Can be empty.
	ColumnName    *string `protobuf:"bytes,4,opt,name=column_name,json=columnName" json:"column_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log_Location) Reset() {
	*x = Log_Location{}
	mi := &file_debug_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log_Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log_Location) ProtoMessage() {}

func (x *Log_Location) ProtoReflect() protoreflect.Message {
	mi := &file_debug_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log_Location.ProtoReflect.Descriptor instead.
func (*Log_Location) Descriptor() ([]byte, []int) {
	return file_debug_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Log_Location) GetFile() string {
	if x != nil && x.File != nil {
		return *x.File
	}
	return ""
}

func (x *Log_Location) GetLineNumber() int64 {
	if x != nil && x.LineNumber != nil {
		return *x.LineNumber
	}
	return 0
}

func (x *Log_Location) GetColumnNumber() int64 {
	if x != nil && x.ColumnNumber != nil {
		return *x.ColumnNumber
	}
	return 0
}

func (x *Log_Location) GetColumnName() string {
	if x != nil && x.ColumnName != nil {
		return *x.ColumnName
	}
	return ""
}

type Log_CounterSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key is the name of a counter.
	Counters      map[string]int64 `protobuf:"bytes,1,rep,name=counters" json:"counters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log_CounterSet) Reset() {
	*x = Log_CounterSet{}
	mi := &file_debug_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log_CounterSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log_CounterSet) ProtoMessage() {}

func (x *Log_CounterSet) ProtoReflect() protoreflect.Message {
	mi := &file_debug_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log_CounterSet.ProtoReflect.Descriptor instead.
func (*Log_CounterSet) Descriptor() ([]byte, []int) {
	return file_debug_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Log_CounterSet) GetCounters() map[string]int64 {
	if x != nil {
		return x.Counters
	}
	return nil
}

// One log entry. This could be a sample of messages for a particular
// counter.
type Log_Entry struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Level    *Log_Level             `protobuf:"varint,1,opt,name=level,enum=datacommons.Log_Level" json:"level,omitempty"`
	Location *Log_Location          `protobuf:"bytes,2,opt,name=location" json:"location,omitempty"`
	// This must be user understandable.
	UserMessage *string `protobuf:"bytes,3,opt,name=user_message,json=userMessage" json:"user_message,omitempty"`
	// A counter key in CounterSet.
	CounterKey    *string `protobuf:"bytes,4,opt,name=counter_key,json=counterKey" json:"counter_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log_Entry) Reset() {
	*x = Log_Entry{}
	mi := &file_debug_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log_Entry) ProtoMessage() {}

func (x *Log_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_debug_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log_Entry.ProtoReflect.Descriptor instead.
func (*Log_Entry) Descriptor() ([]byte, []int) {
	return file_debug_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Log_Entry) GetLevel() Log_Level {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return Log_LEVEL_UNSPECIFIED
}

func (x *Log_Entry) GetLocation() *Log_Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Log_Entry) GetUserMessage() string {
	if x != nil && x.UserMessage != nil {
		return *x.UserMessage
	}
	return ""
}

func (x *Log_Entry) GetCounterKey() string {
	if x != nil && x.CounterKey != nil {
		return *x.CounterKey
	}
	return ""
}

var File_debug_proto protoreflect.FileDescriptor

const file_debug_proto_rawDesc = "" +
	"\n" +
	"\vdebug.proto\x12\vdatacommons\"\xa8\x05\n" +
	"\x03Log\x120\n" +
	"\aentries\x18\x01 \x03(\v2\x16.datacommons.Log.EntryR\aentries\x12<\n" +
	"\vcounter_set\x18\x02 \x01(\v2\x1b.datacommons.Log.CounterSetR\n" +
	"counterSet\x1a\x85\x01\n" +
	"\bLocation\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12\x1f\n" +
	"\vline_number\x18\x02 \x01(\x03R\n" +
	"lineNumber\x12#\n" +
	"\rcolumn_number\x18\x03 \x01(\x03R\fcolumnNumber\x12\x1f\n" +
	"\vcolumn_name\x18\x04 \x01(\tR\n" +
	"columnName\x1a\x90\x01\n" +
	"\n" +
	"CounterSet\x12E\n" +
	"\bcounters\x18\x01 \x03(\v2).datacommons.Log.CounterSet.CountersEntryR\bcounters\x1a;\n" +
	"\rCountersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a\xb0\x01\n" +
	"\x05Entry\x12,\n" +
	"\x05level\x18\x01 \x01(\x0e2\x16.datacommons.Log.LevelR\x05level\x125\n" +
	"\blocation\x18\x02 \x01(\v2\x19.datacommons.Log.LocationR\blocation\x12!\n" +
	"\fuser_message\x18\x03 \x01(\tR\vuserMessage\x12\x1f\n" +
	"\vcounter_key\x18\x04 \x01(\tR\n" +
	"counterKey\"c\n" +
	"\x05Level\x12\x15\n" +
	"\x11LEVEL_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"LEVEL_INFO\x10\x01\x12\x11\n" +
	"\rLEVEL_WARNING\x10\x02\x12\x0f\n" +
	"\vLEVEL_ERROR\x10\x03\x12\x0f\n" +
	"\vLEVEL_FATAL\x10\x04B0Z.github.com/datacommonsorg/mixer/internal/proto"

var (
	file_debug_proto_rawDescOnce sync.Once
	file_debug_proto_rawDescData []byte
)

func file_debug_proto_rawDescGZIP() []byte {
	file_debug_proto_rawDescOnce.Do(func() {
		file_debug_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_debug_proto_rawDesc), len(file_debug_proto_rawDesc)))
	})
	return file_debug_proto_rawDescData
}

var file_debug_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_debug_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_debug_proto_goTypes = []any{
	(Log_Level)(0),         // 0: datacommons.Log.Level
	(*Log)(nil),            // 1: datacommons.Log
	(*Log_Location)(nil),   // 2: datacommons.Log.Location
	(*Log_CounterSet)(nil), // 3: datacommons.Log.CounterSet
	(*Log_Entry)(nil),      // 4: datacommons.Log.Entry
	nil,                    // 5: datacommons.Log.CounterSet.CountersEntry
}
var file_debug_proto_depIdxs = []int32{
	4, // 0: datacommons.Log.entries:type_name -> datacommons.Log.Entry
	3, // 1: datacommons.Log.counter_set:type_name -> datacommons.Log.CounterSet
	5, // 2: datacommons.Log.CounterSet.counters:type_name -> datacommons.Log.CounterSet.CountersEntry
	0, // 3: datacommons.Log.Entry.level:type_name -> datacommons.Log.Level
	2, // 4: datacommons.Log.Entry.location:type_name -> datacommons.Log.Location
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_debug_proto_init() }
func file_debug_proto_init() {
	if File_debug_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_debug_proto_rawDesc), len(file_debug_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_debug_proto_goTypes,
		DependencyIndexes: file_debug_proto_depIdxs,
		EnumInfos:         file_debug_proto_enumTypes,
		MessageInfos:      file_debug_proto_msgTypes,
	}.Build()
	File_debug_proto = out.File
	file_debug_proto_goTypes = nil
	file_debug_proto_depIdxs = nil
}
