// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: v1/info.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaceInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node string `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *PlaceInfoRequest) Reset() {
	*x = PlaceInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceInfoRequest) ProtoMessage() {}

func (x *PlaceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceInfoRequest.ProtoReflect.Descriptor instead.
func (*PlaceInfoRequest) Descriptor() ([]byte, []int) {
	return file_v1_info_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceInfoRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

type PlaceInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node string         `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Info *PlaceMetadata `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *PlaceInfoResponse) Reset() {
	*x = PlaceInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_info_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceInfoResponse) ProtoMessage() {}

func (x *PlaceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_info_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceInfoResponse.ProtoReflect.Descriptor instead.
func (*PlaceInfoResponse) Descriptor() ([]byte, []int) {
	return file_v1_info_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceInfoResponse) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *PlaceInfoResponse) GetInfo() *PlaceMetadata {
	if x != nil {
		return x.Info
	}
	return nil
}

type BulkPlaceInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []string `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *BulkPlaceInfoRequest) Reset() {
	*x = BulkPlaceInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_info_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BulkPlaceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkPlaceInfoRequest) ProtoMessage() {}

func (x *BulkPlaceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_info_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkPlaceInfoRequest.ProtoReflect.Descriptor instead.
func (*BulkPlaceInfoRequest) Descriptor() ([]byte, []int) {
	return file_v1_info_proto_rawDescGZIP(), []int{2}
}

func (x *BulkPlaceInfoRequest) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type BulkPlaceInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*PlaceInfoResponse `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *BulkPlaceInfoResponse) Reset() {
	*x = BulkPlaceInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_info_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BulkPlaceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkPlaceInfoResponse) ProtoMessage() {}

func (x *BulkPlaceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_info_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkPlaceInfoResponse.ProtoReflect.Descriptor instead.
func (*BulkPlaceInfoResponse) Descriptor() ([]byte, []int) {
	return file_v1_info_proto_rawDescGZIP(), []int{3}
}

func (x *BulkPlaceInfoResponse) GetData() []*PlaceInfoResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type VariableInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node string `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
}

func (x *VariableInfoRequest) Reset() {
	*x = VariableInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_info_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VariableInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableInfoRequest) ProtoMessage() {}

func (x *VariableInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_info_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableInfoRequest.ProtoReflect.Descriptor instead.
func (*VariableInfoRequest) Descriptor() ([]byte, []int) {
	return file_v1_info_proto_rawDescGZIP(), []int{4}
}

func (x *VariableInfoRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

type VariableInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node string          `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Info *StatVarSummary `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *VariableInfoResponse) Reset() {
	*x = VariableInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_info_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VariableInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableInfoResponse) ProtoMessage() {}

func (x *VariableInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_info_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableInfoResponse.ProtoReflect.Descriptor instead.
func (*VariableInfoResponse) Descriptor() ([]byte, []int) {
	return file_v1_info_proto_rawDescGZIP(), []int{5}
}

func (x *VariableInfoResponse) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *VariableInfoResponse) GetInfo() *StatVarSummary {
	if x != nil {
		return x.Info
	}
	return nil
}

type BulkVariableInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []string `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *BulkVariableInfoRequest) Reset() {
	*x = BulkVariableInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_info_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BulkVariableInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkVariableInfoRequest) ProtoMessage() {}

func (x *BulkVariableInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_info_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkVariableInfoRequest.ProtoReflect.Descriptor instead.
func (*BulkVariableInfoRequest) Descriptor() ([]byte, []int) {
	return file_v1_info_proto_rawDescGZIP(), []int{6}
}

func (x *BulkVariableInfoRequest) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type BulkVariableInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*VariableInfoResponse `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *BulkVariableInfoResponse) Reset() {
	*x = BulkVariableInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_info_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BulkVariableInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkVariableInfoResponse) ProtoMessage() {}

func (x *BulkVariableInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_info_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkVariableInfoResponse.ProtoReflect.Descriptor instead.
func (*BulkVariableInfoResponse) Descriptor() ([]byte, []int) {
	return file_v1_info_proto_rawDescGZIP(), []int{7}
}

func (x *BulkVariableInfoResponse) GetData() []*VariableInfoResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type VariableGroupInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The variable group dcid to query for.
	Node string `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	// The entities that the variable group is associated with. The response should
	// only contain the child variable (group) if it has data for at least one
	// of the entities.
	ConstrainedEntities []string `protobuf:"bytes,2,rep,name=constrained_entities,json=constrainedEntities,proto3" json:"constrained_entities,omitempty"`
}

func (x *VariableGroupInfoRequest) Reset() {
	*x = VariableGroupInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_info_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VariableGroupInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableGroupInfoRequest) ProtoMessage() {}

func (x *VariableGroupInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_info_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableGroupInfoRequest.ProtoReflect.Descriptor instead.
func (*VariableGroupInfoRequest) Descriptor() ([]byte, []int) {
	return file_v1_info_proto_rawDescGZIP(), []int{8}
}

func (x *VariableGroupInfoRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *VariableGroupInfoRequest) GetConstrainedEntities() []string {
	if x != nil {
		return x.ConstrainedEntities
	}
	return nil
}

type VariableGroupInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Node string            `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Info *StatVarGroupNode `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *VariableGroupInfoResponse) Reset() {
	*x = VariableGroupInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_info_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VariableGroupInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableGroupInfoResponse) ProtoMessage() {}

func (x *VariableGroupInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_info_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableGroupInfoResponse.ProtoReflect.Descriptor instead.
func (*VariableGroupInfoResponse) Descriptor() ([]byte, []int) {
	return file_v1_info_proto_rawDescGZIP(), []int{9}
}

func (x *VariableGroupInfoResponse) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *VariableGroupInfoResponse) GetInfo() *StatVarGroupNode {
	if x != nil {
		return x.Info
	}
	return nil
}

type BulkVariableGroupInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// (optional) The variable group dcids to query for.
	// If not specified, then return all the variable group info.
	Nodes []string `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	// (optional) When specified, only return the variable groups that the entities
	// have data for.
	ConstrainedEntities []string `protobuf:"bytes,2,rep,name=constrained_entities,json=constrainedEntities,proto3" json:"constrained_entities,omitempty"`
}

func (x *BulkVariableGroupInfoRequest) Reset() {
	*x = BulkVariableGroupInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_info_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BulkVariableGroupInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkVariableGroupInfoRequest) ProtoMessage() {}

func (x *BulkVariableGroupInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_info_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkVariableGroupInfoRequest.ProtoReflect.Descriptor instead.
func (*BulkVariableGroupInfoRequest) Descriptor() ([]byte, []int) {
	return file_v1_info_proto_rawDescGZIP(), []int{10}
}

func (x *BulkVariableGroupInfoRequest) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *BulkVariableGroupInfoRequest) GetConstrainedEntities() []string {
	if x != nil {
		return x.ConstrainedEntities
	}
	return nil
}

type BulkVariableGroupInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*VariableGroupInfoResponse `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *BulkVariableGroupInfoResponse) Reset() {
	*x = BulkVariableGroupInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_info_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BulkVariableGroupInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkVariableGroupInfoResponse) ProtoMessage() {}

func (x *BulkVariableGroupInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_info_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkVariableGroupInfoResponse.ProtoReflect.Descriptor instead.
func (*BulkVariableGroupInfoResponse) Descriptor() ([]byte, []int) {
	return file_v1_info_proto_rawDescGZIP(), []int{11}
}

func (x *BulkVariableGroupInfoResponse) GetData() []*VariableGroupInfoResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_v1_info_proto protoreflect.FileDescriptor

var file_v1_info_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x76, 0x31, 0x2f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0e, 0x64, 0x61, 0x74, 0x61, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x76, 0x31, 0x1a,
	0x0b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x73, 0x74,
	0x61, 0x74, 0x5f, 0x76, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x26, 0x0a, 0x10,
	0x50, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x6f, 0x64, 0x65, 0x22, 0x57, 0x0a, 0x11, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x2e, 0x0a,
	0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x64, 0x61,
	0x74, 0x61, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x2c, 0x0a,
	0x14, 0x42, 0x75, 0x6c, 0x6b, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x4e, 0x0a, 0x15, 0x42,
	0x75, 0x6c, 0x6b, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x21, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x29, 0x0a, 0x13, 0x56,
	0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0x5b, 0x0a, 0x14, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62,
	0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f,
	0x64, 0x65, 0x12, 0x2f, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x56, 0x61, 0x72, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x04, 0x69,
	0x6e, 0x66, 0x6f, 0x22, 0x2f, 0x0a, 0x17, 0x42, 0x75, 0x6c, 0x6b, 0x56, 0x61, 0x72, 0x69, 0x61,
	0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e,
	0x6f, 0x64, 0x65, 0x73, 0x22, 0x54, 0x0a, 0x18, 0x42, 0x75, 0x6c, 0x6b, 0x56, 0x61, 0x72, 0x69,
	0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x38, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x61, 0x0a, 0x18, 0x56, 0x61,
	0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x31, 0x0a, 0x14, 0x63, 0x6f,
	0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x13, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x65, 0x64, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0x62, 0x0a,
	0x19, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x31,
	0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x56,
	0x61, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x22, 0x67, 0x0a, 0x1c, 0x42, 0x75, 0x6c, 0x6b, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c,
	0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x14, 0x63, 0x6f, 0x6e, 0x73, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x65, 0x64, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x13, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e,
	0x65, 0x64, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0x5e, 0x0a, 0x1d, 0x42, 0x75,
	0x6c, 0x6b, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x64, 0x61, 0x74, 0x61,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x61, 0x72, 0x69, 0x61,
	0x62, 0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_info_proto_rawDescOnce sync.Once
	file_v1_info_proto_rawDescData = file_v1_info_proto_rawDesc
)

func file_v1_info_proto_rawDescGZIP() []byte {
	file_v1_info_proto_rawDescOnce.Do(func() {
		file_v1_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_info_proto_rawDescData)
	})
	return file_v1_info_proto_rawDescData
}

var file_v1_info_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_v1_info_proto_goTypes = []interface{}{
	(*PlaceInfoRequest)(nil),              // 0: datacommons.v1.PlaceInfoRequest
	(*PlaceInfoResponse)(nil),             // 1: datacommons.v1.PlaceInfoResponse
	(*BulkPlaceInfoRequest)(nil),          // 2: datacommons.v1.BulkPlaceInfoRequest
	(*BulkPlaceInfoResponse)(nil),         // 3: datacommons.v1.BulkPlaceInfoResponse
	(*VariableInfoRequest)(nil),           // 4: datacommons.v1.VariableInfoRequest
	(*VariableInfoResponse)(nil),          // 5: datacommons.v1.VariableInfoResponse
	(*BulkVariableInfoRequest)(nil),       // 6: datacommons.v1.BulkVariableInfoRequest
	(*BulkVariableInfoResponse)(nil),      // 7: datacommons.v1.BulkVariableInfoResponse
	(*VariableGroupInfoRequest)(nil),      // 8: datacommons.v1.VariableGroupInfoRequest
	(*VariableGroupInfoResponse)(nil),     // 9: datacommons.v1.VariableGroupInfoResponse
	(*BulkVariableGroupInfoRequest)(nil),  // 10: datacommons.v1.BulkVariableGroupInfoRequest
	(*BulkVariableGroupInfoResponse)(nil), // 11: datacommons.v1.BulkVariableGroupInfoResponse
	(*PlaceMetadata)(nil),                 // 12: datacommons.PlaceMetadata
	(*StatVarSummary)(nil),                // 13: datacommons.StatVarSummary
	(*StatVarGroupNode)(nil),              // 14: datacommons.StatVarGroupNode
}
var file_v1_info_proto_depIdxs = []int32{
	12, // 0: datacommons.v1.PlaceInfoResponse.info:type_name -> datacommons.PlaceMetadata
	1,  // 1: datacommons.v1.BulkPlaceInfoResponse.data:type_name -> datacommons.v1.PlaceInfoResponse
	13, // 2: datacommons.v1.VariableInfoResponse.info:type_name -> datacommons.StatVarSummary
	5,  // 3: datacommons.v1.BulkVariableInfoResponse.data:type_name -> datacommons.v1.VariableInfoResponse
	14, // 4: datacommons.v1.VariableGroupInfoResponse.info:type_name -> datacommons.StatVarGroupNode
	9,  // 5: datacommons.v1.BulkVariableGroupInfoResponse.data:type_name -> datacommons.v1.VariableGroupInfoResponse
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_v1_info_proto_init() }
func file_v1_info_proto_init() {
	if File_v1_info_proto != nil {
		return
	}
	file_place_proto_init()
	file_stat_var_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_v1_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_info_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_info_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BulkPlaceInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_info_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BulkPlaceInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_info_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VariableInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_info_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VariableInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_info_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BulkVariableInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_info_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BulkVariableInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_info_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VariableGroupInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_info_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VariableGroupInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_info_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BulkVariableGroupInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_info_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BulkVariableGroupInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_info_proto_goTypes,
		DependencyIndexes: file_v1_info_proto_depIdxs,
		MessageInfos:      file_v1_info_proto_msgTypes,
	}.Build()
	File_v1_info_proto = out.File
	file_v1_info_proto_rawDesc = nil
	file_v1_info_proto_goTypes = nil
	file_v1_info_proto_depIdxs = nil
}
