// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//  **** IMPORTANT NOTE ****
//
//  The proto of BT data has to match exactly the g3 proto, including tag
//  number.

// REST API URL from the proto in this file:
// ========================================
//    /query
// ========================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: query.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Cell in the QueryResponse
type QueryResponseCell struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cell value.
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Provenance ID.
	ProvenanceId  string `protobuf:"bytes,2,opt,name=provenance_id,json=provenanceId,proto3" json:"provenance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponseCell) Reset() {
	*x = QueryResponseCell{}
	mi := &file_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponseCell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponseCell) ProtoMessage() {}

func (x *QueryResponseCell) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponseCell.ProtoReflect.Descriptor instead.
func (*QueryResponseCell) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryResponseCell) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *QueryResponseCell) GetProvenanceId() string {
	if x != nil {
		return x.ProvenanceId
	}
	return ""
}

// A graph query response row corresponding to the query variables in graph
// query.
type QueryResponseRow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of QueryResponseCell.
	Cells         []*QueryResponseCell `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponseRow) Reset() {
	*x = QueryResponseRow{}
	mi := &file_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponseRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponseRow) ProtoMessage() {}

func (x *QueryResponseRow) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponseRow.ProtoReflect.Descriptor instead.
func (*QueryResponseRow) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponseRow) GetCells() []*QueryResponseCell {
	if x != nil {
		return x.Cells
	}
	return nil
}

// A graph query request in Sparql query language.
type QueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sparql query string.
	Sparql        string `protobuf:"bytes,1,opt,name=sparql,proto3" json:"sparql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryRequest) GetSparql() string {
	if x != nil {
		return x.Sparql
	}
	return ""
}

// Request proto for V2 Sparql API.
// Note the paramter here is `query` instead of `sparql`.
type SparqlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SparqlRequest) Reset() {
	*x = SparqlRequest{}
	mi := &file_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SparqlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SparqlRequest) ProtoMessage() {}

func (x *SparqlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SparqlRequest.ProtoReflect.Descriptor instead.
func (*SparqlRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{3}
}

func (x *SparqlRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

// Graph query response.
type QueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier for selected variable. Size of the header is the same as number
	// of cells for each row.
	Header []string `protobuf:"bytes,1,rep,name=header,proto3" json:"header,omitempty"`
	// Query results, with each row containing cells corresponding to header
	// variable order.
	Rows          []*QueryResponseRow `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{4}
}

func (x *QueryResponse) GetHeader() []string {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *QueryResponse) GetRows() []*QueryResponseRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

var File_query_proto protoreflect.FileDescriptor

const file_query_proto_rawDesc = "" +
	"\n" +
	"\vquery.proto\x12\vdatacommons\"N\n" +
	"\x11QueryResponseCell\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12#\n" +
	"\rprovenance_id\x18\x02 \x01(\tR\fprovenanceId\"H\n" +
	"\x10QueryResponseRow\x124\n" +
	"\x05cells\x18\x01 \x03(\v2\x1e.datacommons.QueryResponseCellR\x05cells\"&\n" +
	"\fQueryRequest\x12\x16\n" +
	"\x06sparql\x18\x01 \x01(\tR\x06sparql\"%\n" +
	"\rSparqlRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"Z\n" +
	"\rQueryResponse\x12\x16\n" +
	"\x06header\x18\x01 \x03(\tR\x06header\x121\n" +
	"\x04rows\x18\x02 \x03(\v2\x1d.datacommons.QueryResponseRowR\x04rowsB0Z.github.com/datacommonsorg/mixer/internal/protob\x06proto3"

var (
	file_query_proto_rawDescOnce sync.Once
	file_query_proto_rawDescData []byte
)

func file_query_proto_rawDescGZIP() []byte {
	file_query_proto_rawDescOnce.Do(func() {
		file_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)))
	})
	return file_query_proto_rawDescData
}

var file_query_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_query_proto_goTypes = []any{
	(*QueryResponseCell)(nil), // 0: datacommons.QueryResponseCell
	(*QueryResponseRow)(nil),  // 1: datacommons.QueryResponseRow
	(*QueryRequest)(nil),      // 2: datacommons.QueryRequest
	(*SparqlRequest)(nil),     // 3: datacommons.SparqlRequest
	(*QueryResponse)(nil),     // 4: datacommons.QueryResponse
}
var file_query_proto_depIdxs = []int32{
	0, // 0: datacommons.QueryResponseRow.cells:type_name -> datacommons.QueryResponseCell
	1, // 1: datacommons.QueryResponse.rows:type_name -> datacommons.QueryResponseRow
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_query_proto_init() }
func file_query_proto_init() {
	if File_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_query_proto_goTypes,
		DependencyIndexes: file_query_proto_depIdxs,
		MessageInfos:      file_query_proto_msgTypes,
	}.Build()
	File_query_proto = out.File
	file_query_proto_goTypes = nil
	file_query_proto_depIdxs = nil
}
