// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//  **** IMPORTANT NOTE ****
//
//  The proto of BT data has to match exactly the g3 proto, including tag
//  number.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: recon.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lists of entities (with their known IDs) for a given {idProp, idVal}.
type ReconEntities struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entities []*ReconEntities_Entity `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
}

func (x *ReconEntities) Reset() {
	*x = ReconEntities{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReconEntities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconEntities) ProtoMessage() {}

func (x *ReconEntities) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconEntities.ProtoReflect.Descriptor instead.
func (*ReconEntities) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{0}
}

func (x *ReconEntities) GetEntities() []*ReconEntities_Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

// A list of candidate places that a coordinate might be contained in.
type CoordinateRecon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Places []*CoordinateRecon_Place `protobuf:"bytes,1,rep,name=places,proto3" json:"places,omitempty"`
}

func (x *CoordinateRecon) Reset() {
	*x = CoordinateRecon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoordinateRecon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinateRecon) ProtoMessage() {}

func (x *CoordinateRecon) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinateRecon.ProtoReflect.Descriptor instead.
func (*CoordinateRecon) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{1}
}

func (x *CoordinateRecon) GetPlaces() []*CoordinateRecon_Place {
	if x != nil {
		return x.Places
	}
	return nil
}

type ResolveEntitiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entities []*EntitySubGraph `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	// The properties of IDs to find. If empty, all known IDs are returned.
	WantedIdProperties []string `protobuf:"bytes,2,rep,name=wanted_id_properties,json=wantedIdProperties,proto3" json:"wanted_id_properties,omitempty"`
}

func (x *ResolveEntitiesRequest) Reset() {
	*x = ResolveEntitiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveEntitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveEntitiesRequest) ProtoMessage() {}

func (x *ResolveEntitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveEntitiesRequest.ProtoReflect.Descriptor instead.
func (*ResolveEntitiesRequest) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveEntitiesRequest) GetEntities() []*EntitySubGraph {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *ResolveEntitiesRequest) GetWantedIdProperties() []string {
	if x != nil {
		return x.WantedIdProperties
	}
	return nil
}

type ResolveEntitiesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResolvedEntities []*ResolveEntitiesResponse_ResolvedEntity `protobuf:"bytes,1,rep,name=resolved_entities,json=resolvedEntities,proto3" json:"resolved_entities,omitempty"`
}

func (x *ResolveEntitiesResponse) Reset() {
	*x = ResolveEntitiesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveEntitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveEntitiesResponse) ProtoMessage() {}

func (x *ResolveEntitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveEntitiesResponse.ProtoReflect.Descriptor instead.
func (*ResolveEntitiesResponse) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveEntitiesResponse) GetResolvedEntities() []*ResolveEntitiesResponse_ResolvedEntity {
	if x != nil {
		return x.ResolvedEntities
	}
	return nil
}

type ResolveCoordinatesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coordinates []*ResolveCoordinatesRequest_Coordinate `protobuf:"bytes,1,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
}

func (x *ResolveCoordinatesRequest) Reset() {
	*x = ResolveCoordinatesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recon_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveCoordinatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveCoordinatesRequest) ProtoMessage() {}

func (x *ResolveCoordinatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveCoordinatesRequest.ProtoReflect.Descriptor instead.
func (*ResolveCoordinatesRequest) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveCoordinatesRequest) GetCoordinates() []*ResolveCoordinatesRequest_Coordinate {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

type ResolveCoordinatesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlaceCoordinates []*ResolveCoordinatesResponse_PlaceCoordinate `protobuf:"bytes,1,rep,name=place_coordinates,json=placeCoordinates,proto3" json:"place_coordinates,omitempty"`
}

func (x *ResolveCoordinatesResponse) Reset() {
	*x = ResolveCoordinatesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recon_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveCoordinatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveCoordinatesResponse) ProtoMessage() {}

func (x *ResolveCoordinatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveCoordinatesResponse.ProtoReflect.Descriptor instead.
func (*ResolveCoordinatesResponse) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveCoordinatesResponse) GetPlaceCoordinates() []*ResolveCoordinatesResponse_PlaceCoordinate {
	if x != nil {
		return x.PlaceCoordinates
	}
	return nil
}

type ResolveIdsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InProp  string   `protobuf:"bytes,1,opt,name=in_prop,json=inProp,proto3" json:"in_prop,omitempty"`
	OutProp string   `protobuf:"bytes,2,opt,name=out_prop,json=outProp,proto3" json:"out_prop,omitempty"`
	Ids     []string `protobuf:"bytes,3,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *ResolveIdsRequest) Reset() {
	*x = ResolveIdsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recon_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveIdsRequest) ProtoMessage() {}

func (x *ResolveIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveIdsRequest.ProtoReflect.Descriptor instead.
func (*ResolveIdsRequest) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{6}
}

func (x *ResolveIdsRequest) GetInProp() string {
	if x != nil {
		return x.InProp
	}
	return ""
}

func (x *ResolveIdsRequest) GetOutProp() string {
	if x != nil {
		return x.OutProp
	}
	return ""
}

func (x *ResolveIdsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ResolveIdsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entities []*ResolveIdsResponse_Entity `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
}

func (x *ResolveIdsResponse) Reset() {
	*x = ResolveIdsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recon_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveIdsResponse) ProtoMessage() {}

func (x *ResolveIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveIdsResponse.ProtoReflect.Descriptor instead.
func (*ResolveIdsResponse) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{7}
}

func (x *ResolveIdsResponse) GetEntities() []*ResolveIdsResponse_Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type BulkFindEntitiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entities []*BulkFindEntitiesRequest_Entity `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
}

func (x *BulkFindEntitiesRequest) Reset() {
	*x = BulkFindEntitiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recon_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BulkFindEntitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkFindEntitiesRequest) ProtoMessage() {}

func (x *BulkFindEntitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkFindEntitiesRequest.ProtoReflect.Descriptor instead.
func (*BulkFindEntitiesRequest) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{8}
}

func (x *BulkFindEntitiesRequest) GetEntities() []*BulkFindEntitiesRequest_Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type BulkFindEntitiesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entities []*BulkFindEntitiesResponse_Entity `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
}

func (x *BulkFindEntitiesResponse) Reset() {
	*x = BulkFindEntitiesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recon_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BulkFindEntitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkFindEntitiesResponse) ProtoMessage() {}

func (x *BulkFindEntitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkFindEntitiesResponse.ProtoReflect.Descriptor instead.
func (*BulkFindEntitiesResponse) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{9}
}

func (x *BulkFindEntitiesResponse) GetEntities() []*BulkFindEntitiesResponse_Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type ReconEntities_Entity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// All known IDs of the entity, including the DCID, excluding the ID in the
	// recon request.
	// NOTE: A single ID prop might be repeated.
	Ids []*ReconEntities_Entity_ID `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *ReconEntities_Entity) Reset() {
	*x = ReconEntities_Entity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recon_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReconEntities_Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconEntities_Entity) ProtoMessage() {}

func (x *ReconEntities_Entity) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconEntities_Entity.ProtoReflect.Descriptor instead.
func (*ReconEntities_Entity) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ReconEntities_Entity) GetIds() []*ReconEntities_Entity_ID {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ReconEntities_Entity_ID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prop string `protobuf:"bytes,1,opt,name=prop,proto3" json:"prop,omitempty"`
	Val  string `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *ReconEntities_Entity_ID) Reset() {
	*x = ReconEntities_Entity_ID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recon_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReconEntities_Entity_ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconEntities_Entity_ID) ProtoMessage() {}

func (x *ReconEntities_Entity_ID) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconEntities_Entity_ID.ProtoReflect.Descriptor instead.
func (*ReconEntities_Entity_ID) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *ReconEntities_Entity_ID) GetProp() string {
	if x != nil {
		return x.Prop
	}
	return ""
}

func (x *ReconEntities_Entity_ID) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type CoordinateRecon_Place struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The DCIDs of the places.
	Dcid string `protobuf:"bytes,1,opt,name=dcid,proto3" json:"dcid,omitempty"`
	// If the rectangle is fully contained in the place.
	Full bool `protobuf:"varint,2,opt,name=full,proto3" json:"full,omitempty"`
}

func (x *CoordinateRecon_Place) Reset() {
	*x = CoordinateRecon_Place{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recon_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoordinateRecon_Place) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinateRecon_Place) ProtoMessage() {}

func (x *CoordinateRecon_Place) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinateRecon_Place.ProtoReflect.Descriptor instead.
func (*CoordinateRecon_Place) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CoordinateRecon_Place) GetDcid() string {
	if x != nil {
		return x.Dcid
	}
	return ""
}

func (x *CoordinateRecon_Place) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

type ResolveEntitiesResponse_ResolvedId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids         []*IdWithProperty `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Probability float64           `protobuf:"fixed64,2,opt,name=probability,proto3" json:"probability,omitempty"`
}

func (x *ResolveEntitiesResponse_ResolvedId) Reset() {
	*x = ResolveEntitiesResponse_ResolvedId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recon_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveEntitiesResponse_ResolvedId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveEntitiesResponse_ResolvedId) ProtoMessage() {}

func (x *ResolveEntitiesResponse_ResolvedId) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveEntitiesResponse_ResolvedId.ProtoReflect.Descriptor instead.
func (*ResolveEntitiesResponse_ResolvedId) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ResolveEntitiesResponse_ResolvedId) GetIds() []*IdWithProperty {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ResolveEntitiesResponse_ResolvedId) GetProbability() float64 {
	if x != nil {
		return x.Probability
	}
	return 0
}

type ResolveEntitiesResponse_ResolvedEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceId    string                                `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	ResolvedIds []*ResolveEntitiesResponse_ResolvedId `protobuf:"bytes,2,rep,name=resolved_ids,json=resolvedIds,proto3" json:"resolved_ids,omitempty"`
}

func (x *ResolveEntitiesResponse_ResolvedEntity) Reset() {
	*x = ResolveEntitiesResponse_ResolvedEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recon_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveEntitiesResponse_ResolvedEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveEntitiesResponse_ResolvedEntity) ProtoMessage() {}

func (x *ResolveEntitiesResponse_ResolvedEntity) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveEntitiesResponse_ResolvedEntity.ProtoReflect.Descriptor instead.
func (*ResolveEntitiesResponse_ResolvedEntity) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{3, 1}
}

func (x *ResolveEntitiesResponse_ResolvedEntity) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *ResolveEntitiesResponse_ResolvedEntity) GetResolvedIds() []*ResolveEntitiesResponse_ResolvedId {
	if x != nil {
		return x.ResolvedIds
	}
	return nil
}

type ResolveCoordinatesRequest_Coordinate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *ResolveCoordinatesRequest_Coordinate) Reset() {
	*x = ResolveCoordinatesRequest_Coordinate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recon_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveCoordinatesRequest_Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveCoordinatesRequest_Coordinate) ProtoMessage() {}

func (x *ResolveCoordinatesRequest_Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveCoordinatesRequest_Coordinate.ProtoReflect.Descriptor instead.
func (*ResolveCoordinatesRequest_Coordinate) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ResolveCoordinatesRequest_Coordinate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *ResolveCoordinatesRequest_Coordinate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type ResolveCoordinatesResponse_PlaceCoordinate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude   float64  `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude  float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	PlaceDcids []string `protobuf:"bytes,3,rep,name=place_dcids,json=placeDcids,proto3" json:"place_dcids,omitempty"`
}

func (x *ResolveCoordinatesResponse_PlaceCoordinate) Reset() {
	*x = ResolveCoordinatesResponse_PlaceCoordinate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recon_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveCoordinatesResponse_PlaceCoordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveCoordinatesResponse_PlaceCoordinate) ProtoMessage() {}

func (x *ResolveCoordinatesResponse_PlaceCoordinate) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveCoordinatesResponse_PlaceCoordinate.ProtoReflect.Descriptor instead.
func (*ResolveCoordinatesResponse_PlaceCoordinate) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ResolveCoordinatesResponse_PlaceCoordinate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *ResolveCoordinatesResponse_PlaceCoordinate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *ResolveCoordinatesResponse_PlaceCoordinate) GetPlaceDcids() []string {
	if x != nil {
		return x.PlaceDcids
	}
	return nil
}

type ResolveIdsResponse_Entity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InId   string   `protobuf:"bytes,1,opt,name=in_id,json=inId,proto3" json:"in_id,omitempty"`
	OutIds []string `protobuf:"bytes,2,rep,name=out_ids,json=outIds,proto3" json:"out_ids,omitempty"`
}

func (x *ResolveIdsResponse_Entity) Reset() {
	*x = ResolveIdsResponse_Entity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recon_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolveIdsResponse_Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveIdsResponse_Entity) ProtoMessage() {}

func (x *ResolveIdsResponse_Entity) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveIdsResponse_Entity.ProtoReflect.Descriptor instead.
func (*ResolveIdsResponse_Entity) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ResolveIdsResponse_Entity) GetInId() string {
	if x != nil {
		return x.InId
	}
	return ""
}

func (x *ResolveIdsResponse_Entity) GetOutIds() []string {
	if x != nil {
		return x.OutIds
	}
	return nil
}

type BulkFindEntitiesRequest_Entity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// Optional.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *BulkFindEntitiesRequest_Entity) Reset() {
	*x = BulkFindEntitiesRequest_Entity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recon_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BulkFindEntitiesRequest_Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkFindEntitiesRequest_Entity) ProtoMessage() {}

func (x *BulkFindEntitiesRequest_Entity) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkFindEntitiesRequest_Entity.ProtoReflect.Descriptor instead.
func (*BulkFindEntitiesRequest_Entity) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{8, 0}
}

func (x *BulkFindEntitiesRequest_Entity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BulkFindEntitiesRequest_Entity) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type BulkFindEntitiesResponse_Entity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// Optional.
	Type  string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Dcids []string `protobuf:"bytes,3,rep,name=dcids,proto3" json:"dcids,omitempty"`
}

func (x *BulkFindEntitiesResponse_Entity) Reset() {
	*x = BulkFindEntitiesResponse_Entity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recon_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BulkFindEntitiesResponse_Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkFindEntitiesResponse_Entity) ProtoMessage() {}

func (x *BulkFindEntitiesResponse_Entity) ProtoReflect() protoreflect.Message {
	mi := &file_recon_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkFindEntitiesResponse_Entity.ProtoReflect.Descriptor instead.
func (*BulkFindEntitiesResponse_Entity) Descriptor() ([]byte, []int) {
	return file_recon_proto_rawDescGZIP(), []int{9, 0}
}

func (x *BulkFindEntitiesResponse_Entity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BulkFindEntitiesResponse_Entity) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BulkFindEntitiesResponse_Entity) GetDcids() []string {
	if x != nil {
		return x.Dcids
	}
	return nil
}

var File_recon_proto protoreflect.FileDescriptor

var file_recon_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x72, 0x65, 0x63, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x64,
	0x61, 0x74, 0x61, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x1a, 0x0c, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbc, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x63,
	0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x3d, 0x0a, 0x08, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x64,
	0x61, 0x74, 0x61, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x6e,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52,
	0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x1a, 0x6c, 0x0a, 0x06, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x12, 0x36, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x24, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x52,
	0x65, 0x63, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x2e, 0x49, 0x44, 0x52, 0x03, 0x69, 0x64, 0x73, 0x1a, 0x2a, 0x0a, 0x02, 0x49,
	0x44, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x72, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x72, 0x6f, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x22, 0x7e, 0x0a, 0x0f, 0x43, 0x6f, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x12, 0x3a, 0x0a, 0x06, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x64, 0x61, 0x74,
	0x61, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x6e, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x06,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x73, 0x1a, 0x2f, 0x0a, 0x05, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x63, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x75, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x66, 0x75, 0x6c, 0x6c, 0x22, 0x83, 0x01, 0x0a, 0x16, 0x52, 0x65, 0x73, 0x6f,
	0x6c, 0x76, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x37, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x73, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x53, 0x75, 0x62, 0x47, 0x72, 0x61, 0x70,
	0x68, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x14, 0x77,
	0x61, 0x6e, 0x74, 0x65, 0x64, 0x5f, 0x69, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x12, 0x77, 0x61, 0x6e, 0x74, 0x65,
	0x64, 0x49, 0x64, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x22, 0xde, 0x02,
	0x0a, 0x17, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x60, 0x0a, 0x11, 0x72, 0x65, 0x73,
	0x6f, 0x6c, 0x76, 0x65, 0x64, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x6c,
	0x76, 0x65, 0x64, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x10, 0x72, 0x65, 0x73, 0x6f, 0x6c,
	0x76, 0x65, 0x64, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x1a, 0x5d, 0x0a, 0x0a, 0x52,
	0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x03, 0x69, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x49, 0x64, 0x57, 0x69, 0x74, 0x68, 0x50, 0x72, 0x6f, 0x70, 0x65,
	0x72, 0x74, 0x79, 0x52, 0x03, 0x69, 0x64, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x62,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x70,
	0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x1a, 0x81, 0x01, 0x0a, 0x0e, 0x52,
	0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x12, 0x52, 0x0a, 0x0c, 0x72, 0x65,
	0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x2f, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x52,
	0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x49,
	0x64, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x49, 0x64, 0x73, 0x22, 0xb8,
	0x01, 0x0a, 0x19, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69,
	0x6e, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x53, 0x0a, 0x0b,
	0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x31, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e,
	0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69,
	0x6e, 0x61, 0x74, 0x65, 0x52, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65,
	0x73, 0x1a, 0x46, 0x0a, 0x0a, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c,
	0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09,
	0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0xf0, 0x01, 0x0a, 0x1a, 0x52, 0x65,
	0x73, 0x6f, 0x6c, 0x76, 0x65, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x64, 0x0a, 0x11, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x5f, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x73, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e,
	0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x6c, 0x61,
	0x63, 0x65, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x10, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x1a, 0x6c,
	0x0a, 0x0f, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x5f, 0x64, 0x63, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0a, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x44, 0x63, 0x69, 0x64, 0x73, 0x22, 0x59, 0x0a, 0x11,
	0x52, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x69, 0x6e, 0x50, 0x72, 0x6f, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x75,
	0x74, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x75,
	0x74, 0x50, 0x72, 0x6f, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x90, 0x01, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x6f,
	0x6c, 0x76, 0x65, 0x49, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42,
	0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x26, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x52,
	0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x49, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x1a, 0x36, 0x0a, 0x06, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x13, 0x0a, 0x05,
	0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x49, 0x64, 0x73, 0x22, 0xa2, 0x01, 0x0a, 0x17, 0x42,
	0x75, 0x6c, 0x6b, 0x46, 0x69, 0x6e, 0x64, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x47, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x42, 0x75, 0x6c, 0x6b, 0x46, 0x69, 0x6e, 0x64, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x1a,
	0x3e, 0x0a, 0x06, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22,
	0xba, 0x01, 0x0a, 0x18, 0x42, 0x75, 0x6c, 0x6b, 0x46, 0x69, 0x6e, 0x64, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x08,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x42, 0x75, 0x6c,
	0x6b, 0x46, 0x69, 0x6e, 0x64, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x08, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x1a, 0x54, 0x0a, 0x06, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x63, 0x69, 0x64, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x64, 0x63, 0x69, 0x64, 0x73, 0x42, 0x09, 0x5a, 0x07,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_recon_proto_rawDescOnce sync.Once
	file_recon_proto_rawDescData = file_recon_proto_rawDesc
)

func file_recon_proto_rawDescGZIP() []byte {
	file_recon_proto_rawDescOnce.Do(func() {
		file_recon_proto_rawDescData = protoimpl.X.CompressGZIP(file_recon_proto_rawDescData)
	})
	return file_recon_proto_rawDescData
}

var file_recon_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_recon_proto_goTypes = []interface{}{
	(*ReconEntities)(nil),                              // 0: datacommons.ReconEntities
	(*CoordinateRecon)(nil),                            // 1: datacommons.CoordinateRecon
	(*ResolveEntitiesRequest)(nil),                     // 2: datacommons.ResolveEntitiesRequest
	(*ResolveEntitiesResponse)(nil),                    // 3: datacommons.ResolveEntitiesResponse
	(*ResolveCoordinatesRequest)(nil),                  // 4: datacommons.ResolveCoordinatesRequest
	(*ResolveCoordinatesResponse)(nil),                 // 5: datacommons.ResolveCoordinatesResponse
	(*ResolveIdsRequest)(nil),                          // 6: datacommons.ResolveIdsRequest
	(*ResolveIdsResponse)(nil),                         // 7: datacommons.ResolveIdsResponse
	(*BulkFindEntitiesRequest)(nil),                    // 8: datacommons.BulkFindEntitiesRequest
	(*BulkFindEntitiesResponse)(nil),                   // 9: datacommons.BulkFindEntitiesResponse
	(*ReconEntities_Entity)(nil),                       // 10: datacommons.ReconEntities.Entity
	(*ReconEntities_Entity_ID)(nil),                    // 11: datacommons.ReconEntities.Entity.ID
	(*CoordinateRecon_Place)(nil),                      // 12: datacommons.CoordinateRecon.Place
	(*ResolveEntitiesResponse_ResolvedId)(nil),         // 13: datacommons.ResolveEntitiesResponse.ResolvedId
	(*ResolveEntitiesResponse_ResolvedEntity)(nil),     // 14: datacommons.ResolveEntitiesResponse.ResolvedEntity
	(*ResolveCoordinatesRequest_Coordinate)(nil),       // 15: datacommons.ResolveCoordinatesRequest.Coordinate
	(*ResolveCoordinatesResponse_PlaceCoordinate)(nil), // 16: datacommons.ResolveCoordinatesResponse.PlaceCoordinate
	(*ResolveIdsResponse_Entity)(nil),                  // 17: datacommons.ResolveIdsResponse.Entity
	(*BulkFindEntitiesRequest_Entity)(nil),             // 18: datacommons.BulkFindEntitiesRequest.Entity
	(*BulkFindEntitiesResponse_Entity)(nil),            // 19: datacommons.BulkFindEntitiesResponse.Entity
	(*EntitySubGraph)(nil),                             // 20: datacommons.EntitySubGraph
	(*IdWithProperty)(nil),                             // 21: datacommons.IdWithProperty
}
var file_recon_proto_depIdxs = []int32{
	10, // 0: datacommons.ReconEntities.entities:type_name -> datacommons.ReconEntities.Entity
	12, // 1: datacommons.CoordinateRecon.places:type_name -> datacommons.CoordinateRecon.Place
	20, // 2: datacommons.ResolveEntitiesRequest.entities:type_name -> datacommons.EntitySubGraph
	14, // 3: datacommons.ResolveEntitiesResponse.resolved_entities:type_name -> datacommons.ResolveEntitiesResponse.ResolvedEntity
	15, // 4: datacommons.ResolveCoordinatesRequest.coordinates:type_name -> datacommons.ResolveCoordinatesRequest.Coordinate
	16, // 5: datacommons.ResolveCoordinatesResponse.place_coordinates:type_name -> datacommons.ResolveCoordinatesResponse.PlaceCoordinate
	17, // 6: datacommons.ResolveIdsResponse.entities:type_name -> datacommons.ResolveIdsResponse.Entity
	18, // 7: datacommons.BulkFindEntitiesRequest.entities:type_name -> datacommons.BulkFindEntitiesRequest.Entity
	19, // 8: datacommons.BulkFindEntitiesResponse.entities:type_name -> datacommons.BulkFindEntitiesResponse.Entity
	11, // 9: datacommons.ReconEntities.Entity.ids:type_name -> datacommons.ReconEntities.Entity.ID
	21, // 10: datacommons.ResolveEntitiesResponse.ResolvedId.ids:type_name -> datacommons.IdWithProperty
	13, // 11: datacommons.ResolveEntitiesResponse.ResolvedEntity.resolved_ids:type_name -> datacommons.ResolveEntitiesResponse.ResolvedId
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_recon_proto_init() }
func file_recon_proto_init() {
	if File_recon_proto != nil {
		return
	}
	file_entity_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_recon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReconEntities); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoordinateRecon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveEntitiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recon_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveEntitiesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recon_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveCoordinatesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recon_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveCoordinatesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recon_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveIdsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recon_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveIdsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recon_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BulkFindEntitiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recon_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BulkFindEntitiesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recon_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReconEntities_Entity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recon_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReconEntities_Entity_ID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recon_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoordinateRecon_Place); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recon_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveEntitiesResponse_ResolvedId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recon_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveEntitiesResponse_ResolvedEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recon_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveCoordinatesRequest_Coordinate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recon_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveCoordinatesResponse_PlaceCoordinate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recon_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolveIdsResponse_Entity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recon_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BulkFindEntitiesRequest_Entity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recon_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BulkFindEntitiesResponse_Entity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_recon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_recon_proto_goTypes,
		DependencyIndexes: file_recon_proto_depIdxs,
		MessageInfos:      file_recon_proto_msgTypes,
	}.Build()
	File_recon_proto = out.File
	file_recon_proto_rawDesc = nil
	file_recon_proto_goTypes = nil
	file_recon_proto_depIdxs = nil
}
