// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//  **** IMPORTANT NOTE ****
//
//  The proto of BT data has to match exactly the g3 proto, including tag
//  number.

// REST API URL from the proto in this file:
// ========================================
//    /bulk/stats
//    /stat/all
//    /stat/series
//    /stat/value
// ========================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: stat.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Facet contains the source and measurement information for a
// statistical observation.
type Facet struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ImportName        string                 `protobuf:"bytes,1,opt,name=import_name,json=importName,proto3" json:"import_name,omitempty"`
	ProvenanceUrl     string                 `protobuf:"bytes,2,opt,name=provenance_url,json=provenanceUrl,proto3" json:"provenance_url,omitempty"`
	MeasurementMethod string                 `protobuf:"bytes,3,opt,name=measurement_method,json=measurementMethod,proto3" json:"measurement_method,omitempty"`
	ObservationPeriod string                 `protobuf:"bytes,4,opt,name=observation_period,json=observationPeriod,proto3" json:"observation_period,omitempty"`
	ScalingFactor     string                 `protobuf:"bytes,5,opt,name=scaling_factor,json=scalingFactor,proto3" json:"scaling_factor,omitempty"`
	Unit              string                 `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	IsDcAggregate     bool                   `protobuf:"varint,7,opt,name=is_dc_aggregate,json=isDcAggregate,proto3" json:"is_dc_aggregate,omitempty"`
	IsDcImputed       bool                   `protobuf:"varint,8,opt,name=is_dc_imputed,json=isDcImputed,proto3" json:"is_dc_imputed,omitempty"`
	ProvenanceId      string                 `protobuf:"bytes,9,opt,name=provenance_id,json=provenanceId,proto3" json:"provenance_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Facet) Reset() {
	*x = Facet{}
	mi := &file_stat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Facet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Facet) ProtoMessage() {}

func (x *Facet) ProtoReflect() protoreflect.Message {
	mi := &file_stat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Facet.ProtoReflect.Descriptor instead.
func (*Facet) Descriptor() ([]byte, []int) {
	return file_stat_proto_rawDescGZIP(), []int{0}
}

func (x *Facet) GetImportName() string {
	if x != nil {
		return x.ImportName
	}
	return ""
}

func (x *Facet) GetProvenanceUrl() string {
	if x != nil {
		return x.ProvenanceUrl
	}
	return ""
}

func (x *Facet) GetMeasurementMethod() string {
	if x != nil {
		return x.MeasurementMethod
	}
	return ""
}

func (x *Facet) GetObservationPeriod() string {
	if x != nil {
		return x.ObservationPeriod
	}
	return ""
}

func (x *Facet) GetScalingFactor() string {
	if x != nil {
		return x.ScalingFactor
	}
	return ""
}

func (x *Facet) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Facet) GetIsDcAggregate() bool {
	if x != nil {
		return x.IsDcAggregate
	}
	return false
}

func (x *Facet) GetIsDcImputed() bool {
	if x != nil {
		return x.IsDcImputed
	}
	return false
}

func (x *Facet) GetProvenanceId() string {
	if x != nil {
		return x.ProvenanceId
	}
	return ""
}

type Facets struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Facets        []*Facet               `protobuf:"bytes,1,rep,name=facets,proto3" json:"facets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Facets) Reset() {
	*x = Facets{}
	mi := &file_stat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Facets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Facets) ProtoMessage() {}

func (x *Facets) ProtoReflect() protoreflect.Message {
	mi := &file_stat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Facets.ProtoReflect.Descriptor instead.
func (*Facets) Descriptor() ([]byte, []int) {
	return file_stat_proto_rawDescGZIP(), []int{1}
}

func (x *Facets) GetFacets() []*Facet {
	if x != nil {
		return x.Facets
	}
	return nil
}

// PlaceVariableFacet contains the source and measurement information for a set
// of statistical observations about a place and variable.
type PlaceVariableFacet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Facet *Facet                 `protobuf:"bytes,1,opt,name=facet,proto3" json:"facet,omitempty"`
	// Number of observations for given place + variable + Facet.
	ObsCount int32 `protobuf:"varint,2,opt,name=obs_count,json=obsCount,proto3" json:"obs_count,omitempty"`
	// Latest observation date.
	LatestDate string `protobuf:"bytes,3,opt,name=latest_date,json=latestDate,proto3" json:"latest_date,omitempty"`
	// Earliest observation date.
	EarliestDate string `protobuf:"bytes,4,opt,name=earliest_date,json=earliestDate,proto3" json:"earliest_date,omitempty"`
	// Id of the facet.
	FacetId       string `protobuf:"bytes,5,opt,name=facet_id,json=facetId,proto3" json:"facet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceVariableFacet) Reset() {
	*x = PlaceVariableFacet{}
	mi := &file_stat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceVariableFacet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceVariableFacet) ProtoMessage() {}

func (x *PlaceVariableFacet) ProtoReflect() protoreflect.Message {
	mi := &file_stat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceVariableFacet.ProtoReflect.Descriptor instead.
func (*PlaceVariableFacet) Descriptor() ([]byte, []int) {
	return file_stat_proto_rawDescGZIP(), []int{2}
}

func (x *PlaceVariableFacet) GetFacet() *Facet {
	if x != nil {
		return x.Facet
	}
	return nil
}

func (x *PlaceVariableFacet) GetObsCount() int32 {
	if x != nil {
		return x.ObsCount
	}
	return 0
}

func (x *PlaceVariableFacet) GetLatestDate() string {
	if x != nil {
		return x.LatestDate
	}
	return ""
}

func (x *PlaceVariableFacet) GetEarliestDate() string {
	if x != nil {
		return x.EarliestDate
	}
	return ""
}

func (x *PlaceVariableFacet) GetFacetId() string {
	if x != nil {
		return x.FacetId
	}
	return ""
}

type PlaceVariableFacets struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PlaceVariableFacets []*PlaceVariableFacet  `protobuf:"bytes,1,rep,name=place_variable_facets,json=placeVariableFacets,proto3" json:"place_variable_facets,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PlaceVariableFacets) Reset() {
	*x = PlaceVariableFacets{}
	mi := &file_stat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceVariableFacets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceVariableFacets) ProtoMessage() {}

func (x *PlaceVariableFacets) ProtoReflect() protoreflect.Message {
	mi := &file_stat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceVariableFacets.ProtoReflect.Descriptor instead.
func (*PlaceVariableFacets) Descriptor() ([]byte, []int) {
	return file_stat_proto_rawDescGZIP(), []int{3}
}

func (x *PlaceVariableFacets) GetPlaceVariableFacets() []*PlaceVariableFacet {
	if x != nil {
		return x.PlaceVariableFacets
	}
	return nil
}

type PointStat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// date in IOS-8601 format
	Date  string   `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Value *float64 `protobuf:"fixed64,2,opt,name=value,proto3,oneof" json:"value,omitempty"`
	// Full metadata of the stat. This is set when the proto is used statalone,
	// ex, in place page cache.
	Metadata *Facet `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Hash of the metadata, this is to be used together with a map from
	// the hash to the full metatdata. This is set in /stat/set/within-place/*
	// APIs.
	MetaHash string `protobuf:"bytes,4,opt,name=meta_hash,json=metaHash,proto3" json:"meta_hash,omitempty"`
	// Same as meta_hash, used in V1 API.
	Facet string `protobuf:"bytes,5,opt,name=facet,proto3" json:"facet,omitempty"`
	// Optional observation-level attributes. Only populated by APIs backed by
	// observation storage that supports point-level attributes.
	Attributes    map[string]string `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointStat) Reset() {
	*x = PointStat{}
	mi := &file_stat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointStat) ProtoMessage() {}

func (x *PointStat) ProtoReflect() protoreflect.Message {
	mi := &file_stat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointStat.ProtoReflect.Descriptor instead.
func (*PointStat) Descriptor() ([]byte, []int) {
	return file_stat_proto_rawDescGZIP(), []int{4}
}

func (x *PointStat) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *PointStat) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *PointStat) GetMetadata() *Facet {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PointStat) GetMetaHash() string {
	if x != nil {
		return x.MetaHash
	}
	return ""
}

func (x *PointStat) GetFacet() string {
	if x != nil {
		return x.Facet
	}
	return ""
}

func (x *PointStat) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type SourceSeries struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Val               map[string]float64     `protobuf:"bytes,1,rep,name=val,proto3" json:"val,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	MeasurementMethod string                 `protobuf:"bytes,3,opt,name=measurement_method,json=measurementMethod,proto3" json:"measurement_method,omitempty"`
	ObservationPeriod string                 `protobuf:"bytes,4,opt,name=observation_period,json=observationPeriod,proto3" json:"observation_period,omitempty"`
	ImportName        string                 `protobuf:"bytes,5,opt,name=import_name,json=importName,proto3" json:"import_name,omitempty"`
	ProvenanceDomain  string                 `protobuf:"bytes,6,opt,name=provenance_domain,json=provenanceDomain,proto3" json:"provenance_domain,omitempty"`
	ScalingFactor     string                 `protobuf:"bytes,7,opt,name=scaling_factor,json=scalingFactor,proto3" json:"scaling_factor,omitempty"`
	Unit              string                 `protobuf:"bytes,8,opt,name=unit,proto3" json:"unit,omitempty"`
	IsDcAggregate     bool                   `protobuf:"varint,9,opt,name=is_dc_aggregate,json=isDcAggregate,proto3" json:"is_dc_aggregate,omitempty"`
	ProvenanceUrl     string                 `protobuf:"bytes,10,opt,name=provenance_url,json=provenanceUrl,proto3" json:"provenance_url,omitempty"`
	// Only used for latest date obs collection.
	PlaceToLatestDate map[string]string `protobuf:"bytes,11,rep,name=place_to_latest_date,json=placeToLatestDate,proto3" json:"place_to_latest_date,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IsDcImputed       bool              `protobuf:"varint,13,opt,name=is_dc_imputed,json=isDcImputed,proto3" json:"is_dc_imputed,omitempty"`
	ProvenanceId      string            `protobuf:"bytes,14,opt,name=provenance_id,json=provenanceId,proto3" json:"provenance_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SourceSeries) Reset() {
	*x = SourceSeries{}
	mi := &file_stat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceSeries) ProtoMessage() {}

func (x *SourceSeries) ProtoReflect() protoreflect.Message {
	mi := &file_stat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceSeries.ProtoReflect.Descriptor instead.
func (*SourceSeries) Descriptor() ([]byte, []int) {
	return file_stat_proto_rawDescGZIP(), []int{5}
}

func (x *SourceSeries) GetVal() map[string]float64 {
	if x != nil {
		return x.Val
	}
	return nil
}

func (x *SourceSeries) GetMeasurementMethod() string {
	if x != nil {
		return x.MeasurementMethod
	}
	return ""
}

func (x *SourceSeries) GetObservationPeriod() string {
	if x != nil {
		return x.ObservationPeriod
	}
	return ""
}

func (x *SourceSeries) GetImportName() string {
	if x != nil {
		return x.ImportName
	}
	return ""
}

func (x *SourceSeries) GetProvenanceDomain() string {
	if x != nil {
		return x.ProvenanceDomain
	}
	return ""
}

func (x *SourceSeries) GetScalingFactor() string {
	if x != nil {
		return x.ScalingFactor
	}
	return ""
}

func (x *SourceSeries) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *SourceSeries) GetIsDcAggregate() bool {
	if x != nil {
		return x.IsDcAggregate
	}
	return false
}

func (x *SourceSeries) GetProvenanceUrl() string {
	if x != nil {
		return x.ProvenanceUrl
	}
	return ""
}

func (x *SourceSeries) GetPlaceToLatestDate() map[string]string {
	if x != nil {
		return x.PlaceToLatestDate
	}
	return nil
}

func (x *SourceSeries) GetIsDcImputed() bool {
	if x != nil {
		return x.IsDcImputed
	}
	return false
}

func (x *SourceSeries) GetProvenanceId() string {
	if x != nil {
		return x.ProvenanceId
	}
	return ""
}

// Represents a time series from a source.
type Series struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map from date to stat value.
	Val map[string]float64 `protobuf:"bytes,1,rep,name=val,proto3" json:"val,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	// Series metadata.
	Metadata      *Facet `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Series) Reset() {
	*x = Series{}
	mi := &file_stat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Series) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Series) ProtoMessage() {}

func (x *Series) ProtoReflect() protoreflect.Message {
	mi := &file_stat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Series.ProtoReflect.Descriptor instead.
func (*Series) Descriptor() ([]byte, []int) {
	return file_stat_proto_rawDescGZIP(), []int{6}
}

func (x *Series) GetVal() map[string]float64 {
	if x != nil {
		return x.Val
	}
	return nil
}

func (x *Series) GetMetadata() *Facet {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Represents observation time series data.
type ObsTimeSeries struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PlaceName string                 `protobuf:"bytes,3,opt,name=place_name,json=placeName,proto3" json:"place_name,omitempty"`
	// Only used for time series.
	// All valid place types for the given place_dcid
	PlaceTypes    []string        `protobuf:"bytes,7,rep,name=place_types,json=placeTypes,proto3" json:"place_types,omitempty"`
	PlaceDcid     string          `protobuf:"bytes,5,opt,name=place_dcid,json=placeDcid,proto3" json:"place_dcid,omitempty"` // Only set if the key uses mid.
	SourceSeries  []*SourceSeries `protobuf:"bytes,6,rep,name=source_series,json=sourceSeries,proto3" json:"source_series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObsTimeSeries) Reset() {
	*x = ObsTimeSeries{}
	mi := &file_stat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObsTimeSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObsTimeSeries) ProtoMessage() {}

func (x *ObsTimeSeries) ProtoReflect() protoreflect.Message {
	mi := &file_stat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObsTimeSeries.ProtoReflect.Descriptor instead.
func (*ObsTimeSeries) Descriptor() ([]byte, []int) {
	return file_stat_proto_rawDescGZIP(), []int{7}
}

func (x *ObsTimeSeries) GetPlaceName() string {
	if x != nil {
		return x.PlaceName
	}
	return ""
}

func (x *ObsTimeSeries) GetPlaceTypes() []string {
	if x != nil {
		return x.PlaceTypes
	}
	return nil
}

func (x *ObsTimeSeries) GetPlaceDcid() string {
	if x != nil {
		return x.PlaceDcid
	}
	return ""
}

func (x *ObsTimeSeries) GetSourceSeries() []*SourceSeries {
	if x != nil {
		return x.SourceSeries
	}
	return nil
}

// A collection of observation values for various places with the same parent
// and place type, for given measured property, observation period, stat type,
// observation date, pop type, and an optional list of pop PVs.
type ObsCollection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceCohorts []*SourceSeries        `protobuf:"bytes,5,rep,name=source_cohorts,json=sourceCohorts,proto3" json:"source_cohorts,omitempty"`
	// A map of place DCID to all of the place's types
	// All places in the val/str_val have types here
	PlaceDcidToTypes map[string]*ObsCollection_PlaceTypes `protobuf:"bytes,17,rep,name=place_dcid_to_types,json=placeDcidToTypes,proto3" json:"place_dcid_to_types,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ObsCollection) Reset() {
	*x = ObsCollection{}
	mi := &file_stat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObsCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObsCollection) ProtoMessage() {}

func (x *ObsCollection) ProtoReflect() protoreflect.Message {
	mi := &file_stat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObsCollection.ProtoReflect.Descriptor instead.
func (*ObsCollection) Descriptor() ([]byte, []int) {
	return file_stat_proto_rawDescGZIP(), []int{8}
}

func (x *ObsCollection) GetSourceCohorts() []*SourceSeries {
	if x != nil {
		return x.SourceCohorts
	}
	return nil
}

func (x *ObsCollection) GetPlaceDcidToTypes() map[string]*ObsCollection_PlaceTypes {
	if x != nil {
		return x.PlaceDcidToTypes
	}
	return nil
}

// Wrapper for observation data.
type ChartStore struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Val:
	//
	//	*ChartStore_ObsTimeSeries
	//	*ChartStore_ObsCollection
	Val           isChartStore_Val `protobuf_oneof:"val"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChartStore) Reset() {
	*x = ChartStore{}
	mi := &file_stat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChartStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChartStore) ProtoMessage() {}

func (x *ChartStore) ProtoReflect() protoreflect.Message {
	mi := &file_stat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChartStore.ProtoReflect.Descriptor instead.
func (*ChartStore) Descriptor() ([]byte, []int) {
	return file_stat_proto_rawDescGZIP(), []int{9}
}

func (x *ChartStore) GetVal() isChartStore_Val {
	if x != nil {
		return x.Val
	}
	return nil
}

func (x *ChartStore) GetObsTimeSeries() *ObsTimeSeries {
	if x != nil {
		if x, ok := x.Val.(*ChartStore_ObsTimeSeries); ok {
			return x.ObsTimeSeries
		}
	}
	return nil
}

func (x *ChartStore) GetObsCollection() *ObsCollection {
	if x != nil {
		if x, ok := x.Val.(*ChartStore_ObsCollection); ok {
			return x.ObsCollection
		}
	}
	return nil
}

type isChartStore_Val interface {
	isChartStore_Val()
}

type ChartStore_ObsTimeSeries struct {
	ObsTimeSeries *ObsTimeSeries `protobuf:"bytes,1,opt,name=obs_time_series,json=obsTimeSeries,proto3,oneof"`
}

type ChartStore_ObsCollection struct {
	ObsCollection *ObsCollection `protobuf:"bytes,2,opt,name=obs_collection,json=obsCollection,proto3,oneof"`
}

func (*ChartStore_ObsTimeSeries) isChartStore_Val() {}

func (*ChartStore_ObsCollection) isChartStore_Val() {}

// TODO(shifucun): deprecate this and use StatVarSeries when migrating
// /stat/all to v1.
type PlaceStat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key is stat var dcid.
	StatVarData   map[string]*ObsTimeSeries `protobuf:"bytes,3,rep,name=stat_var_data,json=statVarData,proto3" json:"stat_var_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceStat) Reset() {
	*x = PlaceStat{}
	mi := &file_stat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceStat) ProtoMessage() {}

func (x *PlaceStat) ProtoReflect() protoreflect.Message {
	mi := &file_stat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceStat.ProtoReflect.Descriptor instead.
func (*PlaceStat) Descriptor() ([]byte, []int) {
	return file_stat_proto_rawDescGZIP(), []int{10}
}

func (x *PlaceStat) GetStatVarData() map[string]*ObsTimeSeries {
	if x != nil {
		return x.StatVarData
	}
	return nil
}

// Hold mapping from stat var id to Series struct. This is different from
// StatVarObsSeries that the "Series" is processed time series with metadata
// while "ObsTimeSeries" is the raw series from cache.
type StatVarSeries struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key is stat var dcid.
	Data          map[string]*Series `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatVarSeries) Reset() {
	*x = StatVarSeries{}
	mi := &file_stat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatVarSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatVarSeries) ProtoMessage() {}

func (x *StatVarSeries) ProtoReflect() protoreflect.Message {
	mi := &file_stat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatVarSeries.ProtoReflect.Descriptor instead.
func (*StatVarSeries) Descriptor() ([]byte, []int) {
	return file_stat_proto_rawDescGZIP(), []int{11}
}

func (x *StatVarSeries) GetData() map[string]*Series {
	if x != nil {
		return x.Data
	}
	return nil
}

// Request message for GetStats.
type GetStatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The dcids of the place.
	Place []string `protobuf:"bytes,1,rep,name=place,proto3" json:"place,omitempty"`
	// The dcid of the StatisticalVariable.
	StatsVar string `protobuf:"bytes,2,opt,name=stats_var,json=statsVar,proto3" json:"stats_var,omitempty"`
	// (Optional) The measurement method of the observation. If not specified,
	// stats series with any measurement methods could be returned.
	MeasurementMethod string `protobuf:"bytes,4,opt,name=measurement_method,json=measurementMethod,proto3" json:"measurement_method,omitempty"`
	// (Optional) The unit of the observation. If not specified, stats series with
	// any unit could be returned.
	Unit string `protobuf:"bytes,5,opt,name=unit,proto3" json:"unit,omitempty"`
	// (Optional) The observation period of the observation. If not specified,
	// stats series with any observation period could be returned.
	ObservationPeriod string `protobuf:"bytes,6,opt,name=observation_period,json=observationPeriod,proto3" json:"observation_period,omitempty"`
	// (optional) scaling factor of the observation.
	ScalingFactor string `protobuf:"bytes,7,opt,name=scaling_factor,json=scalingFactor,proto3" json:"scaling_factor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_stat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_stat_proto_rawDescGZIP(), []int{12}
}

func (x *GetStatsRequest) GetPlace() []string {
	if x != nil {
		return x.Place
	}
	return nil
}

func (x *GetStatsRequest) GetStatsVar() string {
	if x != nil {
		return x.StatsVar
	}
	return ""
}

func (x *GetStatsRequest) GetMeasurementMethod() string {
	if x != nil {
		return x.MeasurementMethod
	}
	return ""
}

func (x *GetStatsRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *GetStatsRequest) GetObservationPeriod() string {
	if x != nil {
		return x.ObservationPeriod
	}
	return ""
}

func (x *GetStatsRequest) GetScalingFactor() string {
	if x != nil {
		return x.ScalingFactor
	}
	return ""
}

// Response of GetStats
type GetStatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The JSON payload.
	Payload       string `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_stat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_stat_proto_rawDescGZIP(), []int{13}
}

func (x *GetStatsResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

// Request for GetStat service.
type GetStatValueRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// dcid of the place.
	Place string `protobuf:"bytes,1,opt,name=place,proto3" json:"place,omitempty"`
	// dcid of the stat var.
	StatVar string `protobuf:"bytes,2,opt,name=stat_var,json=statVar,proto3" json:"stat_var,omitempty"`
	// (optional) date of the stat. The latest date will be used if unspecified.
	Date string `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	// (optional) measurement method of the observation, ex: "CensusACS5yrSurvey".
	MeasurementMethod string `protobuf:"bytes,4,opt,name=measurement_method,json=measurementMethod,proto3" json:"measurement_method,omitempty"`
	// (optional) observation period of the observation, ex: "P1Y".
	ObservationPeriod string `protobuf:"bytes,5,opt,name=observation_period,json=observationPeriod,proto3" json:"observation_period,omitempty"`
	// (optional) unit of the observation.
	Unit string `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	// (optional) scaling factor of the observation.
	ScalingFactor string `protobuf:"bytes,7,opt,name=scaling_factor,json=scalingFactor,proto3" json:"scaling_factor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatValueRequest) Reset() {
	*x = GetStatValueRequest{}
	mi := &file_stat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatValueRequest) ProtoMessage() {}

func (x *GetStatValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatValueRequest.ProtoReflect.Descriptor instead.
func (*GetStatValueRequest) Descriptor() ([]byte, []int) {
	return file_stat_proto_rawDescGZIP(), []int{14}
}

func (x *GetStatValueRequest) GetPlace() string {
	if x != nil {
		return x.Place
	}
	return ""
}

func (x *GetStatValueRequest) GetStatVar() string {
	if x != nil {
		return x.StatVar
	}
	return ""
}

func (x *GetStatValueRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetStatValueRequest) GetMeasurementMethod() string {
	if x != nil {
		return x.MeasurementMethod
	}
	return ""
}

func (x *GetStatValueRequest) GetObservationPeriod() string {
	if x != nil {
		return x.ObservationPeriod
	}
	return ""
}

func (x *GetStatValueRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *GetStatValueRequest) GetScalingFactor() string {
	if x != nil {
		return x.ScalingFactor
	}
	return ""
}

type GetStatValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *float64               `protobuf:"fixed64,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatValueResponse) Reset() {
	*x = GetStatValueResponse{}
	mi := &file_stat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatValueResponse) ProtoMessage() {}

func (x *GetStatValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatValueResponse.ProtoReflect.Descriptor instead.
func (*GetStatValueResponse) Descriptor() ([]byte, []int) {
	return file_stat_proto_rawDescGZIP(), []int{15}
}

func (x *GetStatValueResponse) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

// Request for GetStatSeries service.
type GetStatSeriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// dcid of the place.
	Place string `protobuf:"bytes,1,opt,name=place,proto3" json:"place,omitempty"`
	// dcid of the stat var.
	StatVar string `protobuf:"bytes,2,opt,name=stat_var,json=statVar,proto3" json:"stat_var,omitempty"`
	// (optional) measurement method of the observation, ex: "CensusACS5yrSurvey".
	MeasurementMethod string `protobuf:"bytes,3,opt,name=measurement_method,json=measurementMethod,proto3" json:"measurement_method,omitempty"`
	// (optional) observation period of the observation, ex: "P1Y".
	ObservationPeriod string `protobuf:"bytes,4,opt,name=observation_period,json=observationPeriod,proto3" json:"observation_period,omitempty"`
	// (optional) unit of the observation.
	Unit string `protobuf:"bytes,5,opt,name=unit,proto3" json:"unit,omitempty"`
	// (optional) scaling factor of the observation.
	ScalingFactor string `protobuf:"bytes,6,opt,name=scaling_factor,json=scalingFactor,proto3" json:"scaling_factor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatSeriesRequest) Reset() {
	*x = GetStatSeriesRequest{}
	mi := &file_stat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatSeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatSeriesRequest) ProtoMessage() {}

func (x *GetStatSeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatSeriesRequest.ProtoReflect.Descriptor instead.
func (*GetStatSeriesRequest) Descriptor() ([]byte, []int) {
	return file_stat_proto_rawDescGZIP(), []int{16}
}

func (x *GetStatSeriesRequest) GetPlace() string {
	if x != nil {
		return x.Place
	}
	return ""
}

func (x *GetStatSeriesRequest) GetStatVar() string {
	if x != nil {
		return x.StatVar
	}
	return ""
}

func (x *GetStatSeriesRequest) GetMeasurementMethod() string {
	if x != nil {
		return x.MeasurementMethod
	}
	return ""
}

func (x *GetStatSeriesRequest) GetObservationPeriod() string {
	if x != nil {
		return x.ObservationPeriod
	}
	return ""
}

func (x *GetStatSeriesRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *GetStatSeriesRequest) GetScalingFactor() string {
	if x != nil {
		return x.ScalingFactor
	}
	return ""
}

// Response for GetStatSeries service.
type GetStatSeriesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A map from ISO date to stat value.
	Series        map[string]float64 `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatSeriesResponse) Reset() {
	*x = GetStatSeriesResponse{}
	mi := &file_stat_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatSeriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatSeriesResponse) ProtoMessage() {}

func (x *GetStatSeriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stat_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatSeriesResponse.ProtoReflect.Descriptor instead.
func (*GetStatSeriesResponse) Descriptor() ([]byte, []int) {
	return file_stat_proto_rawDescGZIP(), []int{17}
}

func (x *GetStatSeriesResponse) GetSeries() map[string]float64 {
	if x != nil {
		return x.Series
	}
	return nil
}

// Request for GetStatAll service.
type GetStatAllRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// dcids of the place.
	Places []string `protobuf:"bytes,1,rep,name=places,proto3" json:"places,omitempty"`
	// dcids of the stat var.
	StatVars      []string `protobuf:"bytes,2,rep,name=stat_vars,json=statVars,proto3" json:"stat_vars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatAllRequest) Reset() {
	*x = GetStatAllRequest{}
	mi := &file_stat_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatAllRequest) ProtoMessage() {}

func (x *GetStatAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stat_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatAllRequest.ProtoReflect.Descriptor instead.
func (*GetStatAllRequest) Descriptor() ([]byte, []int) {
	return file_stat_proto_rawDescGZIP(), []int{18}
}

func (x *GetStatAllRequest) GetPlaces() []string {
	if x != nil {
		return x.Places
	}
	return nil
}

func (x *GetStatAllRequest) GetStatVars() []string {
	if x != nil {
		return x.StatVars
	}
	return nil
}

// Response for GetStatAll service.
//
// The response is a two level map, with the first level keyed by place dcid,
// and the second level keyed by the stat var dcid.
// Each leaf object contains multiple source series with <date, value> object
// and observation metadata.
//
// The response is transcoded by esp:
// https://cloud.google.com/endpoints/docs/grpc/grpc-service-config Example
// response after esp transcoding is like below.
//
//	{
//	  placeData: {
//	    "geoId/01": {
//	      statVarData: {
//	        "statvar1": {
//	          "placeName": "City of Mountain View",
//	          "sourceSeries": [
//	            {
//	              "val": {
//	                "2008": 2116,
//	                "2009": 2155,
//	                "2010": 1633,
//	                "2011": 1509,
//	                "2012": 1581,
//	                "2013": 1867,
//	                "2014": 1770,
//	                "2015": 2201,
//	                "2016": 1913,
//	                "2017": 2138
//	              },
//	              "observationPeriod": "P1Y",
//	              "importName": "FBIGovCrime",
//	              "provenanceDomain": "fbi.gov"
//	            }
//	          ]
//	        },
//	      }
//	    },
//	    "geoId/02": {
//	      statVarData: {
//	        "statvar3": {...},
//	      }
//	    }
//	  }
//	}
type GetStatAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaceData     map[string]*PlaceStat  `protobuf:"bytes,1,rep,name=place_data,json=placeData,proto3" json:"place_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatAllResponse) Reset() {
	*x = GetStatAllResponse{}
	mi := &file_stat_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatAllResponse) ProtoMessage() {}

func (x *GetStatAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stat_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatAllResponse.ProtoReflect.Descriptor instead.
func (*GetStatAllResponse) Descriptor() ([]byte, []int) {
	return file_stat_proto_rawDescGZIP(), []int{19}
}

func (x *GetStatAllResponse) GetPlaceData() map[string]*PlaceStat {
	if x != nil {
		return x.PlaceData
	}
	return nil
}

type StatDate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map from date to the number of places.
	DatePlaceCount map[string]float64 `protobuf:"bytes,1,rep,name=date_place_count,json=datePlaceCount,proto3" json:"date_place_count,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Metadata       *Facet             `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatDate) Reset() {
	*x = StatDate{}
	mi := &file_stat_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatDate) ProtoMessage() {}

func (x *StatDate) ProtoReflect() protoreflect.Message {
	mi := &file_stat_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatDate.ProtoReflect.Descriptor instead.
func (*StatDate) Descriptor() ([]byte, []int) {
	return file_stat_proto_rawDescGZIP(), []int{20}
}

func (x *StatDate) GetDatePlaceCount() map[string]float64 {
	if x != nil {
		return x.DatePlaceCount
	}
	return nil
}

func (x *StatDate) GetMetadata() *Facet {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type StatDateList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatDate      []*StatDate            `protobuf:"bytes,1,rep,name=stat_date,json=statDate,proto3" json:"stat_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatDateList) Reset() {
	*x = StatDateList{}
	mi := &file_stat_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatDateList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatDateList) ProtoMessage() {}

func (x *StatDateList) ProtoReflect() protoreflect.Message {
	mi := &file_stat_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatDateList.ProtoReflect.Descriptor instead.
func (*StatDateList) Descriptor() ([]byte, []int) {
	return file_stat_proto_rawDescGZIP(), []int{21}
}

func (x *StatDateList) GetStatDate() []*StatDate {
	if x != nil {
		return x.StatDate
	}
	return nil
}

// All place types for a given place, used in place_dcid_to_types.
type ObsCollection_PlaceTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []string               `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObsCollection_PlaceTypes) Reset() {
	*x = ObsCollection_PlaceTypes{}
	mi := &file_stat_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObsCollection_PlaceTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObsCollection_PlaceTypes) ProtoMessage() {}

func (x *ObsCollection_PlaceTypes) ProtoReflect() protoreflect.Message {
	mi := &file_stat_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObsCollection_PlaceTypes.ProtoReflect.Descriptor instead.
func (*ObsCollection_PlaceTypes) Descriptor() ([]byte, []int) {
	return file_stat_proto_rawDescGZIP(), []int{8, 0}
}

func (x *ObsCollection_PlaceTypes) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

var File_stat_proto protoreflect.FileDescriptor

const file_stat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"stat.proto\x12\vdatacommons\"\xd9\x02\n" +
	"\x05Facet\x12\x1f\n" +
	"\vimport_name\x18\x01 \x01(\tR\n" +
	"importName\x12%\n" +
	"\x0eprovenance_url\x18\x02 \x01(\tR\rprovenanceUrl\x12-\n" +
	"\x12measurement_method\x18\x03 \x01(\tR\x11measurementMethod\x12-\n" +
	"\x12observation_period\x18\x04 \x01(\tR\x11observationPeriod\x12%\n" +
	"\x0escaling_factor\x18\x05 \x01(\tR\rscalingFactor\x12\x12\n" +
	"\x04unit\x18\x06 \x01(\tR\x04unit\x12&\n" +
	"\x0fis_dc_aggregate\x18\a \x01(\bR\risDcAggregate\x12\"\n" +
	"\ris_dc_imputed\x18\b \x01(\bR\visDcImputed\x12#\n" +
	"\rprovenance_id\x18\t \x01(\tR\fprovenanceId\"4\n" +
	"\x06Facets\x12*\n" +
	"\x06facets\x18\x01 \x03(\v2\x12.datacommons.FacetR\x06facets\"\xbc\x01\n" +
	"\x12PlaceVariableFacet\x12(\n" +
	"\x05facet\x18\x01 \x01(\v2\x12.datacommons.FacetR\x05facet\x12\x1b\n" +
	"\tobs_count\x18\x02 \x01(\x05R\bobsCount\x12\x1f\n" +
	"\vlatest_date\x18\x03 \x01(\tR\n" +
	"latestDate\x12#\n" +
	"\rearliest_date\x18\x04 \x01(\tR\fearliestDate\x12\x19\n" +
	"\bfacet_id\x18\x05 \x01(\tR\afacetId\"j\n" +
	"\x13PlaceVariableFacets\x12S\n" +
	"\x15place_variable_facets\x18\x01 \x03(\v2\x1f.datacommons.PlaceVariableFacetR\x13placeVariableFacets\"\xae\x02\n" +
	"\tPointStat\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x19\n" +
	"\x05value\x18\x02 \x01(\x01H\x00R\x05value\x88\x01\x01\x12.\n" +
	"\bmetadata\x18\x03 \x01(\v2\x12.datacommons.FacetR\bmetadata\x12\x1b\n" +
	"\tmeta_hash\x18\x04 \x01(\tR\bmetaHash\x12\x14\n" +
	"\x05facet\x18\x05 \x01(\tR\x05facet\x12F\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v2&.datacommons.PointStat.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06_value\"\xaa\x05\n" +
	"\fSourceSeries\x124\n" +
	"\x03val\x18\x01 \x03(\v2\".datacommons.SourceSeries.ValEntryR\x03val\x12-\n" +
	"\x12measurement_method\x18\x03 \x01(\tR\x11measurementMethod\x12-\n" +
	"\x12observation_period\x18\x04 \x01(\tR\x11observationPeriod\x12\x1f\n" +
	"\vimport_name\x18\x05 \x01(\tR\n" +
	"importName\x12+\n" +
	"\x11provenance_domain\x18\x06 \x01(\tR\x10provenanceDomain\x12%\n" +
	"\x0escaling_factor\x18\a \x01(\tR\rscalingFactor\x12\x12\n" +
	"\x04unit\x18\b \x01(\tR\x04unit\x12&\n" +
	"\x0fis_dc_aggregate\x18\t \x01(\bR\risDcAggregate\x12%\n" +
	"\x0eprovenance_url\x18\n" +
	" \x01(\tR\rprovenanceUrl\x12a\n" +
	"\x14place_to_latest_date\x18\v \x03(\v20.datacommons.SourceSeries.PlaceToLatestDateEntryR\x11placeToLatestDate\x12\"\n" +
	"\ris_dc_imputed\x18\r \x01(\bR\visDcImputed\x12#\n" +
	"\rprovenance_id\x18\x0e \x01(\tR\fprovenanceId\x1a6\n" +
	"\bValEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1aD\n" +
	"\x16PlaceToLatestDateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x02\x10\x03\"\xa0\x01\n" +
	"\x06Series\x12.\n" +
	"\x03val\x18\x01 \x03(\v2\x1c.datacommons.Series.ValEntryR\x03val\x12.\n" +
	"\bmetadata\x18\x02 \x01(\v2\x12.datacommons.FacetR\bmetadata\x1a6\n" +
	"\bValEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xae\x01\n" +
	"\rObsTimeSeries\x12\x1d\n" +
	"\n" +
	"place_name\x18\x03 \x01(\tR\tplaceName\x12\x1f\n" +
	"\vplace_types\x18\a \x03(\tR\n" +
	"placeTypes\x12\x1d\n" +
	"\n" +
	"place_dcid\x18\x05 \x01(\tR\tplaceDcid\x12>\n" +
	"\rsource_series\x18\x06 \x03(\v2\x19.datacommons.SourceSeriesR\fsourceSeries\"\xda\x02\n" +
	"\rObsCollection\x12@\n" +
	"\x0esource_cohorts\x18\x05 \x03(\v2\x19.datacommons.SourceSeriesR\rsourceCohorts\x12_\n" +
	"\x13place_dcid_to_types\x18\x11 \x03(\v20.datacommons.ObsCollection.PlaceDcidToTypesEntryR\x10placeDcidToTypes\x1a\"\n" +
	"\n" +
	"PlaceTypes\x12\x14\n" +
	"\x05types\x18\x01 \x03(\tR\x05types\x1aj\n" +
	"\x15PlaceDcidToTypesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12;\n" +
	"\x05value\x18\x02 \x01(\v2%.datacommons.ObsCollection.PlaceTypesR\x05value:\x028\x01J\x04\b\x01\x10\x02J\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x04\x10\x05\"\x9e\x01\n" +
	"\n" +
	"ChartStore\x12D\n" +
	"\x0fobs_time_series\x18\x01 \x01(\v2\x1a.datacommons.ObsTimeSeriesH\x00R\robsTimeSeries\x12C\n" +
	"\x0eobs_collection\x18\x02 \x01(\v2\x1a.datacommons.ObsCollectionH\x00R\robsCollectionB\x05\n" +
	"\x03val\"\xb4\x01\n" +
	"\tPlaceStat\x12K\n" +
	"\rstat_var_data\x18\x03 \x03(\v2'.datacommons.PlaceStat.StatVarDataEntryR\vstatVarData\x1aZ\n" +
	"\x10StatVarDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.datacommons.ObsTimeSeriesR\x05value:\x028\x01\"\x97\x01\n" +
	"\rStatVarSeries\x128\n" +
	"\x04data\x18\x01 \x03(\v2$.datacommons.StatVarSeries.DataEntryR\x04data\x1aL\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.datacommons.SeriesR\x05value:\x028\x01\"\xdd\x01\n" +
	"\x0fGetStatsRequest\x12\x14\n" +
	"\x05place\x18\x01 \x03(\tR\x05place\x12\x1b\n" +
	"\tstats_var\x18\x02 \x01(\tR\bstatsVar\x12-\n" +
	"\x12measurement_method\x18\x04 \x01(\tR\x11measurementMethod\x12\x12\n" +
	"\x04unit\x18\x05 \x01(\tR\x04unit\x12-\n" +
	"\x12observation_period\x18\x06 \x01(\tR\x11observationPeriod\x12%\n" +
	"\x0escaling_factor\x18\a \x01(\tR\rscalingFactor\",\n" +
	"\x10GetStatsResponse\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"\xf3\x01\n" +
	"\x13GetStatValueRequest\x12\x14\n" +
	"\x05place\x18\x01 \x01(\tR\x05place\x12\x19\n" +
	"\bstat_var\x18\x02 \x01(\tR\astatVar\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12-\n" +
	"\x12measurement_method\x18\x04 \x01(\tR\x11measurementMethod\x12-\n" +
	"\x12observation_period\x18\x05 \x01(\tR\x11observationPeriod\x12\x12\n" +
	"\x04unit\x18\x06 \x01(\tR\x04unit\x12%\n" +
	"\x0escaling_factor\x18\a \x01(\tR\rscalingFactor\";\n" +
	"\x14GetStatValueResponse\x12\x19\n" +
	"\x05value\x18\x01 \x01(\x01H\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"\xe0\x01\n" +
	"\x14GetStatSeriesRequest\x12\x14\n" +
	"\x05place\x18\x01 \x01(\tR\x05place\x12\x19\n" +
	"\bstat_var\x18\x02 \x01(\tR\astatVar\x12-\n" +
	"\x12measurement_method\x18\x03 \x01(\tR\x11measurementMethod\x12-\n" +
	"\x12observation_period\x18\x04 \x01(\tR\x11observationPeriod\x12\x12\n" +
	"\x04unit\x18\x05 \x01(\tR\x04unit\x12%\n" +
	"\x0escaling_factor\x18\x06 \x01(\tR\rscalingFactor\"\x9a\x01\n" +
	"\x15GetStatSeriesResponse\x12F\n" +
	"\x06series\x18\x01 \x03(\v2..datacommons.GetStatSeriesResponse.SeriesEntryR\x06series\x1a9\n" +
	"\vSeriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"H\n" +
	"\x11GetStatAllRequest\x12\x16\n" +
	"\x06places\x18\x01 \x03(\tR\x06places\x12\x1b\n" +
	"\tstat_vars\x18\x02 \x03(\tR\bstatVars\"\xb9\x01\n" +
	"\x12GetStatAllResponse\x12M\n" +
	"\n" +
	"place_data\x18\x01 \x03(\v2..datacommons.GetStatAllResponse.PlaceDataEntryR\tplaceData\x1aT\n" +
	"\x0ePlaceDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.datacommons.PlaceStatR\x05value:\x028\x01\"\xd2\x01\n" +
	"\bStatDate\x12S\n" +
	"\x10date_place_count\x18\x01 \x03(\v2).datacommons.StatDate.DatePlaceCountEntryR\x0edatePlaceCount\x12.\n" +
	"\bmetadata\x18\x02 \x01(\v2\x12.datacommons.FacetR\bmetadata\x1aA\n" +
	"\x13DatePlaceCountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"B\n" +
	"\fStatDateList\x122\n" +
	"\tstat_date\x18\x01 \x03(\v2\x15.datacommons.StatDateR\bstatDateB0Z.github.com/datacommonsorg/mixer/internal/protob\x06proto3"

var (
	file_stat_proto_rawDescOnce sync.Once
	file_stat_proto_rawDescData []byte
)

func file_stat_proto_rawDescGZIP() []byte {
	file_stat_proto_rawDescOnce.Do(func() {
		file_stat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stat_proto_rawDesc), len(file_stat_proto_rawDesc)))
	})
	return file_stat_proto_rawDescData
}

var file_stat_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_stat_proto_goTypes = []any{
	(*Facet)(nil),                    // 0: datacommons.Facet
	(*Facets)(nil),                   // 1: datacommons.Facets
	(*PlaceVariableFacet)(nil),       // 2: datacommons.PlaceVariableFacet
	(*PlaceVariableFacets)(nil),      // 3: datacommons.PlaceVariableFacets
	(*PointStat)(nil),                // 4: datacommons.PointStat
	(*SourceSeries)(nil),             // 5: datacommons.SourceSeries
	(*Series)(nil),                   // 6: datacommons.Series
	(*ObsTimeSeries)(nil),            // 7: datacommons.ObsTimeSeries
	(*ObsCollection)(nil),            // 8: datacommons.ObsCollection
	(*ChartStore)(nil),               // 9: datacommons.ChartStore
	(*PlaceStat)(nil),                // 10: datacommons.PlaceStat
	(*StatVarSeries)(nil),            // 11: datacommons.StatVarSeries
	(*GetStatsRequest)(nil),          // 12: datacommons.GetStatsRequest
	(*GetStatsResponse)(nil),         // 13: datacommons.GetStatsResponse
	(*GetStatValueRequest)(nil),      // 14: datacommons.GetStatValueRequest
	(*GetStatValueResponse)(nil),     // 15: datacommons.GetStatValueResponse
	(*GetStatSeriesRequest)(nil),     // 16: datacommons.GetStatSeriesRequest
	(*GetStatSeriesResponse)(nil),    // 17: datacommons.GetStatSeriesResponse
	(*GetStatAllRequest)(nil),        // 18: datacommons.GetStatAllRequest
	(*GetStatAllResponse)(nil),       // 19: datacommons.GetStatAllResponse
	(*StatDate)(nil),                 // 20: datacommons.StatDate
	(*StatDateList)(nil),             // 21: datacommons.StatDateList
	nil,                              // 22: datacommons.PointStat.AttributesEntry
	nil,                              // 23: datacommons.SourceSeries.ValEntry
	nil,                              // 24: datacommons.SourceSeries.PlaceToLatestDateEntry
	nil,                              // 25: datacommons.Series.ValEntry
	(*ObsCollection_PlaceTypes)(nil), // 26: datacommons.ObsCollection.PlaceTypes
	nil,                              // 27: datacommons.ObsCollection.PlaceDcidToTypesEntry
	nil,                              // 28: datacommons.PlaceStat.StatVarDataEntry
	nil,                              // 29: datacommons.StatVarSeries.DataEntry
	nil,                              // 30: datacommons.GetStatSeriesResponse.SeriesEntry
	nil,                              // 31: datacommons.GetStatAllResponse.PlaceDataEntry
	nil,                              // 32: datacommons.StatDate.DatePlaceCountEntry
}
var file_stat_proto_depIdxs = []int32{
	0,  // 0: datacommons.Facets.facets:type_name -> datacommons.Facet
	0,  // 1: datacommons.PlaceVariableFacet.facet:type_name -> datacommons.Facet
	2,  // 2: datacommons.PlaceVariableFacets.place_variable_facets:type_name -> datacommons.PlaceVariableFacet
	0,  // 3: datacommons.PointStat.metadata:type_name -> datacommons.Facet
	22, // 4: datacommons.PointStat.attributes:type_name -> datacommons.PointStat.AttributesEntry
	23, // 5: datacommons.SourceSeries.val:type_name -> datacommons.SourceSeries.ValEntry
	24, // 6: datacommons.SourceSeries.place_to_latest_date:type_name -> datacommons.SourceSeries.PlaceToLatestDateEntry
	25, // 7: datacommons.Series.val:type_name -> datacommons.Series.ValEntry
	0,  // 8: datacommons.Series.metadata:type_name -> datacommons.Facet
	5,  // 9: datacommons.ObsTimeSeries.source_series:type_name -> datacommons.SourceSeries
	5,  // 10: datacommons.ObsCollection.source_cohorts:type_name -> datacommons.SourceSeries
	27, // 11: datacommons.ObsCollection.place_dcid_to_types:type_name -> datacommons.ObsCollection.PlaceDcidToTypesEntry
	7,  // 12: datacommons.ChartStore.obs_time_series:type_name -> datacommons.ObsTimeSeries
	8,  // 13: datacommons.ChartStore.obs_collection:type_name -> datacommons.ObsCollection
	28, // 14: datacommons.PlaceStat.stat_var_data:type_name -> datacommons.PlaceStat.StatVarDataEntry
	29, // 15: datacommons.StatVarSeries.data:type_name -> datacommons.StatVarSeries.DataEntry
	30, // 16: datacommons.GetStatSeriesResponse.series:type_name -> datacommons.GetStatSeriesResponse.SeriesEntry
	31, // 17: datacommons.GetStatAllResponse.place_data:type_name -> datacommons.GetStatAllResponse.PlaceDataEntry
	32, // 18: datacommons.StatDate.date_place_count:type_name -> datacommons.StatDate.DatePlaceCountEntry
	0,  // 19: datacommons.StatDate.metadata:type_name -> datacommons.Facet
	20, // 20: datacommons.StatDateList.stat_date:type_name -> datacommons.StatDate
	26, // 21: datacommons.ObsCollection.PlaceDcidToTypesEntry.value:type_name -> datacommons.ObsCollection.PlaceTypes
	7,  // 22: datacommons.PlaceStat.StatVarDataEntry.value:type_name -> datacommons.ObsTimeSeries
	6,  // 23: datacommons.StatVarSeries.DataEntry.value:type_name -> datacommons.Series
	10, // 24: datacommons.GetStatAllResponse.PlaceDataEntry.value:type_name -> datacommons.PlaceStat
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_stat_proto_init() }
func file_stat_proto_init() {
	if File_stat_proto != nil {
		return
	}
	file_stat_proto_msgTypes[4].OneofWrappers = []any{}
	file_stat_proto_msgTypes[9].OneofWrappers = []any{
		(*ChartStore_ObsTimeSeries)(nil),
		(*ChartStore_ObsCollection)(nil),
	}
	file_stat_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stat_proto_rawDesc), len(file_stat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stat_proto_goTypes,
		DependencyIndexes: file_stat_proto_depIdxs,
		MessageInfos:      file_stat_proto_msgTypes,
	}.Build()
	File_stat_proto = out.File
	file_stat_proto_goTypes = nil
	file_stat_proto_depIdxs = nil
}
