project_id: datcom-apigee-dev
proxies:
  - name: api
    policies:
      - add-cors
      - copy-key-param-to-header
      - verify-api-key-in-header
      - rewrite-missing-key-message
      - rewrite-missing-allow-header-error
      - enforce-quota-limit
      - rewrite-quota-exceeded-message
      - set-southbound-key
      - strip-api-key-header-and-params
      - block-internal-only-endpoints
      - block-deprecated-endpoints
      - set-content-type-to-json
      - extract-json-params
    proxy_endpoints:
      - api
    target_endpoints:
      - api
  - name: nl
    policies:
      - copy-key-param-to-header
      - verify-api-key-in-header
      - strip-api-key-header-and-params
    proxy_endpoints:
      - nl
    target_endpoints:
      - nl
  - name: oauth
    policies:
      - add-cors
      - set-southbound-key
      - rewrite-quota-exceeded-message
      - oauth-set-config
      - oauth-script
      - oauth-verify-client-id
      - oauth-generate-state2-code
      - oauth-get-state2-attributes
      - oauth-delete-state2-code
      - oauth-call-google-token
      - oauth-verify-google-id-token
      - oauth-compute-uid
      - oauth-generate-auth-code
      - oauth-decode-basic-auth
      - oauth-verify-client-form
      - oauth-get-code-attributes
      - oauth-generate-access-token
      - oauth-refresh-access-token
      - oauth-verify-access-token
      - oauth-enforce-user-quota
      - oauth-strip-auth-headers
      - oauth-raise-error
      - oauth-rewrite-error
      - oauth-rewrite-unauthorized-mcp
    jsc:
      - oauth
    proxy_endpoints:
      - oauth
    target_endpoints:
      - oauth
