project_id: datcom-apigee
proxies:
  - name: api
    policies:
      - copy-key-param-to-header
      - verify-api-key-in-header
      - rewrite-missing-key-message
      - rewrite-missing-allow-header-error
      - enforce-quota-limit
      - enforce-quota-limit-v2
      - set-quota-tier
      - rewrite-quota-exceeded-message
      - set-southbound-key
      - strip-api-key-header-and-params
      - block-internal-only-endpoints
    proxy_endpoints:
      - api
    target_endpoints:
      - api
    resources:
      - jsc/set-quota-tier.js
  - name: bard
    policies:
      - forward-host
      - verify-api-key-in-param
    proxy_endpoints:
      - bard
    target_endpoints:
      - bard
  - name: nl
    policies:
      - copy-key-param-to-header
      - verify-api-key-in-header
      - strip-api-key-header-and-params
    proxy_endpoints:
      - nl
    target_endpoints:
      - nl