# Flags for mixer bundled with website autopush
clusters:
  - projects/datcom-website-autopush/locations/us-central1/clusters/website-us-central1
liveUrl: https://autopush.datacommons.org
flags:
  V3MirrorFraction: 1.0
  WriteUsageLogs: 1.0
  UseSpannerGraph: true
  SpannerGraphDatabase: projects/datcom-store/instances/dc-graph-prod/databases/dc_graph
  EnableSpannerSearchEmbeddings: true
  UseMultiEntitySchema: true
  EnableSDMXDataApi: true
  UseSpannerKeyValueStore: true
