# Flags for mixer bundled with website autopush
clusters:
  - projects/datcom-website-autopush/locations/us-central1/clusters/website-us-central1
liveUrl: https://autopush.datacommons.org
flags:
  WriteUsageLogs: 1.0
