# This should only be used for DCP, do not use it for CDC
flags:
  UseSpannerGraph: true
  UseStaleReads: true
  V2DivertFraction: 1.0
  EnableEmbeddingsResolver: false
  EnableSpannerSearchEmbeddings: true
