# This is read in for DCP deployments when resolve via spanner is enabled. It is not used for CDC.
flags:
  UseMultiEntitySchema: true
  EnableSDMXDataApi: true
  EnableEmbeddingsResolver: false
  EnableSpannerSearchEmbeddings: true
