# Default feature flag configuration for Data Commons Platform (DCP) Spanner deployments.
# NOTE: These defaults can be dynamically overridden by container environment variables configured in Terraform and applied via datacommonsorg/website:build/cdc_services/update_dcp_flags.py during container startup. 
flags:
  UseSpannerGraph: true
  UseMultiEntitySchema: true
  EnableSDMXDataApi: true
  EnableEmbeddingsResolver: false
  EnableSpannerSearchEmbeddings: true
  UseNewIngestionHistorySchema: false
  UseSpannerKeyValueStore: false
