clusters:
  - projects/datcom-mixer/locations/us-central1/clusters/mixer-us-central1
liveUrl: https://api.datacommons.org
flags:
  V3MirrorFraction: 0.1
  SpannerGraphDatabase: projects/datcom-store/instances/dc-graph-prod/databases/dc_graph
  WriteUsageLogs: 1.0
  UseSpannerGraph: true
  UseMultiEntitySchema: true
  EnableSDMXDataApi: true
  UseSpannerKeyValueStore: true
  UseNewIngestionHistorySchema: true
