// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: service/http_proxy.proto

package service

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_http_proxy_proto protoreflect.FileDescriptor

const file_service_http_proxy_proto_rawDesc = "" +
	"\n" +
	"\x18service/http_proxy.proto\x12\vdatacommons\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/api/httpbody.proto2y\n" +
	"\x10HttpProxyService\x12e\n" +
	"\tHttpProxy\x12\x14.google.api.HttpBody\x1a\x14.google.api.HttpBody\",\x82\xd3\xe4\x93\x02&Z\t:\x01*\"\x04/mcpZ\a\x12\x05/mcp2Z\n" +
	":\x01*\"\x05/mcp2\x12\x04/mcpB8Z6github.com/datacommonsorg/mixer/internal/proto/serviceb\x06proto3"

var file_service_http_proxy_proto_goTypes = []any{
	(*httpbody.HttpBody)(nil), // 0: google.api.HttpBody
}
var file_service_http_proxy_proto_depIdxs = []int32{
	0, // 0: datacommons.HttpProxyService.HttpProxy:input_type -> google.api.HttpBody
	0, // 1: datacommons.HttpProxyService.HttpProxy:output_type -> google.api.HttpBody
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_http_proxy_proto_init() }
func file_service_http_proxy_proto_init() {
	if File_service_http_proxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_http_proxy_proto_rawDesc), len(file_service_http_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_http_proxy_proto_goTypes,
		DependencyIndexes: file_service_http_proxy_proto_depIdxs,
	}.Build()
	File_service_http_proxy_proto = out.File
	file_service_http_proxy_proto_goTypes = nil
	file_service_http_proxy_proto_depIdxs = nil
}
