// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: service/http_proxy.proto

package service

import (
	context "context"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HttpProxyService_HttpProxy_FullMethodName = "/datacommons.HttpProxyService/HttpProxy"
)

// HttpProxyServiceClient is the client API for HttpProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HttpProxyServiceClient interface {
	// Generic RPC to proxy HTTP requests to external backends.
	HttpProxy(ctx context.Context, in *httpbody.HttpBody, opts ...grpc.CallOption) (*httpbody.HttpBody, error)
}

type httpProxyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHttpProxyServiceClient(cc grpc.ClientConnInterface) HttpProxyServiceClient {
	return &httpProxyServiceClient{cc}
}

func (c *httpProxyServiceClient) HttpProxy(ctx context.Context, in *httpbody.HttpBody, opts ...grpc.CallOption) (*httpbody.HttpBody, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(httpbody.HttpBody)
	err := c.cc.Invoke(ctx, HttpProxyService_HttpProxy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HttpProxyServiceServer is the server API for HttpProxyService service.
// All implementations should embed UnimplementedHttpProxyServiceServer
// for forward compatibility.
type HttpProxyServiceServer interface {
	// Generic RPC to proxy HTTP requests to external backends.
	HttpProxy(context.Context, *httpbody.HttpBody) (*httpbody.HttpBody, error)
}

// UnimplementedHttpProxyServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHttpProxyServiceServer struct{}

func (UnimplementedHttpProxyServiceServer) HttpProxy(context.Context, *httpbody.HttpBody) (*httpbody.HttpBody, error) {
	return nil, status.Error(codes.Unimplemented, "method HttpProxy not implemented")
}
func (UnimplementedHttpProxyServiceServer) testEmbeddedByValue() {}

// UnsafeHttpProxyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HttpProxyServiceServer will
// result in compilation errors.
type UnsafeHttpProxyServiceServer interface {
	mustEmbedUnimplementedHttpProxyServiceServer()
}

func RegisterHttpProxyServiceServer(s grpc.ServiceRegistrar, srv HttpProxyServiceServer) {
	// If the following call panics, it indicates UnimplementedHttpProxyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HttpProxyService_ServiceDesc, srv)
}

func _HttpProxyService_HttpProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(httpbody.HttpBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpProxyServiceServer).HttpProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpProxyService_HttpProxy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpProxyServiceServer).HttpProxy(ctx, req.(*httpbody.HttpBody))
	}
	return interceptor(ctx, in, info, handler)
}

// HttpProxyService_ServiceDesc is the grpc.ServiceDesc for HttpProxyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HttpProxyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datacommons.HttpProxyService",
	HandlerType: (*HttpProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HttpProxy",
			Handler:    _HttpProxyService_HttpProxy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/http_proxy.proto",
}
