// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//  **** IMPORTANT NOTE ****
//
//  The proto of BT data has to match exactly the g3 proto, including tag
//  number.

// Mixer service definitions

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: service/mixer.proto

package service

import (
	reflect "reflect"
	unsafe "unsafe"

	proto "github.com/datacommonsorg/mixer/internal/proto"
	v1 "github.com/datacommonsorg/mixer/internal/proto/v1"
	v2 "github.com/datacommonsorg/mixer/internal/proto/v2"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_mixer_proto protoreflect.FileDescriptor

const file_service_mixer_proto_rawDesc = "" +
	"\n" +
	"\x13service/mixer.proto\x12\vdatacommons\x1a\x1cgoogle/api/annotations.proto\x1a\fcommon.proto\x1a\x0einternal.proto\x1a\n" +
	"misc.proto\x1a\n" +
	"node.proto\x1a\vplace.proto\x1a\vquery.proto\x1a\n" +
	"stat.proto\x1a\x0estat_var.proto\x1a\vrecon.proto\x1a\x0ev1/event.proto\x1a\x13v1/properties.proto\x1a\x18v1/property_values.proto\x1a\x11v1/variable.proto\x1a\rv1/info.proto\x1a\x15v1/observations.proto\x1a\x1av1/observation_dates.proto\x1a\x1ev1/observation_existence.proto\x1a\rv1/page.proto\x1a\x10v1/triples.proto\x1a\x0ev2/event.proto\x1a\rv2/node.proto\x1a\x14v2/node_search.proto\x1a\x14v2/observation.proto\x1a\x10v2/resolve.proto2\xc5P\n" +
	"\x05Mixer\x12d\n" +
	"\x06V3Node\x12\x1b.datacommons.v2.NodeRequest\x1a\x1c.datacommons.v2.NodeResponse\"\x1f\x82\xd3\xe4\x93\x02\x19Z\r:\x01*\"\b/v3/node\x12\b/v3/node\x12\x87\x01\n" +
	"\rV3Observation\x12\".datacommons.v2.ObservationRequest\x1a#.datacommons.v2.ObservationResponse\"-\x82\xd3\xe4\x93\x02'Z\x14:\x01*\"\x0f/v3/observation\x12\x0f/v3/observation\x12\x84\x01\n" +
	"\fV3NodeSearch\x12!.datacommons.v2.NodeSearchRequest\x1a\".datacommons.v2.NodeSearchResponse\"-\x82\xd3\xe4\x93\x02'Z\x14:\x01*\"\x0f/v3/node_search\x12\x0f/v3/node_search\x12s\n" +
	"\tV3Resolve\x12\x1e.datacommons.v2.ResolveRequest\x1a\x1f.datacommons.v2.ResolveResponse\"%\x82\xd3\xe4\x93\x02\x1fZ\x10:\x01*\"\v/v3/resolve\x12\v/v3/resolve\x12g\n" +
	"\bV2Sparql\x12\x1a.datacommons.SparqlRequest\x1a\x1a.datacommons.QueryResponse\"#\x82\xd3\xe4\x93\x02\x1dZ\x0f:\x01*\"\n" +
	"/v2/sparql\x12\n" +
	"/v2/sparql\x12s\n" +
	"\tV2Resolve\x12\x1e.datacommons.v2.ResolveRequest\x1a\x1f.datacommons.v2.ResolveResponse\"%\x82\xd3\xe4\x93\x02\x1fZ\x10:\x01*\"\v/v2/resolve\x12\v/v2/resolve\x12d\n" +
	"\x06V2Node\x12\x1b.datacommons.v2.NodeRequest\x1a\x1c.datacommons.v2.NodeResponse\"\x1f\x82\xd3\xe4\x93\x02\x19Z\r:\x01*\"\b/v2/node\x12\b/v2/node\x12i\n" +
	"\aV2Event\x12\x1c.datacommons.v2.EventRequest\x1a\x1d.datacommons.v2.EventResponse\"!\x82\xd3\xe4\x93\x02\x1bZ\x0e:\x01*\"\t/v2/event\x12\t/v2/event\x12\x87\x01\n" +
	"\rV2Observation\x12\".datacommons.v2.ObservationRequest\x1a#.datacommons.v2.ObservationResponse\"-\x82\xd3\xe4\x93\x02'Z\x14:\x01*\"\x0f/v2/observation\x12\x0f/v2/observation\x12\x91\x01\n" +
	"\x16FilterStatVarsByEntity\x12*.datacommons.FilterStatVarsByEntityRequest\x1a+.datacommons.FilterStatVarsByEntityResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v2/variable/filter\x12[\n" +
	"\x05Query\x12\x19.datacommons.QueryRequest\x1a\x1a.datacommons.QueryResponse\"\x1b\x82\xd3\xe4\x93\x02\x15Z\v:\x01*\"\x06/query\x12\x06/query\x12\x93\x01\n" +
	"\x11GetPropertyLabels\x12%.datacommons.GetPropertyLabelsRequest\x1a\x1c.datacommons.PayloadResponse\"9\x82\xd3\xe4\x93\x023Z\x1a:\x01*\"\x15/node/property-labels\x12\x15/node/property-labels\x12\x93\x01\n" +
	"\x11GetPropertyValues\x12%.datacommons.GetPropertyValuesRequest\x1a\x1c.datacommons.PayloadResponse\"9\x82\xd3\xe4\x93\x023Z\x1a:\x01*\"\x15/node/property-values\x12\x15/node/property-values\x12u\n" +
	"\n" +
	"GetTriples\x12\x1e.datacommons.GetTriplesRequest\x1a\x1c.datacommons.PayloadResponse\")\x82\xd3\xe4\x93\x02#Z\x12:\x01*\"\r/node/triples\x12\r/node/triples\x12\x7f\n" +
	"\vGetPlacesIn\x12\x1f.datacommons.GetPlacesInRequest\x1a .datacommons.GetPlacesInResponse\"-\x82\xd3\xe4\x93\x02'Z\x14:\x01*\"\x0f/node/places-in\x12\x0f/node/places-in\x12n\n" +
	"\bGetStats\x12\x1c.datacommons.GetStatsRequest\x1a\x1d.datacommons.GetStatsResponse\"%\x82\xd3\xe4\x93\x02\x1fZ\x10:\x01*\"\v/bulk/stats\x12\v/bulk/stats\x12z\n" +
	"\fGetStatValue\x12 .datacommons.GetStatValueRequest\x1a!.datacommons.GetStatValueResponse\"%\x82\xd3\xe4\x93\x02\x1fZ\x10:\x01*\"\v/stat/value\x12\v/stat/value\x12\x7f\n" +
	"\rGetStatSeries\x12!.datacommons.GetStatSeriesRequest\x1a\".datacommons.GetStatSeriesResponse\"'\x82\xd3\xe4\x93\x02!Z\x11:\x01*\"\f/stat/series\x12\f/stat/series\x12p\n" +
	"\n" +
	"GetStatAll\x12\x1e.datacommons.GetStatAllRequest\x1a\x1f.datacommons.GetStatAllResponse\"!\x82\xd3\xe4\x93\x02\x1bZ\x0e:\x01*\"\t/stat/all\x12\t/stat/all\x12\x9e\x01\n" +
	"\x14GetLocationsRankings\x12(.datacommons.GetLocationsRankingsRequest\x1a).datacommons.GetLocationsRankingsResponse\"1\x82\xd3\xe4\x93\x02+Z\x16:\x01*\"\x11/v1/place/ranking\x12\x11/v1/place/ranking\x12\x9b\x01\n" +
	"\x13GetRelatedLocations\x12'.datacommons.GetRelatedLocationsRequest\x1a(.datacommons.GetRelatedLocationsResponse\"1\x82\xd3\xe4\x93\x02+Z\x16:\x01*\"\x11/v1/place/related\x12\x11/v1/place/related\x12x\n" +
	"\x0eGetBioPageData\x12\".datacommons.GetBioPageDataRequest\x1a\x17.datacommons.GraphNodes\")\x82\xd3\xe4\x93\x02#Z\x12:\x01*\"\r/internal/bio\x12\r/internal/bio\x12R\n" +
	"\x06Search\x12\x1a.datacommons.SearchRequest\x1a\x1b.datacommons.SearchResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/search\x12_\n" +
	"\n" +
	"GetVersion\x12\x1e.datacommons.GetVersionRequest\x1a\x1f.datacommons.GetVersionResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/version\x12\x90\x01\n" +
	"\x10GetPlaceStatsVar\x12$.datacommons.GetPlaceStatsVarRequest\x1a%.datacommons.GetPlaceStatsVarResponse\"/\x82\xd3\xe4\x93\x02)Z\x15:\x01*\"\x10/place/stats-var\x12\x10/place/stats-var\x12\x90\x01\n" +
	"\x10GetPlaceStatVars\x12$.datacommons.GetPlaceStatVarsRequest\x1a%.datacommons.GetPlaceStatVarsResponse\"/\x82\xd3\xe4\x93\x02)Z\x15:\x01*\"\x10/place/stat-vars\x12\x10/place/stat-vars\x12\xb6\x01\n" +
	"\x18GetEntityStatVarsUnionV1\x12*.datacommons.GetEntityStatVarsUnionRequest\x1a+.datacommons.GetEntityStatVarsUnionResponse\"A\x82\xd3\xe4\x93\x02;Z\x1e:\x01*\"\x19/v1/place/stat-vars/union\x12\x19/v1/place/stat-vars/union\x12\xcb\x01\n" +
	"\x1bGetPlaceStatDateWithinPlace\x12/.datacommons.GetPlaceStatDateWithinPlaceRequest\x1a0.datacommons.GetPlaceStatDateWithinPlaceResponse\"I\x82\xd3\xe4\x93\x02CZ\":\x01*\"\x1d/place/stat/date/within-place\x12\x1d/place/stat/date/within-place\x12\xb6\x01\n" +
	"\x16GetStatDateWithinPlace\x12*.datacommons.GetStatDateWithinPlaceRequest\x1a+.datacommons.GetStatDateWithinPlaceResponse\"C\x82\xd3\xe4\x93\x02=Z\x1f:\x01*\"\x1a/v1/stat/date/within-place\x12\x1a/v1/stat/date/within-place\x12\xa2\x01\n" +
	"\x12GetImportTableData\x12&.datacommons.GetImportTableDataRequest\x1a'.datacommons.GetImportTableDataResponse\";\x82\xd3\xe4\x93\x025Z\x1b:\x01*\"\x16/internal/import-table\x12\x16/internal/import-table\x12c\n" +
	"\aQueryV1\x12\x19.datacommons.QueryRequest\x1a\x1a.datacommons.QueryResponse\"!\x82\xd3\xe4\x93\x02\x1bZ\x0e:\x01*\"\t/v1/query\x12\t/v1/query\x12\x81\x01\n" +
	"\n" +
	"Properties\x12!.datacommons.v1.PropertiesRequest\x1a\".datacommons.v1.PropertiesResponse\",\x82\xd3\xe4\x93\x02&\x12$/v1/properties/{direction}/{node=**}\x12\xae\x01\n" +
	"\x0eBulkProperties\x12%.datacommons.v1.BulkPropertiesRequest\x1a&.datacommons.v1.BulkPropertiesResponse\"M\x82\xd3\xe4\x93\x02GZ$:\x01*\"\x1f/v1/bulk/properties/{direction}\x12\x1f/v1/bulk/properties/{direction}\x12\x9b\x01\n" +
	"\x0ePropertyValues\x12%.datacommons.v1.PropertyValuesRequest\x1a&.datacommons.v1.PropertyValuesResponse\":\x82\xd3\xe4\x93\x024\x122/v1/property/values/{direction}/{node_property=**}\x12\xa5\x01\n" +
	"\x14LinkedPropertyValues\x12+.datacommons.v1.LinkedPropertyValuesRequest\x1a&.datacommons.v1.PropertyValuesResponse\"8\x82\xd3\xe4\x93\x022\x120/v1/property/values/in/linked/{node_property=**}\x12\xc4\x01\n" +
	"\x12BulkPropertyValues\x12).datacommons.v1.BulkPropertyValuesRequest\x1a*.datacommons.v1.BulkPropertyValuesResponse\"W\x82\xd3\xe4\x93\x02QZ):\x01*\"$/v1/bulk/property/values/{direction}\x12$/v1/bulk/property/values/{direction}\x12\xcc\x01\n" +
	"\x18BulkLinkedPropertyValues\x12/.datacommons.v1.BulkLinkedPropertyValuesRequest\x1a*.datacommons.v1.BulkPropertyValuesResponse\"S\x82\xd3\xe4\x93\x02MZ':\x01*\"\"/v1/bulk/property/values/in/linked\x12\"/v1/bulk/property/values/in/linked\x12u\n" +
	"\aTriples\x12\x1e.datacommons.v1.TriplesRequest\x1a\x1f.datacommons.v1.TriplesResponse\")\x82\xd3\xe4\x93\x02#\x12!/v1/triples/{direction}/{node=**}\x12\x9f\x01\n" +
	"\vBulkTriples\x12\".datacommons.v1.BulkTriplesRequest\x1a#.datacommons.v1.BulkTriplesResponse\"G\x82\xd3\xe4\x93\x02AZ!:\x01*\"\x1c/v1/bulk/triples/{direction}\x12\x1c/v1/bulk/triples/{direction}\x12s\n" +
	"\tVariables\x12 .datacommons.v1.VariablesRequest\x1a!.datacommons.v1.VariablesResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/variables/{entity=**}\x12\x91\x01\n" +
	"\rBulkVariables\x12$.datacommons.v1.BulkVariablesRequest\x1a%.datacommons.v1.BulkVariablesResponse\"3\x82\xd3\xe4\x93\x02-Z\x17:\x01*\"\x12/v1/bulk/variables\x12\x12/v1/bulk/variables\x12r\n" +
	"\tPlaceInfo\x12 .datacommons.v1.PlaceInfoRequest\x1a!.datacommons.v1.PlaceInfoResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/info/place/{node=**}\x12\x93\x01\n" +
	"\rBulkPlaceInfo\x12$.datacommons.v1.BulkPlaceInfoRequest\x1a%.datacommons.v1.BulkPlaceInfoResponse\"5\x82\xd3\xe4\x93\x02/Z\x18:\x01*\"\x13/v1/bulk/info/place\x12\x13/v1/bulk/info/place\x12~\n" +
	"\fVariableInfo\x12#.datacommons.v1.VariableInfoRequest\x1a$.datacommons.v1.VariableInfoResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/info/variable/{node=**}\x12\xa2\x01\n" +
	"\x10BulkVariableInfo\x12'.datacommons.v1.BulkVariableInfoRequest\x1a(.datacommons.v1.BulkVariableInfoResponse\";\x82\xd3\xe4\x93\x025Z\x1b:\x01*\"\x16/v1/bulk/info/variable\x12\x16/v1/bulk/info/variable\x12\x93\x01\n" +
	"\x11VariableGroupInfo\x12(.datacommons.v1.VariableGroupInfoRequest\x1a).datacommons.v1.VariableGroupInfoResponse\")\x82\xd3\xe4\x93\x02#\x12!/v1/info/variable-group/{node=**}\x12\xbd\x01\n" +
	"\x15BulkVariableGroupInfo\x12,.datacommons.v1.BulkVariableGroupInfoRequest\x1a-.datacommons.v1.BulkVariableGroupInfoResponse\"G\x82\xd3\xe4\x93\x02AZ!:\x01*\"\x1c/v1/bulk/info/variable-group\x12\x1c/v1/bulk/info/variable-group\x12\x8a\x01\n" +
	"\x11ObservationsPoint\x12(.datacommons.v1.ObservationsPointRequest\x1a\x16.datacommons.PointStat\"3\x82\xd3\xe4\x93\x02-\x12+/v1/observations/point/{entity_variable=**}\x12\xbb\x01\n" +
	"\x15BulkObservationsPoint\x12,.datacommons.v1.BulkObservationsPointRequest\x1a-.datacommons.v1.BulkObservationsPointResponse\"E\x82\xd3\xe4\x93\x02?Z :\x01*\"\x1b/v1/bulk/observations/point\x12\x1b/v1/bulk/observations/point\x12\xd5\x01\n" +
	"\x1bBulkObservationsPointLinked\x122.datacommons.v1.BulkObservationsPointLinkedRequest\x1a-.datacommons.v1.BulkObservationsPointResponse\"S\x82\xd3\xe4\x93\x02MZ':\x01*\"\"/v1/bulk/observations/point/linked\x12\"/v1/bulk/observations/point/linked\x12\xa1\x01\n" +
	"\x12ObservationsSeries\x12).datacommons.v1.ObservationsSeriesRequest\x1a*.datacommons.v1.ObservationsSeriesResponse\"4\x82\xd3\xe4\x93\x02.\x12,/v1/observations/series/{entity_variable=**}\x12\xc0\x01\n" +
	"\x16BulkObservationsSeries\x12-.datacommons.v1.BulkObservationsSeriesRequest\x1a..datacommons.v1.BulkObservationsSeriesResponse\"G\x82\xd3\xe4\x93\x02AZ!:\x01*\"\x1c/v1/bulk/observations/series\x12\x1c/v1/bulk/observations/series\x12\xda\x01\n" +
	"\x1cBulkObservationsSeriesLinked\x123.datacommons.v1.BulkObservationsSeriesLinkedRequest\x1a..datacommons.v1.BulkObservationsSeriesResponse\"U\x82\xd3\xe4\x93\x02OZ(:\x01*\"#/v1/bulk/observations/series/linked\x12#/v1/bulk/observations/series/linked\x12\xcf\x01\n" +
	"\x19DerivedObservationsSeries\x120.datacommons.v1.DerivedObservationsSeriesRequest\x1a1.datacommons.v1.DerivedObservationsSeriesResponse\"M\x82\xd3\xe4\x93\x02GZ$:\x01*\"\x1f/v1/observations/series/derived\x12\x1f/v1/observations/series/derived\x12\xd6\x01\n" +
	"\x1aBulkObservationDatesLinked\x121.datacommons.v1.BulkObservationDatesLinkedRequest\x1a2.datacommons.v1.BulkObservationDatesLinkedResponse\"Q\x82\xd3\xe4\x93\x02KZ&:\x01*\"!/v1/bulk/observation-dates/linked\x12!/v1/bulk/observation-dates/linked\x12\xca\x01\n" +
	"\x18BulkObservationExistence\x12/.datacommons.v1.BulkObservationExistenceRequest\x1a0.datacommons.v1.BulkObservationExistenceResponse\"K\x82\xd3\xe4\x93\x02EZ#:\x01*\"\x1e/v1/bulk/observation-existence\x12\x1e/v1/bulk/observation-existence\x12k\n" +
	"\aBioPage\x12\x1e.datacommons.v1.BioPageRequest\x1a\x17.datacommons.GraphNodes\"'\x82\xd3\xe4\x93\x02!\x12\x1f/v1/internal/page/bio/{node=**}\x12\x99\x01\n" +
	"\tPlacePage\x12 .datacommons.v1.PlacePageRequest\x1a!.datacommons.v1.PlacePageResponse\"G\x82\xd3\xe4\x93\x02AZ\x1c:\x01*\"\x17/v1/internal/page/place\x12!/v1/internal/page/place/{node=**}\x12\xaf\x01\n" +
	"\x11VariableAncestors\x12(.datacommons.v1.VariableAncestorsRequest\x1a).datacommons.v1.VariableAncestorsResponse\"E\x82\xd3\xe4\x93\x02?Z\x1b:\x01*\"\x16/v1/variable/ancestors\x12 /v1/variable/ancestors/{node=**}\x12\x8d\x01\n" +
	"\rSearchStatVar\x12!.datacommons.SearchStatVarRequest\x1a\".datacommons.SearchStatVarResponse\"5\x82\xd3\xe4\x93\x02/Z\x18:\x01*\"\x13/v1/variable/search\x12\x13/v1/variable/search\x12\x87\x01\n" +
	"\x0fEventCollection\x12&.datacommons.v1.EventCollectionRequest\x1a'.datacommons.v1.EventCollectionResponse\"#\x82\xd3\xe4\x93\x02\x1dZ\x0f:\x01*\"\n" +
	"/v1/events\x12\n" +
	"/v1/events\x12\x9f\x01\n" +
	"\x13EventCollectionDate\x12*.datacommons.v1.EventCollectionDateRequest\x1a+.datacommons.v1.EventCollectionDateResponse\"/\x82\xd3\xe4\x93\x02)Z\x15:\x01*\"\x10/v1/events/dates\x12\x10/v1/events/dates\x12\x81\x01\n" +
	"\x0fResolveEntities\x12#.datacommons.ResolveEntitiesRequest\x1a$.datacommons.ResolveEntitiesResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/recon/entity/resolve\x12\x8e\x01\n" +
	"\x12ResolveCoordinates\x12&.datacommons.ResolveCoordinatesRequest\x1a'.datacommons.ResolveCoordinatesResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/recon/resolve/coordinate\x12n\n" +
	"\n" +
	"ResolveIds\x12\x1e.datacommons.ResolveIdsRequest\x1a\x1f.datacommons.ResolveIdsResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/recon/resolve/id\x12\x86\x01\n" +
	"\fFindEntities\x12 .datacommons.FindEntitiesRequest\x1a!.datacommons.FindEntitiesResponse\"1\x82\xd3\xe4\x93\x02+Z\x16:\x01*\"\x11/v1/find/entities\x12\x11/v1/find/entities\x12\x82\x01\n" +
	"\x10BulkFindEntities\x12$.datacommons.BulkFindEntitiesRequest\x1a%.datacommons.BulkFindEntitiesResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/bulk/find/entities\x12\x95\x01\n" +
	"\x0fRecognizePlaces\x12#.datacommons.RecognizePlacesRequest\x1a$.datacommons.RecognizePlacesResponse\"7\x82\xd3\xe4\x93\x021Z\x19:\x01*\"\x14/v1/recognize/places\x12\x14/v1/recognize/places\x12\x9f\x01\n" +
	"\x11RecognizeEntities\x12%.datacommons.RecognizeEntitiesRequest\x1a&.datacommons.RecognizeEntitiesResponse\";\x82\xd3\xe4\x93\x025Z\x1b:\x01*\"\x16/v1/recognize/entities\x12\x16/v1/recognize/entities\x12j\n" +
	"\vUpdateCache\x12\x1f.datacommons.UpdateCacheRequest\x1a .datacommons.UpdateCacheResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/update-cacheB8Z6github.com/datacommonsorg/mixer/internal/proto/serviceb\x06proto3"

var file_service_mixer_proto_goTypes = []any{
	(*v2.NodeRequest)(nil),                            // 0: datacommons.v2.NodeRequest
	(*v2.ObservationRequest)(nil),                     // 1: datacommons.v2.ObservationRequest
	(*v2.NodeSearchRequest)(nil),                      // 2: datacommons.v2.NodeSearchRequest
	(*v2.ResolveRequest)(nil),                         // 3: datacommons.v2.ResolveRequest
	(*proto.SparqlRequest)(nil),                       // 4: datacommons.SparqlRequest
	(*v2.EventRequest)(nil),                           // 5: datacommons.v2.EventRequest
	(*proto.FilterStatVarsByEntityRequest)(nil),       // 6: datacommons.FilterStatVarsByEntityRequest
	(*proto.QueryRequest)(nil),                        // 7: datacommons.QueryRequest
	(*proto.GetPropertyLabelsRequest)(nil),            // 8: datacommons.GetPropertyLabelsRequest
	(*proto.GetPropertyValuesRequest)(nil),            // 9: datacommons.GetPropertyValuesRequest
	(*proto.GetTriplesRequest)(nil),                   // 10: datacommons.GetTriplesRequest
	(*proto.GetPlacesInRequest)(nil),                  // 11: datacommons.GetPlacesInRequest
	(*proto.GetStatsRequest)(nil),                     // 12: datacommons.GetStatsRequest
	(*proto.GetStatValueRequest)(nil),                 // 13: datacommons.GetStatValueRequest
	(*proto.GetStatSeriesRequest)(nil),                // 14: datacommons.GetStatSeriesRequest
	(*proto.GetStatAllRequest)(nil),                   // 15: datacommons.GetStatAllRequest
	(*proto.GetLocationsRankingsRequest)(nil),         // 16: datacommons.GetLocationsRankingsRequest
	(*proto.GetRelatedLocationsRequest)(nil),          // 17: datacommons.GetRelatedLocationsRequest
	(*proto.SearchRequest)(nil),                       // 18: datacommons.SearchRequest
	(*proto.GetVersionRequest)(nil),                   // 19: datacommons.GetVersionRequest
	(*proto.GetPlaceStatsVarRequest)(nil),             // 20: datacommons.GetPlaceStatsVarRequest
	(*proto.GetPlaceStatVarsRequest)(nil),             // 21: datacommons.GetPlaceStatVarsRequest
	(*proto.GetEntityStatVarsUnionRequest)(nil),       // 22: datacommons.GetEntityStatVarsUnionRequest
	(*proto.GetPlaceStatDateWithinPlaceRequest)(nil),  // 23: datacommons.GetPlaceStatDateWithinPlaceRequest
	(*proto.GetStatDateWithinPlaceRequest)(nil),       // 24: datacommons.GetStatDateWithinPlaceRequest
	(*proto.GetImportTableDataRequest)(nil),           // 25: datacommons.GetImportTableDataRequest
	(*v1.PropertiesRequest)(nil),                      // 26: datacommons.v1.PropertiesRequest
	(*v1.BulkPropertiesRequest)(nil),                  // 27: datacommons.v1.BulkPropertiesRequest
	(*v1.PropertyValuesRequest)(nil),                  // 28: datacommons.v1.PropertyValuesRequest
	(*v1.LinkedPropertyValuesRequest)(nil),            // 29: datacommons.v1.LinkedPropertyValuesRequest
	(*v1.BulkPropertyValuesRequest)(nil),              // 30: datacommons.v1.BulkPropertyValuesRequest
	(*v1.BulkLinkedPropertyValuesRequest)(nil),        // 31: datacommons.v1.BulkLinkedPropertyValuesRequest
	(*v1.TriplesRequest)(nil),                         // 32: datacommons.v1.TriplesRequest
	(*v1.BulkTriplesRequest)(nil),                     // 33: datacommons.v1.BulkTriplesRequest
	(*v1.VariablesRequest)(nil),                       // 34: datacommons.v1.VariablesRequest
	(*v1.BulkVariablesRequest)(nil),                   // 35: datacommons.v1.BulkVariablesRequest
	(*v1.PlaceInfoRequest)(nil),                       // 36: datacommons.v1.PlaceInfoRequest
	(*v1.BulkPlaceInfoRequest)(nil),                   // 37: datacommons.v1.BulkPlaceInfoRequest
	(*v1.VariableInfoRequest)(nil),                    // 38: datacommons.v1.VariableInfoRequest
	(*v1.BulkVariableInfoRequest)(nil),                // 39: datacommons.v1.BulkVariableInfoRequest
	(*v1.VariableGroupInfoRequest)(nil),               // 40: datacommons.v1.VariableGroupInfoRequest
	(*v1.BulkVariableGroupInfoRequest)(nil),           // 41: datacommons.v1.BulkVariableGroupInfoRequest
	(*v1.ObservationsPointRequest)(nil),               // 42: datacommons.v1.ObservationsPointRequest
	(*v1.BulkObservationsPointRequest)(nil),           // 43: datacommons.v1.BulkObservationsPointRequest
	(*v1.BulkObservationsPointLinkedRequest)(nil),     // 44: datacommons.v1.BulkObservationsPointLinkedRequest
	(*v1.ObservationsSeriesRequest)(nil),              // 45: datacommons.v1.ObservationsSeriesRequest
	(*v1.BulkObservationsSeriesRequest)(nil),          // 46: datacommons.v1.BulkObservationsSeriesRequest
	(*v1.BulkObservationsSeriesLinkedRequest)(nil),    // 47: datacommons.v1.BulkObservationsSeriesLinkedRequest
	(*v1.DerivedObservationsSeriesRequest)(nil),       // 48: datacommons.v1.DerivedObservationsSeriesRequest
	(*v1.BulkObservationDatesLinkedRequest)(nil),      // 49: datacommons.v1.BulkObservationDatesLinkedRequest
	(*v1.BulkObservationExistenceRequest)(nil),        // 50: datacommons.v1.BulkObservationExistenceRequest
	(*v1.BioPageRequest)(nil),                         // 51: datacommons.v1.BioPageRequest
	(*v1.PlacePageRequest)(nil),                       // 52: datacommons.v1.PlacePageRequest
	(*v1.VariableAncestorsRequest)(nil),               // 53: datacommons.v1.VariableAncestorsRequest
	(*proto.SearchStatVarRequest)(nil),                // 54: datacommons.SearchStatVarRequest
	(*v1.EventCollectionRequest)(nil),                 // 55: datacommons.v1.EventCollectionRequest
	(*v1.EventCollectionDateRequest)(nil),             // 56: datacommons.v1.EventCollectionDateRequest
	(*proto.ResolveEntitiesRequest)(nil),              // 57: datacommons.ResolveEntitiesRequest
	(*proto.ResolveCoordinatesRequest)(nil),           // 58: datacommons.ResolveCoordinatesRequest
	(*proto.ResolveIdsRequest)(nil),                   // 59: datacommons.ResolveIdsRequest
	(*proto.FindEntitiesRequest)(nil),                 // 60: datacommons.FindEntitiesRequest
	(*proto.BulkFindEntitiesRequest)(nil),             // 61: datacommons.BulkFindEntitiesRequest
	(*proto.RecognizePlacesRequest)(nil),              // 62: datacommons.RecognizePlacesRequest
	(*proto.RecognizeEntitiesRequest)(nil),            // 63: datacommons.RecognizeEntitiesRequest
	(*proto.UpdateCacheRequest)(nil),                  // 64: datacommons.UpdateCacheRequest
	(*v2.NodeResponse)(nil),                           // 65: datacommons.v2.NodeResponse
	(*v2.ObservationResponse)(nil),                    // 66: datacommons.v2.ObservationResponse
	(*v2.NodeSearchResponse)(nil),                     // 67: datacommons.v2.NodeSearchResponse
	(*v2.ResolveResponse)(nil),                        // 68: datacommons.v2.ResolveResponse
	(*proto.QueryResponse)(nil),                       // 69: datacommons.QueryResponse
	(*v2.EventResponse)(nil),                          // 70: datacommons.v2.EventResponse
	(*proto.FilterStatVarsByEntityResponse)(nil),      // 71: datacommons.FilterStatVarsByEntityResponse
	(*proto.PayloadResponse)(nil),                     // 72: datacommons.PayloadResponse
	(*proto.GetPlacesInResponse)(nil),                 // 73: datacommons.GetPlacesInResponse
	(*proto.GetStatsResponse)(nil),                    // 74: datacommons.GetStatsResponse
	(*proto.GetStatValueResponse)(nil),                // 75: datacommons.GetStatValueResponse
	(*proto.GetStatSeriesResponse)(nil),               // 76: datacommons.GetStatSeriesResponse
	(*proto.GetStatAllResponse)(nil),                  // 77: datacommons.GetStatAllResponse
	(*proto.GetLocationsRankingsResponse)(nil),        // 78: datacommons.GetLocationsRankingsResponse
	(*proto.GetRelatedLocationsResponse)(nil),         // 79: datacommons.GetRelatedLocationsResponse
	(*proto.SearchResponse)(nil),                      // 80: datacommons.SearchResponse
	(*proto.GetVersionResponse)(nil),                  // 81: datacommons.GetVersionResponse
	(*proto.GetPlaceStatsVarResponse)(nil),            // 82: datacommons.GetPlaceStatsVarResponse
	(*proto.GetPlaceStatVarsResponse)(nil),            // 83: datacommons.GetPlaceStatVarsResponse
	(*proto.GetEntityStatVarsUnionResponse)(nil),      // 84: datacommons.GetEntityStatVarsUnionResponse
	(*proto.GetPlaceStatDateWithinPlaceResponse)(nil), // 85: datacommons.GetPlaceStatDateWithinPlaceResponse
	(*proto.GetStatDateWithinPlaceResponse)(nil),      // 86: datacommons.GetStatDateWithinPlaceResponse
	(*proto.GetImportTableDataResponse)(nil),          // 87: datacommons.GetImportTableDataResponse
	(*v1.PropertiesResponse)(nil),                     // 88: datacommons.v1.PropertiesResponse
	(*v1.BulkPropertiesResponse)(nil),                 // 89: datacommons.v1.BulkPropertiesResponse
	(*v1.PropertyValuesResponse)(nil),                 // 90: datacommons.v1.PropertyValuesResponse
	(*v1.BulkPropertyValuesResponse)(nil),             // 91: datacommons.v1.BulkPropertyValuesResponse
	(*v1.TriplesResponse)(nil),                        // 92: datacommons.v1.TriplesResponse
	(*v1.BulkTriplesResponse)(nil),                    // 93: datacommons.v1.BulkTriplesResponse
	(*v1.VariablesResponse)(nil),                      // 94: datacommons.v1.VariablesResponse
	(*v1.BulkVariablesResponse)(nil),                  // 95: datacommons.v1.BulkVariablesResponse
	(*v1.PlaceInfoResponse)(nil),                      // 96: datacommons.v1.PlaceInfoResponse
	(*v1.BulkPlaceInfoResponse)(nil),                  // 97: datacommons.v1.BulkPlaceInfoResponse
	(*v1.VariableInfoResponse)(nil),                   // 98: datacommons.v1.VariableInfoResponse
	(*v1.BulkVariableInfoResponse)(nil),               // 99: datacommons.v1.BulkVariableInfoResponse
	(*v1.VariableGroupInfoResponse)(nil),              // 100: datacommons.v1.VariableGroupInfoResponse
	(*v1.BulkVariableGroupInfoResponse)(nil),          // 101: datacommons.v1.BulkVariableGroupInfoResponse
	(*proto.PointStat)(nil),                           // 102: datacommons.PointStat
	(*v1.BulkObservationsPointResponse)(nil),          // 103: datacommons.v1.BulkObservationsPointResponse
	(*v1.ObservationsSeriesResponse)(nil),             // 104: datacommons.v1.ObservationsSeriesResponse
	(*v1.BulkObservationsSeriesResponse)(nil),         // 105: datacommons.v1.BulkObservationsSeriesResponse
	(*v1.DerivedObservationsSeriesResponse)(nil),      // 106: datacommons.v1.DerivedObservationsSeriesResponse
	(*v1.BulkObservationDatesLinkedResponse)(nil),     // 107: datacommons.v1.BulkObservationDatesLinkedResponse
	(*v1.BulkObservationExistenceResponse)(nil),       // 108: datacommons.v1.BulkObservationExistenceResponse
	(*proto.GraphNodes)(nil),                          // 109: datacommons.GraphNodes
	(*v1.PlacePageResponse)(nil),                      // 110: datacommons.v1.PlacePageResponse
	(*v1.VariableAncestorsResponse)(nil),              // 111: datacommons.v1.VariableAncestorsResponse
	(*proto.SearchStatVarResponse)(nil),               // 112: datacommons.SearchStatVarResponse
	(*v1.EventCollectionResponse)(nil),                // 113: datacommons.v1.EventCollectionResponse
	(*v1.EventCollectionDateResponse)(nil),            // 114: datacommons.v1.EventCollectionDateResponse
	(*proto.ResolveEntitiesResponse)(nil),             // 115: datacommons.ResolveEntitiesResponse
	(*proto.ResolveCoordinatesResponse)(nil),          // 116: datacommons.ResolveCoordinatesResponse
	(*proto.ResolveIdsResponse)(nil),                  // 117: datacommons.ResolveIdsResponse
	(*proto.FindEntitiesResponse)(nil),                // 118: datacommons.FindEntitiesResponse
	(*proto.BulkFindEntitiesResponse)(nil),            // 119: datacommons.BulkFindEntitiesResponse
	(*proto.RecognizePlacesResponse)(nil),             // 120: datacommons.RecognizePlacesResponse
	(*proto.RecognizeEntitiesResponse)(nil),           // 121: datacommons.RecognizeEntitiesResponse
	(*proto.UpdateCacheResponse)(nil),                 // 122: datacommons.UpdateCacheResponse
}
var file_service_mixer_proto_depIdxs = []int32{
	0,   // 0: datacommons.Mixer.V3Node:input_type -> datacommons.v2.NodeRequest
	1,   // 1: datacommons.Mixer.V3Observation:input_type -> datacommons.v2.ObservationRequest
	2,   // 2: datacommons.Mixer.V3NodeSearch:input_type -> datacommons.v2.NodeSearchRequest
	3,   // 3: datacommons.Mixer.V3Resolve:input_type -> datacommons.v2.ResolveRequest
	4,   // 4: datacommons.Mixer.V2Sparql:input_type -> datacommons.SparqlRequest
	3,   // 5: datacommons.Mixer.V2Resolve:input_type -> datacommons.v2.ResolveRequest
	0,   // 6: datacommons.Mixer.V2Node:input_type -> datacommons.v2.NodeRequest
	5,   // 7: datacommons.Mixer.V2Event:input_type -> datacommons.v2.EventRequest
	1,   // 8: datacommons.Mixer.V2Observation:input_type -> datacommons.v2.ObservationRequest
	6,   // 9: datacommons.Mixer.FilterStatVarsByEntity:input_type -> datacommons.FilterStatVarsByEntityRequest
	7,   // 10: datacommons.Mixer.Query:input_type -> datacommons.QueryRequest
	8,   // 11: datacommons.Mixer.GetPropertyLabels:input_type -> datacommons.GetPropertyLabelsRequest
	9,   // 12: datacommons.Mixer.GetPropertyValues:input_type -> datacommons.GetPropertyValuesRequest
	10,  // 13: datacommons.Mixer.GetTriples:input_type -> datacommons.GetTriplesRequest
	11,  // 14: datacommons.Mixer.GetPlacesIn:input_type -> datacommons.GetPlacesInRequest
	12,  // 15: datacommons.Mixer.GetStats:input_type -> datacommons.GetStatsRequest
	13,  // 16: datacommons.Mixer.GetStatValue:input_type -> datacommons.GetStatValueRequest
	14,  // 17: datacommons.Mixer.GetStatSeries:input_type -> datacommons.GetStatSeriesRequest
	15,  // 18: datacommons.Mixer.GetStatAll:input_type -> datacommons.GetStatAllRequest
	16,  // 19: datacommons.Mixer.GetLocationsRankings:input_type -> datacommons.GetLocationsRankingsRequest
	17,  // 20: datacommons.Mixer.GetRelatedLocations:input_type -> datacommons.GetRelatedLocationsRequest
	18,  // 21: datacommons.Mixer.Search:input_type -> datacommons.SearchRequest
	19,  // 22: datacommons.Mixer.GetVersion:input_type -> datacommons.GetVersionRequest
	20,  // 23: datacommons.Mixer.GetPlaceStatsVar:input_type -> datacommons.GetPlaceStatsVarRequest
	21,  // 24: datacommons.Mixer.GetPlaceStatVars:input_type -> datacommons.GetPlaceStatVarsRequest
	22,  // 25: datacommons.Mixer.GetEntityStatVarsUnionV1:input_type -> datacommons.GetEntityStatVarsUnionRequest
	23,  // 26: datacommons.Mixer.GetPlaceStatDateWithinPlace:input_type -> datacommons.GetPlaceStatDateWithinPlaceRequest
	24,  // 27: datacommons.Mixer.GetStatDateWithinPlace:input_type -> datacommons.GetStatDateWithinPlaceRequest
	25,  // 28: datacommons.Mixer.GetImportTableData:input_type -> datacommons.GetImportTableDataRequest
	7,   // 29: datacommons.Mixer.QueryV1:input_type -> datacommons.QueryRequest
	26,  // 30: datacommons.Mixer.Properties:input_type -> datacommons.v1.PropertiesRequest
	27,  // 31: datacommons.Mixer.BulkProperties:input_type -> datacommons.v1.BulkPropertiesRequest
	28,  // 32: datacommons.Mixer.PropertyValues:input_type -> datacommons.v1.PropertyValuesRequest
	29,  // 33: datacommons.Mixer.LinkedPropertyValues:input_type -> datacommons.v1.LinkedPropertyValuesRequest
	30,  // 34: datacommons.Mixer.BulkPropertyValues:input_type -> datacommons.v1.BulkPropertyValuesRequest
	31,  // 35: datacommons.Mixer.BulkLinkedPropertyValues:input_type -> datacommons.v1.BulkLinkedPropertyValuesRequest
	32,  // 36: datacommons.Mixer.Triples:input_type -> datacommons.v1.TriplesRequest
	33,  // 37: datacommons.Mixer.BulkTriples:input_type -> datacommons.v1.BulkTriplesRequest
	34,  // 38: datacommons.Mixer.Variables:input_type -> datacommons.v1.VariablesRequest
	35,  // 39: datacommons.Mixer.BulkVariables:input_type -> datacommons.v1.BulkVariablesRequest
	36,  // 40: datacommons.Mixer.PlaceInfo:input_type -> datacommons.v1.PlaceInfoRequest
	37,  // 41: datacommons.Mixer.BulkPlaceInfo:input_type -> datacommons.v1.BulkPlaceInfoRequest
	38,  // 42: datacommons.Mixer.VariableInfo:input_type -> datacommons.v1.VariableInfoRequest
	39,  // 43: datacommons.Mixer.BulkVariableInfo:input_type -> datacommons.v1.BulkVariableInfoRequest
	40,  // 44: datacommons.Mixer.VariableGroupInfo:input_type -> datacommons.v1.VariableGroupInfoRequest
	41,  // 45: datacommons.Mixer.BulkVariableGroupInfo:input_type -> datacommons.v1.BulkVariableGroupInfoRequest
	42,  // 46: datacommons.Mixer.ObservationsPoint:input_type -> datacommons.v1.ObservationsPointRequest
	43,  // 47: datacommons.Mixer.BulkObservationsPoint:input_type -> datacommons.v1.BulkObservationsPointRequest
	44,  // 48: datacommons.Mixer.BulkObservationsPointLinked:input_type -> datacommons.v1.BulkObservationsPointLinkedRequest
	45,  // 49: datacommons.Mixer.ObservationsSeries:input_type -> datacommons.v1.ObservationsSeriesRequest
	46,  // 50: datacommons.Mixer.BulkObservationsSeries:input_type -> datacommons.v1.BulkObservationsSeriesRequest
	47,  // 51: datacommons.Mixer.BulkObservationsSeriesLinked:input_type -> datacommons.v1.BulkObservationsSeriesLinkedRequest
	48,  // 52: datacommons.Mixer.DerivedObservationsSeries:input_type -> datacommons.v1.DerivedObservationsSeriesRequest
	49,  // 53: datacommons.Mixer.BulkObservationDatesLinked:input_type -> datacommons.v1.BulkObservationDatesLinkedRequest
	50,  // 54: datacommons.Mixer.BulkObservationExistence:input_type -> datacommons.v1.BulkObservationExistenceRequest
	51,  // 55: datacommons.Mixer.BioPage:input_type -> datacommons.v1.BioPageRequest
	52,  // 56: datacommons.Mixer.PlacePage:input_type -> datacommons.v1.PlacePageRequest
	53,  // 57: datacommons.Mixer.VariableAncestors:input_type -> datacommons.v1.VariableAncestorsRequest
	54,  // 58: datacommons.Mixer.SearchStatVar:input_type -> datacommons.SearchStatVarRequest
	55,  // 59: datacommons.Mixer.EventCollection:input_type -> datacommons.v1.EventCollectionRequest
	56,  // 60: datacommons.Mixer.EventCollectionDate:input_type -> datacommons.v1.EventCollectionDateRequest
	57,  // 61: datacommons.Mixer.ResolveEntities:input_type -> datacommons.ResolveEntitiesRequest
	58,  // 62: datacommons.Mixer.ResolveCoordinates:input_type -> datacommons.ResolveCoordinatesRequest
	59,  // 63: datacommons.Mixer.ResolveIds:input_type -> datacommons.ResolveIdsRequest
	60,  // 64: datacommons.Mixer.FindEntities:input_type -> datacommons.FindEntitiesRequest
	61,  // 65: datacommons.Mixer.BulkFindEntities:input_type -> datacommons.BulkFindEntitiesRequest
	62,  // 66: datacommons.Mixer.RecognizePlaces:input_type -> datacommons.RecognizePlacesRequest
	63,  // 67: datacommons.Mixer.RecognizeEntities:input_type -> datacommons.RecognizeEntitiesRequest
	64,  // 68: datacommons.Mixer.UpdateCache:input_type -> datacommons.UpdateCacheRequest
	65,  // 69: datacommons.Mixer.V3Node:output_type -> datacommons.v2.NodeResponse
	66,  // 70: datacommons.Mixer.V3Observation:output_type -> datacommons.v2.ObservationResponse
	67,  // 71: datacommons.Mixer.V3NodeSearch:output_type -> datacommons.v2.NodeSearchResponse
	68,  // 72: datacommons.Mixer.V3Resolve:output_type -> datacommons.v2.ResolveResponse
	69,  // 73: datacommons.Mixer.V2Sparql:output_type -> datacommons.QueryResponse
	68,  // 74: datacommons.Mixer.V2Resolve:output_type -> datacommons.v2.ResolveResponse
	65,  // 75: datacommons.Mixer.V2Node:output_type -> datacommons.v2.NodeResponse
	70,  // 76: datacommons.Mixer.V2Event:output_type -> datacommons.v2.EventResponse
	66,  // 77: datacommons.Mixer.V2Observation:output_type -> datacommons.v2.ObservationResponse
	71,  // 78: datacommons.Mixer.FilterStatVarsByEntity:output_type -> datacommons.FilterStatVarsByEntityResponse
	69,  // 79: datacommons.Mixer.Query:output_type -> datacommons.QueryResponse
	72,  // 80: datacommons.Mixer.GetPropertyLabels:output_type -> datacommons.PayloadResponse
	72,  // 81: datacommons.Mixer.GetPropertyValues:output_type -> datacommons.PayloadResponse
	72,  // 82: datacommons.Mixer.GetTriples:output_type -> datacommons.PayloadResponse
	73,  // 83: datacommons.Mixer.GetPlacesIn:output_type -> datacommons.GetPlacesInResponse
	74,  // 84: datacommons.Mixer.GetStats:output_type -> datacommons.GetStatsResponse
	75,  // 85: datacommons.Mixer.GetStatValue:output_type -> datacommons.GetStatValueResponse
	76,  // 86: datacommons.Mixer.GetStatSeries:output_type -> datacommons.GetStatSeriesResponse
	77,  // 87: datacommons.Mixer.GetStatAll:output_type -> datacommons.GetStatAllResponse
	78,  // 88: datacommons.Mixer.GetLocationsRankings:output_type -> datacommons.GetLocationsRankingsResponse
	79,  // 89: datacommons.Mixer.GetRelatedLocations:output_type -> datacommons.GetRelatedLocationsResponse
	80,  // 90: datacommons.Mixer.Search:output_type -> datacommons.SearchResponse
	81,  // 91: datacommons.Mixer.GetVersion:output_type -> datacommons.GetVersionResponse
	82,  // 92: datacommons.Mixer.GetPlaceStatsVar:output_type -> datacommons.GetPlaceStatsVarResponse
	83,  // 93: datacommons.Mixer.GetPlaceStatVars:output_type -> datacommons.GetPlaceStatVarsResponse
	84,  // 94: datacommons.Mixer.GetEntityStatVarsUnionV1:output_type -> datacommons.GetEntityStatVarsUnionResponse
	85,  // 95: datacommons.Mixer.GetPlaceStatDateWithinPlace:output_type -> datacommons.GetPlaceStatDateWithinPlaceResponse
	86,  // 96: datacommons.Mixer.GetStatDateWithinPlace:output_type -> datacommons.GetStatDateWithinPlaceResponse
	87,  // 97: datacommons.Mixer.GetImportTableData:output_type -> datacommons.GetImportTableDataResponse
	69,  // 98: datacommons.Mixer.QueryV1:output_type -> datacommons.QueryResponse
	88,  // 99: datacommons.Mixer.Properties:output_type -> datacommons.v1.PropertiesResponse
	89,  // 100: datacommons.Mixer.BulkProperties:output_type -> datacommons.v1.BulkPropertiesResponse
	90,  // 101: datacommons.Mixer.PropertyValues:output_type -> datacommons.v1.PropertyValuesResponse
	90,  // 102: datacommons.Mixer.LinkedPropertyValues:output_type -> datacommons.v1.PropertyValuesResponse
	91,  // 103: datacommons.Mixer.BulkPropertyValues:output_type -> datacommons.v1.BulkPropertyValuesResponse
	91,  // 104: datacommons.Mixer.BulkLinkedPropertyValues:output_type -> datacommons.v1.BulkPropertyValuesResponse
	92,  // 105: datacommons.Mixer.Triples:output_type -> datacommons.v1.TriplesResponse
	93,  // 106: datacommons.Mixer.BulkTriples:output_type -> datacommons.v1.BulkTriplesResponse
	94,  // 107: datacommons.Mixer.Variables:output_type -> datacommons.v1.VariablesResponse
	95,  // 108: datacommons.Mixer.BulkVariables:output_type -> datacommons.v1.BulkVariablesResponse
	96,  // 109: datacommons.Mixer.PlaceInfo:output_type -> datacommons.v1.PlaceInfoResponse
	97,  // 110: datacommons.Mixer.BulkPlaceInfo:output_type -> datacommons.v1.BulkPlaceInfoResponse
	98,  // 111: datacommons.Mixer.VariableInfo:output_type -> datacommons.v1.VariableInfoResponse
	99,  // 112: datacommons.Mixer.BulkVariableInfo:output_type -> datacommons.v1.BulkVariableInfoResponse
	100, // 113: datacommons.Mixer.VariableGroupInfo:output_type -> datacommons.v1.VariableGroupInfoResponse
	101, // 114: datacommons.Mixer.BulkVariableGroupInfo:output_type -> datacommons.v1.BulkVariableGroupInfoResponse
	102, // 115: datacommons.Mixer.ObservationsPoint:output_type -> datacommons.PointStat
	103, // 116: datacommons.Mixer.BulkObservationsPoint:output_type -> datacommons.v1.BulkObservationsPointResponse
	103, // 117: datacommons.Mixer.BulkObservationsPointLinked:output_type -> datacommons.v1.BulkObservationsPointResponse
	104, // 118: datacommons.Mixer.ObservationsSeries:output_type -> datacommons.v1.ObservationsSeriesResponse
	105, // 119: datacommons.Mixer.BulkObservationsSeries:output_type -> datacommons.v1.BulkObservationsSeriesResponse
	105, // 120: datacommons.Mixer.BulkObservationsSeriesLinked:output_type -> datacommons.v1.BulkObservationsSeriesResponse
	106, // 121: datacommons.Mixer.DerivedObservationsSeries:output_type -> datacommons.v1.DerivedObservationsSeriesResponse
	107, // 122: datacommons.Mixer.BulkObservationDatesLinked:output_type -> datacommons.v1.BulkObservationDatesLinkedResponse
	108, // 123: datacommons.Mixer.BulkObservationExistence:output_type -> datacommons.v1.BulkObservationExistenceResponse
	109, // 124: datacommons.Mixer.BioPage:output_type -> datacommons.GraphNodes
	110, // 125: datacommons.Mixer.PlacePage:output_type -> datacommons.v1.PlacePageResponse
	111, // 126: datacommons.Mixer.VariableAncestors:output_type -> datacommons.v1.VariableAncestorsResponse
	112, // 127: datacommons.Mixer.SearchStatVar:output_type -> datacommons.SearchStatVarResponse
	113, // 128: datacommons.Mixer.EventCollection:output_type -> datacommons.v1.EventCollectionResponse
	114, // 129: datacommons.Mixer.EventCollectionDate:output_type -> datacommons.v1.EventCollectionDateResponse
	115, // 130: datacommons.Mixer.ResolveEntities:output_type -> datacommons.ResolveEntitiesResponse
	116, // 131: datacommons.Mixer.ResolveCoordinates:output_type -> datacommons.ResolveCoordinatesResponse
	117, // 132: datacommons.Mixer.ResolveIds:output_type -> datacommons.ResolveIdsResponse
	118, // 133: datacommons.Mixer.FindEntities:output_type -> datacommons.FindEntitiesResponse
	119, // 134: datacommons.Mixer.BulkFindEntities:output_type -> datacommons.BulkFindEntitiesResponse
	120, // 135: datacommons.Mixer.RecognizePlaces:output_type -> datacommons.RecognizePlacesResponse
	121, // 136: datacommons.Mixer.RecognizeEntities:output_type -> datacommons.RecognizeEntitiesResponse
	122, // 137: datacommons.Mixer.UpdateCache:output_type -> datacommons.UpdateCacheResponse
	69,  // [69:138] is the sub-list for method output_type
	0,   // [0:69] is the sub-list for method input_type
	0,   // [0:0] is the sub-list for extension type_name
	0,   // [0:0] is the sub-list for extension extendee
	0,   // [0:0] is the sub-list for field type_name
}

func init() { file_service_mixer_proto_init() }
func file_service_mixer_proto_init() {
	if File_service_mixer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_mixer_proto_rawDesc), len(file_service_mixer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_mixer_proto_goTypes,
		DependencyIndexes: file_service_mixer_proto_depIdxs,
	}.Build()
	File_service_mixer_proto = out.File
	file_service_mixer_proto_goTypes = nil
	file_service_mixer_proto_depIdxs = nil
}
