// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//  **** IMPORTANT NOTE ****
//
//  The proto of BT data has to match exactly the g3 proto, including tag
//  number.

// Mixer service definitions

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: service/mixer.proto

package service

import (
	proto "github.com/datacommonsorg/mixer/internal/proto"
	v1 "github.com/datacommonsorg/mixer/internal/proto/v1"
	v2 "github.com/datacommonsorg/mixer/internal/proto/v2"
	v3 "github.com/datacommonsorg/mixer/internal/proto/v3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_mixer_proto protoreflect.FileDescriptor

const file_service_mixer_proto_rawDesc = "" +
	"\n" +
	"\x13service/mixer.proto\x12\vdatacommons\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/api/httpbody.proto\x1a\fcommon.proto\x1a\fcustom.proto\x1a\n" +
	"misc.proto\x1a\n" +
	"node.proto\x1a\vplace.proto\x1a\vquery.proto\x1a\n" +
	"stat.proto\x1a\x0estat_var.proto\x1a\vrecon.proto\x1a\x13v1/properties.proto\x1a\x18v1/property_values.proto\x1a\x11v1/variable.proto\x1a\rv1/info.proto\x1a\x15v1/observations.proto\x1a\x1av1/observation_dates.proto\x1a\rv1/page.proto\x1a\x10v1/triples.proto\x1a\x0ev2/event.proto\x1a\rv2/node.proto\x1a\x14v2/node_search.proto\x1a\x14v2/observation.proto\x1a\x10v2/resolve.proto\x1a\x0ev2/agent.proto\x1a\rv3/data.proto2\xe6P\n" +
	"\x05Mixer\x12d\n" +
	"\x06V3Node\x12\x1b.datacommons.v2.NodeRequest\x1a\x1c.datacommons.v2.NodeResponse\"\x1f\x82\xd3\xe4\x93\x02\x19Z\r:\x01*\"\b/v3/node\x12\b/v3/node\x12\x87\x01\n" +
	"\rV3Observation\x12\".datacommons.v2.ObservationRequest\x1a#.datacommons.v2.ObservationResponse\"-\x82\xd3\xe4\x93\x02'Z\x14:\x01*\"\x0f/v3/observation\x12\x0f/v3/observation\x12w\n" +
	"\n" +
	"V3SdmxData\x12\x1f.datacommons.v3.SdmxRestRequest\x1a\x14.google.api.HttpBody\"0\x82\xd3\xe4\x93\x02*Z\x0f\x12\r/sdmx/v3/data\x12\x17/sdmx/v3/data/{tail=**}0\x01\x12\x8d\x01\n" +
	"\x12V3SdmxAvailability\x12\x1f.datacommons.v3.SdmxRestRequest\x1a\x14.google.api.HttpBody\"@\x82\xd3\xe4\x93\x02:Z\x17\x12\x15/sdmx/v3/availability\x12\x1f/sdmx/v3/availability/{tail=**}\x12\x84\x01\n" +
	"\fV3NodeSearch\x12!.datacommons.v2.NodeSearchRequest\x1a\".datacommons.v2.NodeSearchResponse\"-\x82\xd3\xe4\x93\x02'Z\x14:\x01*\"\x0f/v3/node_search\x12\x0f/v3/node_search\x12s\n" +
	"\tV3Resolve\x12\x1e.datacommons.v2.ResolveRequest\x1a\x1f.datacommons.v2.ResolveResponse\"%\x82\xd3\xe4\x93\x02\x1fZ\x10:\x01*\"\v/v3/resolve\x12\v/v3/resolve\x12i\n" +
	"\aV3Event\x12\x1c.datacommons.v2.EventRequest\x1a\x1d.datacommons.v2.EventResponse\"!\x82\xd3\xe4\x93\x02\x1bZ\x0e:\x01*\"\t/v3/event\x12\t/v3/event\x12g\n" +
	"\bV3Sparql\x12\x1a.datacommons.SparqlRequest\x1a\x1a.datacommons.QueryResponse\"#\x82\xd3\xe4\x93\x02\x1dZ\x0f:\x01*\"\n" +
	"/v3/sparql\x12\n" +
	"/v3/sparql\x12\xa4\x01\n" +
	"\x12V3BulkVariableInfo\x12'.datacommons.v1.BulkVariableInfoRequest\x1a(.datacommons.v1.BulkVariableInfoResponse\";\x82\xd3\xe4\x93\x025Z\x1b:\x01*\"\x16/v3/bulk/info/variable\x12\x16/v3/bulk/info/variable\x12\xbf\x01\n" +
	"\x17V3BulkVariableGroupInfo\x12,.datacommons.v1.BulkVariableGroupInfoRequest\x1a-.datacommons.v1.BulkVariableGroupInfoResponse\"G\x82\xd3\xe4\x93\x02AZ!:\x01*\"\x1c/v3/bulk/info/variable-group\x12\x1c/v3/bulk/info/variable-group\x12g\n" +
	"\bV2Sparql\x12\x1a.datacommons.SparqlRequest\x1a\x1a.datacommons.QueryResponse\"#\x82\xd3\xe4\x93\x02\x1dZ\x0f:\x01*\"\n" +
	"/v2/sparql\x12\n" +
	"/v2/sparql\x12s\n" +
	"\tV2Resolve\x12\x1e.datacommons.v2.ResolveRequest\x1a\x1f.datacommons.v2.ResolveResponse\"%\x82\xd3\xe4\x93\x02\x1fZ\x10:\x01*\"\v/v2/resolve\x12\v/v2/resolve\x12d\n" +
	"\x06V2Node\x12\x1b.datacommons.v2.NodeRequest\x1a\x1c.datacommons.v2.NodeResponse\"\x1f\x82\xd3\xe4\x93\x02\x19Z\r:\x01*\"\b/v2/node\x12\b/v2/node\x12i\n" +
	"\aV2Event\x12\x1c.datacommons.v2.EventRequest\x1a\x1d.datacommons.v2.EventResponse\"!\x82\xd3\xe4\x93\x02\x1bZ\x0e:\x01*\"\t/v2/event\x12\t/v2/event\x12\x87\x01\n" +
	"\rV2Observation\x12\".datacommons.v2.ObservationRequest\x1a#.datacommons.v2.ObservationResponse\"-\x82\xd3\xe4\x93\x02'Z\x14:\x01*\"\x0f/v2/observation\x12\x0f/v2/observation\x12\x97\x01\n" +
	"\x11V2RecognizePlaces\x12#.datacommons.RecognizePlacesRequest\x1a$.datacommons.RecognizePlacesResponse\"7\x82\xd3\xe4\x93\x021Z\x19:\x01*\"\x14/v2/recognize/places\x12\x14/v2/recognize/places\x12\x91\x01\n" +
	"\x16FilterStatVarsByEntity\x12*.datacommons.FilterStatVarsByEntityRequest\x1a+.datacommons.FilterStatVarsByEntityResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v2/variable/filter\x12\xa4\x01\n" +
	"\x12V2BulkVariableInfo\x12'.datacommons.v1.BulkVariableInfoRequest\x1a(.datacommons.v1.BulkVariableInfoResponse\";\x82\xd3\xe4\x93\x025Z\x1b:\x01*\"\x16/v2/bulk/info/variable\x12\x16/v2/bulk/info/variable\x12\xbf\x01\n" +
	"\x17V2BulkVariableGroupInfo\x12,.datacommons.v1.BulkVariableGroupInfoRequest\x1a-.datacommons.v1.BulkVariableGroupInfoResponse\"G\x82\xd3\xe4\x93\x02AZ!:\x01*\"\x1c/v2/bulk/info/variable-group\x12\x1c/v2/bulk/info/variable-group\x12\xb3\x01\n" +
	"\x17V2AgentSearchIndicators\x12'.datacommons.v2.SearchIndicatorsRequest\x1a(.datacommons.v2.SearchIndicatorsResponse\"E\x82\xd3\xe4\x93\x02?Z :\x01*\"\x1b/v2/agent/search_indicators\x12\x1b/v2/agent/search_indicators\x12\xae\x01\n" +
	"\x16V2AgentGetObservations\x12&.datacommons.v2.GetObservationsRequest\x1a'.datacommons.v2.GetObservationsResponse\"C\x82\xd3\xe4\x93\x02=Z\x1f:\x01*\"\x1a/v2/agent/get_observations\x12\x1a/v2/agent/get_observations\x12\xc4\x01\n" +
	"\x1aV2AgentGetVariableMetadata\x12*.datacommons.v2.GetVariableMetadataRequest\x1a+.datacommons.v2.GetVariableMetadataResponse\"M\x82\xd3\xe4\x93\x02GZ$:\x01*\"\x1f/v2/agent/get_variable_metadata\x12\x1f/v2/agent/get_variable_metadata\x12\xa0\x01\n" +
	"\x16V2GetLocationsRankings\x12(.datacommons.GetLocationsRankingsRequest\x1a).datacommons.GetLocationsRankingsResponse\"1\x82\xd3\xe4\x93\x02+Z\x16:\x01*\"\x11/v2/place/ranking\x12\x11/v2/place/ranking\x12[\n" +
	"\x05Query\x12\x19.datacommons.QueryRequest\x1a\x1a.datacommons.QueryResponse\"\x1b\x82\xd3\xe4\x93\x02\x15Z\v:\x01*\"\x06/query\x12\x06/query\x12\x93\x01\n" +
	"\x11GetPropertyLabels\x12%.datacommons.GetPropertyLabelsRequest\x1a\x1c.datacommons.PayloadResponse\"9\x82\xd3\xe4\x93\x023Z\x1a:\x01*\"\x15/node/property-labels\x12\x15/node/property-labels\x12\x93\x01\n" +
	"\x11GetPropertyValues\x12%.datacommons.GetPropertyValuesRequest\x1a\x1c.datacommons.PayloadResponse\"9\x82\xd3\xe4\x93\x023Z\x1a:\x01*\"\x15/node/property-values\x12\x15/node/property-values\x12u\n" +
	"\n" +
	"GetTriples\x12\x1e.datacommons.GetTriplesRequest\x1a\x1c.datacommons.PayloadResponse\")\x82\xd3\xe4\x93\x02#Z\x12:\x01*\"\r/node/triples\x12\r/node/triples\x12\x7f\n" +
	"\vGetPlacesIn\x12\x1f.datacommons.GetPlacesInRequest\x1a .datacommons.GetPlacesInResponse\"-\x82\xd3\xe4\x93\x02'Z\x14:\x01*\"\x0f/node/places-in\x12\x0f/node/places-in\x12n\n" +
	"\bGetStats\x12\x1c.datacommons.GetStatsRequest\x1a\x1d.datacommons.GetStatsResponse\"%\x82\xd3\xe4\x93\x02\x1fZ\x10:\x01*\"\v/bulk/stats\x12\v/bulk/stats\x12z\n" +
	"\fGetStatValue\x12 .datacommons.GetStatValueRequest\x1a!.datacommons.GetStatValueResponse\"%\x82\xd3\xe4\x93\x02\x1fZ\x10:\x01*\"\v/stat/value\x12\v/stat/value\x12\x7f\n" +
	"\rGetStatSeries\x12!.datacommons.GetStatSeriesRequest\x1a\".datacommons.GetStatSeriesResponse\"'\x82\xd3\xe4\x93\x02!Z\x11:\x01*\"\f/stat/series\x12\f/stat/series\x12p\n" +
	"\n" +
	"GetStatAll\x12\x1e.datacommons.GetStatAllRequest\x1a\x1f.datacommons.GetStatAllResponse\"!\x82\xd3\xe4\x93\x02\x1bZ\x0e:\x01*\"\t/stat/all\x12\t/stat/all\x12\x9e\x01\n" +
	"\x14GetLocationsRankings\x12(.datacommons.GetLocationsRankingsRequest\x1a).datacommons.GetLocationsRankingsResponse\"1\x82\xd3\xe4\x93\x02+Z\x16:\x01*\"\x11/v1/place/ranking\x12\x11/v1/place/ranking\x12\x9b\x01\n" +
	"\x13GetRelatedLocations\x12'.datacommons.GetRelatedLocationsRequest\x1a(.datacommons.GetRelatedLocationsResponse\"1\x82\xd3\xe4\x93\x02+Z\x16:\x01*\"\x11/v1/place/related\x12\x11/v1/place/related\x12_\n" +
	"\n" +
	"GetVersion\x12\x1e.datacommons.GetVersionRequest\x1a\x1f.datacommons.GetVersionResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/version\x12\x90\x01\n" +
	"\x10GetPlaceStatVars\x12$.datacommons.GetPlaceStatVarsRequest\x1a%.datacommons.GetPlaceStatVarsResponse\"/\x82\xd3\xe4\x93\x02)Z\x15:\x01*\"\x10/place/stat-vars\x12\x10/place/stat-vars\x12\xb6\x01\n" +
	"\x18GetEntityStatVarsUnionV1\x12*.datacommons.GetEntityStatVarsUnionRequest\x1a+.datacommons.GetEntityStatVarsUnionResponse\"A\x82\xd3\xe4\x93\x02;Z\x1e:\x01*\"\x19/v1/place/stat-vars/union\x12\x19/v1/place/stat-vars/union\x12c\n" +
	"\aQueryV1\x12\x19.datacommons.QueryRequest\x1a\x1a.datacommons.QueryResponse\"!\x82\xd3\xe4\x93\x02\x1bZ\x0e:\x01*\"\t/v1/query\x12\t/v1/query\x12\x81\x01\n" +
	"\n" +
	"Properties\x12!.datacommons.v1.PropertiesRequest\x1a\".datacommons.v1.PropertiesResponse\",\x82\xd3\xe4\x93\x02&\x12$/v1/properties/{direction}/{node=**}\x12\xae\x01\n" +
	"\x0eBulkProperties\x12%.datacommons.v1.BulkPropertiesRequest\x1a&.datacommons.v1.BulkPropertiesResponse\"M\x82\xd3\xe4\x93\x02GZ$:\x01*\"\x1f/v1/bulk/properties/{direction}\x12\x1f/v1/bulk/properties/{direction}\x12\x9b\x01\n" +
	"\x0ePropertyValues\x12%.datacommons.v1.PropertyValuesRequest\x1a&.datacommons.v1.PropertyValuesResponse\":\x82\xd3\xe4\x93\x024\x122/v1/property/values/{direction}/{node_property=**}\x12\xa5\x01\n" +
	"\x14LinkedPropertyValues\x12+.datacommons.v1.LinkedPropertyValuesRequest\x1a&.datacommons.v1.PropertyValuesResponse\"8\x82\xd3\xe4\x93\x022\x120/v1/property/values/in/linked/{node_property=**}\x12\xc4\x01\n" +
	"\x12BulkPropertyValues\x12).datacommons.v1.BulkPropertyValuesRequest\x1a*.datacommons.v1.BulkPropertyValuesResponse\"W\x82\xd3\xe4\x93\x02QZ):\x01*\"$/v1/bulk/property/values/{direction}\x12$/v1/bulk/property/values/{direction}\x12\xcc\x01\n" +
	"\x18BulkLinkedPropertyValues\x12/.datacommons.v1.BulkLinkedPropertyValuesRequest\x1a*.datacommons.v1.BulkPropertyValuesResponse\"S\x82\xd3\xe4\x93\x02MZ':\x01*\"\"/v1/bulk/property/values/in/linked\x12\"/v1/bulk/property/values/in/linked\x12u\n" +
	"\aTriples\x12\x1e.datacommons.v1.TriplesRequest\x1a\x1f.datacommons.v1.TriplesResponse\")\x82\xd3\xe4\x93\x02#\x12!/v1/triples/{direction}/{node=**}\x12\x9f\x01\n" +
	"\vBulkTriples\x12\".datacommons.v1.BulkTriplesRequest\x1a#.datacommons.v1.BulkTriplesResponse\"G\x82\xd3\xe4\x93\x02AZ!:\x01*\"\x1c/v1/bulk/triples/{direction}\x12\x1c/v1/bulk/triples/{direction}\x12s\n" +
	"\tVariables\x12 .datacommons.v1.VariablesRequest\x1a!.datacommons.v1.VariablesResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/variables/{entity=**}\x12r\n" +
	"\tPlaceInfo\x12 .datacommons.v1.PlaceInfoRequest\x1a!.datacommons.v1.PlaceInfoResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/info/place/{node=**}\x12\x93\x01\n" +
	"\rBulkPlaceInfo\x12$.datacommons.v1.BulkPlaceInfoRequest\x1a%.datacommons.v1.BulkPlaceInfoResponse\"5\x82\xd3\xe4\x93\x02/Z\x18:\x01*\"\x13/v1/bulk/info/place\x12\x13/v1/bulk/info/place\x12~\n" +
	"\fVariableInfo\x12#.datacommons.v1.VariableInfoRequest\x1a$.datacommons.v1.VariableInfoResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/info/variable/{node=**}\x12\xa2\x01\n" +
	"\x10BulkVariableInfo\x12'.datacommons.v1.BulkVariableInfoRequest\x1a(.datacommons.v1.BulkVariableInfoResponse\";\x82\xd3\xe4\x93\x025Z\x1b:\x01*\"\x16/v1/bulk/info/variable\x12\x16/v1/bulk/info/variable\x12\x93\x01\n" +
	"\x11VariableGroupInfo\x12(.datacommons.v1.VariableGroupInfoRequest\x1a).datacommons.v1.VariableGroupInfoResponse\")\x82\xd3\xe4\x93\x02#\x12!/v1/info/variable-group/{node=**}\x12\xbd\x01\n" +
	"\x15BulkVariableGroupInfo\x12,.datacommons.v1.BulkVariableGroupInfoRequest\x1a-.datacommons.v1.BulkVariableGroupInfoResponse\"G\x82\xd3\xe4\x93\x02AZ!:\x01*\"\x1c/v1/bulk/info/variable-group\x12\x1c/v1/bulk/info/variable-group\x12\x8a\x01\n" +
	"\x11ObservationsPoint\x12(.datacommons.v1.ObservationsPointRequest\x1a\x16.datacommons.PointStat\"3\x82\xd3\xe4\x93\x02-\x12+/v1/observations/point/{entity_variable=**}\x12\xbb\x01\n" +
	"\x15BulkObservationsPoint\x12,.datacommons.v1.BulkObservationsPointRequest\x1a-.datacommons.v1.BulkObservationsPointResponse\"E\x82\xd3\xe4\x93\x02?Z :\x01*\"\x1b/v1/bulk/observations/point\x12\x1b/v1/bulk/observations/point\x12\xa1\x01\n" +
	"\x12ObservationsSeries\x12).datacommons.v1.ObservationsSeriesRequest\x1a*.datacommons.v1.ObservationsSeriesResponse\"4\x82\xd3\xe4\x93\x02.\x12,/v1/observations/series/{entity_variable=**}\x12\xc0\x01\n" +
	"\x16BulkObservationsSeries\x12-.datacommons.v1.BulkObservationsSeriesRequest\x1a..datacommons.v1.BulkObservationsSeriesResponse\"G\x82\xd3\xe4\x93\x02AZ!:\x01*\"\x1c/v1/bulk/observations/series\x12\x1c/v1/bulk/observations/series\x12\xda\x01\n" +
	"\x1cBulkObservationsSeriesLinked\x123.datacommons.v1.BulkObservationsSeriesLinkedRequest\x1a..datacommons.v1.BulkObservationsSeriesResponse\"U\x82\xd3\xe4\x93\x02OZ(:\x01*\"#/v1/bulk/observations/series/linked\x12#/v1/bulk/observations/series/linked\x12\xd6\x01\n" +
	"\x1aBulkObservationDatesLinked\x121.datacommons.v1.BulkObservationDatesLinkedRequest\x1a2.datacommons.v1.BulkObservationDatesLinkedResponse\"Q\x82\xd3\xe4\x93\x02KZ&:\x01*\"!/v1/bulk/observation-dates/linked\x12!/v1/bulk/observation-dates/linked\x12\x99\x01\n" +
	"\tPlacePage\x12 .datacommons.v1.PlacePageRequest\x1a!.datacommons.v1.PlacePageResponse\"G\x82\xd3\xe4\x93\x02AZ\x1c:\x01*\"\x17/v1/internal/page/place\x12!/v1/internal/page/place/{node=**}\x12\xaf\x01\n" +
	"\x11VariableAncestors\x12(.datacommons.v1.VariableAncestorsRequest\x1a).datacommons.v1.VariableAncestorsResponse\"E\x82\xd3\xe4\x93\x02?Z\x1b:\x01*\"\x16/v1/variable/ancestors\x12 /v1/variable/ancestors/{node=**}\x12\x8d\x01\n" +
	"\rSearchStatVar\x12!.datacommons.SearchStatVarRequest\x1a\".datacommons.SearchStatVarResponse\"5\x82\xd3\xe4\x93\x02/Z\x18:\x01*\"\x13/v1/variable/search\x12\x13/v1/variable/search\x12\x81\x01\n" +
	"\x0fResolveEntities\x12#.datacommons.ResolveEntitiesRequest\x1a$.datacommons.ResolveEntitiesResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/recon/entity/resolve\x12\x8e\x01\n" +
	"\x12ResolveCoordinates\x12&.datacommons.ResolveCoordinatesRequest\x1a'.datacommons.ResolveCoordinatesResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/recon/resolve/coordinate\x12n\n" +
	"\n" +
	"ResolveIds\x12\x1e.datacommons.ResolveIdsRequest\x1a\x1f.datacommons.ResolveIdsResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/recon/resolve/id\x12\x86\x01\n" +
	"\fFindEntities\x12 .datacommons.FindEntitiesRequest\x1a!.datacommons.FindEntitiesResponse\"1\x82\xd3\xe4\x93\x02+Z\x16:\x01*\"\x11/v1/find/entities\x12\x11/v1/find/entities\x12\x82\x01\n" +
	"\x10BulkFindEntities\x12$.datacommons.BulkFindEntitiesRequest\x1a%.datacommons.BulkFindEntitiesResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/bulk/find/entities\x12\x95\x01\n" +
	"\x0fRecognizePlaces\x12#.datacommons.RecognizePlacesRequest\x1a$.datacommons.RecognizePlacesResponse\"7\x82\xd3\xe4\x93\x021Z\x19:\x01*\"\x14/v1/recognize/places\x12\x14/v1/recognize/places\x12\xa2\x01\n" +
	"\x11RecognizeEntities\x12%.datacommons.RecognizeEntitiesRequest\x1a&.datacommons.RecognizeEntitiesResponse\">\x82\xd3\xe4\x93\x025Z\x1b:\x01*\"\x16/v1/recognize/entities\x12\x16/v1/recognize/entities\x88\x02\x01\x12\x9e\x01\n" +
	"\x12GetImportTableData\x12&.datacommons.GetImportTableDataRequest\x1a'.datacommons.GetImportTableDataResponse\"7\x82\xd3\xe4\x93\x021Z\x19:\x01*\"\x14/custom/import-table\x12\x14/custom/import-tableB8Z6github.com/datacommonsorg/mixer/internal/proto/serviceb\x06proto3"

var file_service_mixer_proto_goTypes = []any{
	(*v2.NodeRequest)(nil),                         // 0: datacommons.v2.NodeRequest
	(*v2.ObservationRequest)(nil),                  // 1: datacommons.v2.ObservationRequest
	(*v3.SdmxRestRequest)(nil),                     // 2: datacommons.v3.SdmxRestRequest
	(*v2.NodeSearchRequest)(nil),                   // 3: datacommons.v2.NodeSearchRequest
	(*v2.ResolveRequest)(nil),                      // 4: datacommons.v2.ResolveRequest
	(*v2.EventRequest)(nil),                        // 5: datacommons.v2.EventRequest
	(*proto.SparqlRequest)(nil),                    // 6: datacommons.SparqlRequest
	(*v1.BulkVariableInfoRequest)(nil),             // 7: datacommons.v1.BulkVariableInfoRequest
	(*v1.BulkVariableGroupInfoRequest)(nil),        // 8: datacommons.v1.BulkVariableGroupInfoRequest
	(*proto.RecognizePlacesRequest)(nil),           // 9: datacommons.RecognizePlacesRequest
	(*proto.FilterStatVarsByEntityRequest)(nil),    // 10: datacommons.FilterStatVarsByEntityRequest
	(*v2.SearchIndicatorsRequest)(nil),             // 11: datacommons.v2.SearchIndicatorsRequest
	(*v2.GetObservationsRequest)(nil),              // 12: datacommons.v2.GetObservationsRequest
	(*v2.GetVariableMetadataRequest)(nil),          // 13: datacommons.v2.GetVariableMetadataRequest
	(*proto.GetLocationsRankingsRequest)(nil),      // 14: datacommons.GetLocationsRankingsRequest
	(*proto.QueryRequest)(nil),                     // 15: datacommons.QueryRequest
	(*proto.GetPropertyLabelsRequest)(nil),         // 16: datacommons.GetPropertyLabelsRequest
	(*proto.GetPropertyValuesRequest)(nil),         // 17: datacommons.GetPropertyValuesRequest
	(*proto.GetTriplesRequest)(nil),                // 18: datacommons.GetTriplesRequest
	(*proto.GetPlacesInRequest)(nil),               // 19: datacommons.GetPlacesInRequest
	(*proto.GetStatsRequest)(nil),                  // 20: datacommons.GetStatsRequest
	(*proto.GetStatValueRequest)(nil),              // 21: datacommons.GetStatValueRequest
	(*proto.GetStatSeriesRequest)(nil),             // 22: datacommons.GetStatSeriesRequest
	(*proto.GetStatAllRequest)(nil),                // 23: datacommons.GetStatAllRequest
	(*proto.GetRelatedLocationsRequest)(nil),       // 24: datacommons.GetRelatedLocationsRequest
	(*proto.GetVersionRequest)(nil),                // 25: datacommons.GetVersionRequest
	(*proto.GetPlaceStatVarsRequest)(nil),          // 26: datacommons.GetPlaceStatVarsRequest
	(*proto.GetEntityStatVarsUnionRequest)(nil),    // 27: datacommons.GetEntityStatVarsUnionRequest
	(*v1.PropertiesRequest)(nil),                   // 28: datacommons.v1.PropertiesRequest
	(*v1.BulkPropertiesRequest)(nil),               // 29: datacommons.v1.BulkPropertiesRequest
	(*v1.PropertyValuesRequest)(nil),               // 30: datacommons.v1.PropertyValuesRequest
	(*v1.LinkedPropertyValuesRequest)(nil),         // 31: datacommons.v1.LinkedPropertyValuesRequest
	(*v1.BulkPropertyValuesRequest)(nil),           // 32: datacommons.v1.BulkPropertyValuesRequest
	(*v1.BulkLinkedPropertyValuesRequest)(nil),     // 33: datacommons.v1.BulkLinkedPropertyValuesRequest
	(*v1.TriplesRequest)(nil),                      // 34: datacommons.v1.TriplesRequest
	(*v1.BulkTriplesRequest)(nil),                  // 35: datacommons.v1.BulkTriplesRequest
	(*v1.VariablesRequest)(nil),                    // 36: datacommons.v1.VariablesRequest
	(*v1.PlaceInfoRequest)(nil),                    // 37: datacommons.v1.PlaceInfoRequest
	(*v1.BulkPlaceInfoRequest)(nil),                // 38: datacommons.v1.BulkPlaceInfoRequest
	(*v1.VariableInfoRequest)(nil),                 // 39: datacommons.v1.VariableInfoRequest
	(*v1.VariableGroupInfoRequest)(nil),            // 40: datacommons.v1.VariableGroupInfoRequest
	(*v1.ObservationsPointRequest)(nil),            // 41: datacommons.v1.ObservationsPointRequest
	(*v1.BulkObservationsPointRequest)(nil),        // 42: datacommons.v1.BulkObservationsPointRequest
	(*v1.ObservationsSeriesRequest)(nil),           // 43: datacommons.v1.ObservationsSeriesRequest
	(*v1.BulkObservationsSeriesRequest)(nil),       // 44: datacommons.v1.BulkObservationsSeriesRequest
	(*v1.BulkObservationsSeriesLinkedRequest)(nil), // 45: datacommons.v1.BulkObservationsSeriesLinkedRequest
	(*v1.BulkObservationDatesLinkedRequest)(nil),   // 46: datacommons.v1.BulkObservationDatesLinkedRequest
	(*v1.PlacePageRequest)(nil),                    // 47: datacommons.v1.PlacePageRequest
	(*v1.VariableAncestorsRequest)(nil),            // 48: datacommons.v1.VariableAncestorsRequest
	(*proto.SearchStatVarRequest)(nil),             // 49: datacommons.SearchStatVarRequest
	(*proto.ResolveEntitiesRequest)(nil),           // 50: datacommons.ResolveEntitiesRequest
	(*proto.ResolveCoordinatesRequest)(nil),        // 51: datacommons.ResolveCoordinatesRequest
	(*proto.ResolveIdsRequest)(nil),                // 52: datacommons.ResolveIdsRequest
	(*proto.FindEntitiesRequest)(nil),              // 53: datacommons.FindEntitiesRequest
	(*proto.BulkFindEntitiesRequest)(nil),          // 54: datacommons.BulkFindEntitiesRequest
	(*proto.RecognizeEntitiesRequest)(nil),         // 55: datacommons.RecognizeEntitiesRequest
	(*proto.GetImportTableDataRequest)(nil),        // 56: datacommons.GetImportTableDataRequest
	(*v2.NodeResponse)(nil),                        // 57: datacommons.v2.NodeResponse
	(*v2.ObservationResponse)(nil),                 // 58: datacommons.v2.ObservationResponse
	(*httpbody.HttpBody)(nil),                      // 59: google.api.HttpBody
	(*v2.NodeSearchResponse)(nil),                  // 60: datacommons.v2.NodeSearchResponse
	(*v2.ResolveResponse)(nil),                     // 61: datacommons.v2.ResolveResponse
	(*v2.EventResponse)(nil),                       // 62: datacommons.v2.EventResponse
	(*proto.QueryResponse)(nil),                    // 63: datacommons.QueryResponse
	(*v1.BulkVariableInfoResponse)(nil),            // 64: datacommons.v1.BulkVariableInfoResponse
	(*v1.BulkVariableGroupInfoResponse)(nil),       // 65: datacommons.v1.BulkVariableGroupInfoResponse
	(*proto.RecognizePlacesResponse)(nil),          // 66: datacommons.RecognizePlacesResponse
	(*proto.FilterStatVarsByEntityResponse)(nil),   // 67: datacommons.FilterStatVarsByEntityResponse
	(*v2.SearchIndicatorsResponse)(nil),            // 68: datacommons.v2.SearchIndicatorsResponse
	(*v2.GetObservationsResponse)(nil),             // 69: datacommons.v2.GetObservationsResponse
	(*v2.GetVariableMetadataResponse)(nil),         // 70: datacommons.v2.GetVariableMetadataResponse
	(*proto.GetLocationsRankingsResponse)(nil),     // 71: datacommons.GetLocationsRankingsResponse
	(*proto.PayloadResponse)(nil),                  // 72: datacommons.PayloadResponse
	(*proto.GetPlacesInResponse)(nil),              // 73: datacommons.GetPlacesInResponse
	(*proto.GetStatsResponse)(nil),                 // 74: datacommons.GetStatsResponse
	(*proto.GetStatValueResponse)(nil),             // 75: datacommons.GetStatValueResponse
	(*proto.GetStatSeriesResponse)(nil),            // 76: datacommons.GetStatSeriesResponse
	(*proto.GetStatAllResponse)(nil),               // 77: datacommons.GetStatAllResponse
	(*proto.GetRelatedLocationsResponse)(nil),      // 78: datacommons.GetRelatedLocationsResponse
	(*proto.GetVersionResponse)(nil),               // 79: datacommons.GetVersionResponse
	(*proto.GetPlaceStatVarsResponse)(nil),         // 80: datacommons.GetPlaceStatVarsResponse
	(*proto.GetEntityStatVarsUnionResponse)(nil),   // 81: datacommons.GetEntityStatVarsUnionResponse
	(*v1.PropertiesResponse)(nil),                  // 82: datacommons.v1.PropertiesResponse
	(*v1.BulkPropertiesResponse)(nil),              // 83: datacommons.v1.BulkPropertiesResponse
	(*v1.PropertyValuesResponse)(nil),              // 84: datacommons.v1.PropertyValuesResponse
	(*v1.BulkPropertyValuesResponse)(nil),          // 85: datacommons.v1.BulkPropertyValuesResponse
	(*v1.TriplesResponse)(nil),                     // 86: datacommons.v1.TriplesResponse
	(*v1.BulkTriplesResponse)(nil),                 // 87: datacommons.v1.BulkTriplesResponse
	(*v1.VariablesResponse)(nil),                   // 88: datacommons.v1.VariablesResponse
	(*v1.PlaceInfoResponse)(nil),                   // 89: datacommons.v1.PlaceInfoResponse
	(*v1.BulkPlaceInfoResponse)(nil),               // 90: datacommons.v1.BulkPlaceInfoResponse
	(*v1.VariableInfoResponse)(nil),                // 91: datacommons.v1.VariableInfoResponse
	(*v1.VariableGroupInfoResponse)(nil),           // 92: datacommons.v1.VariableGroupInfoResponse
	(*proto.PointStat)(nil),                        // 93: datacommons.PointStat
	(*v1.BulkObservationsPointResponse)(nil),       // 94: datacommons.v1.BulkObservationsPointResponse
	(*v1.ObservationsSeriesResponse)(nil),          // 95: datacommons.v1.ObservationsSeriesResponse
	(*v1.BulkObservationsSeriesResponse)(nil),      // 96: datacommons.v1.BulkObservationsSeriesResponse
	(*v1.BulkObservationDatesLinkedResponse)(nil),  // 97: datacommons.v1.BulkObservationDatesLinkedResponse
	(*v1.PlacePageResponse)(nil),                   // 98: datacommons.v1.PlacePageResponse
	(*v1.VariableAncestorsResponse)(nil),           // 99: datacommons.v1.VariableAncestorsResponse
	(*proto.SearchStatVarResponse)(nil),            // 100: datacommons.SearchStatVarResponse
	(*proto.ResolveEntitiesResponse)(nil),          // 101: datacommons.ResolveEntitiesResponse
	(*proto.ResolveCoordinatesResponse)(nil),       // 102: datacommons.ResolveCoordinatesResponse
	(*proto.ResolveIdsResponse)(nil),               // 103: datacommons.ResolveIdsResponse
	(*proto.FindEntitiesResponse)(nil),             // 104: datacommons.FindEntitiesResponse
	(*proto.BulkFindEntitiesResponse)(nil),         // 105: datacommons.BulkFindEntitiesResponse
	(*proto.RecognizeEntitiesResponse)(nil),        // 106: datacommons.RecognizeEntitiesResponse
	(*proto.GetImportTableDataResponse)(nil),       // 107: datacommons.GetImportTableDataResponse
}
var file_service_mixer_proto_depIdxs = []int32{
	0,   // 0: datacommons.Mixer.V3Node:input_type -> datacommons.v2.NodeRequest
	1,   // 1: datacommons.Mixer.V3Observation:input_type -> datacommons.v2.ObservationRequest
	2,   // 2: datacommons.Mixer.V3SdmxData:input_type -> datacommons.v3.SdmxRestRequest
	2,   // 3: datacommons.Mixer.V3SdmxAvailability:input_type -> datacommons.v3.SdmxRestRequest
	3,   // 4: datacommons.Mixer.V3NodeSearch:input_type -> datacommons.v2.NodeSearchRequest
	4,   // 5: datacommons.Mixer.V3Resolve:input_type -> datacommons.v2.ResolveRequest
	5,   // 6: datacommons.Mixer.V3Event:input_type -> datacommons.v2.EventRequest
	6,   // 7: datacommons.Mixer.V3Sparql:input_type -> datacommons.SparqlRequest
	7,   // 8: datacommons.Mixer.V3BulkVariableInfo:input_type -> datacommons.v1.BulkVariableInfoRequest
	8,   // 9: datacommons.Mixer.V3BulkVariableGroupInfo:input_type -> datacommons.v1.BulkVariableGroupInfoRequest
	6,   // 10: datacommons.Mixer.V2Sparql:input_type -> datacommons.SparqlRequest
	4,   // 11: datacommons.Mixer.V2Resolve:input_type -> datacommons.v2.ResolveRequest
	0,   // 12: datacommons.Mixer.V2Node:input_type -> datacommons.v2.NodeRequest
	5,   // 13: datacommons.Mixer.V2Event:input_type -> datacommons.v2.EventRequest
	1,   // 14: datacommons.Mixer.V2Observation:input_type -> datacommons.v2.ObservationRequest
	9,   // 15: datacommons.Mixer.V2RecognizePlaces:input_type -> datacommons.RecognizePlacesRequest
	10,  // 16: datacommons.Mixer.FilterStatVarsByEntity:input_type -> datacommons.FilterStatVarsByEntityRequest
	7,   // 17: datacommons.Mixer.V2BulkVariableInfo:input_type -> datacommons.v1.BulkVariableInfoRequest
	8,   // 18: datacommons.Mixer.V2BulkVariableGroupInfo:input_type -> datacommons.v1.BulkVariableGroupInfoRequest
	11,  // 19: datacommons.Mixer.V2AgentSearchIndicators:input_type -> datacommons.v2.SearchIndicatorsRequest
	12,  // 20: datacommons.Mixer.V2AgentGetObservations:input_type -> datacommons.v2.GetObservationsRequest
	13,  // 21: datacommons.Mixer.V2AgentGetVariableMetadata:input_type -> datacommons.v2.GetVariableMetadataRequest
	14,  // 22: datacommons.Mixer.V2GetLocationsRankings:input_type -> datacommons.GetLocationsRankingsRequest
	15,  // 23: datacommons.Mixer.Query:input_type -> datacommons.QueryRequest
	16,  // 24: datacommons.Mixer.GetPropertyLabels:input_type -> datacommons.GetPropertyLabelsRequest
	17,  // 25: datacommons.Mixer.GetPropertyValues:input_type -> datacommons.GetPropertyValuesRequest
	18,  // 26: datacommons.Mixer.GetTriples:input_type -> datacommons.GetTriplesRequest
	19,  // 27: datacommons.Mixer.GetPlacesIn:input_type -> datacommons.GetPlacesInRequest
	20,  // 28: datacommons.Mixer.GetStats:input_type -> datacommons.GetStatsRequest
	21,  // 29: datacommons.Mixer.GetStatValue:input_type -> datacommons.GetStatValueRequest
	22,  // 30: datacommons.Mixer.GetStatSeries:input_type -> datacommons.GetStatSeriesRequest
	23,  // 31: datacommons.Mixer.GetStatAll:input_type -> datacommons.GetStatAllRequest
	14,  // 32: datacommons.Mixer.GetLocationsRankings:input_type -> datacommons.GetLocationsRankingsRequest
	24,  // 33: datacommons.Mixer.GetRelatedLocations:input_type -> datacommons.GetRelatedLocationsRequest
	25,  // 34: datacommons.Mixer.GetVersion:input_type -> datacommons.GetVersionRequest
	26,  // 35: datacommons.Mixer.GetPlaceStatVars:input_type -> datacommons.GetPlaceStatVarsRequest
	27,  // 36: datacommons.Mixer.GetEntityStatVarsUnionV1:input_type -> datacommons.GetEntityStatVarsUnionRequest
	15,  // 37: datacommons.Mixer.QueryV1:input_type -> datacommons.QueryRequest
	28,  // 38: datacommons.Mixer.Properties:input_type -> datacommons.v1.PropertiesRequest
	29,  // 39: datacommons.Mixer.BulkProperties:input_type -> datacommons.v1.BulkPropertiesRequest
	30,  // 40: datacommons.Mixer.PropertyValues:input_type -> datacommons.v1.PropertyValuesRequest
	31,  // 41: datacommons.Mixer.LinkedPropertyValues:input_type -> datacommons.v1.LinkedPropertyValuesRequest
	32,  // 42: datacommons.Mixer.BulkPropertyValues:input_type -> datacommons.v1.BulkPropertyValuesRequest
	33,  // 43: datacommons.Mixer.BulkLinkedPropertyValues:input_type -> datacommons.v1.BulkLinkedPropertyValuesRequest
	34,  // 44: datacommons.Mixer.Triples:input_type -> datacommons.v1.TriplesRequest
	35,  // 45: datacommons.Mixer.BulkTriples:input_type -> datacommons.v1.BulkTriplesRequest
	36,  // 46: datacommons.Mixer.Variables:input_type -> datacommons.v1.VariablesRequest
	37,  // 47: datacommons.Mixer.PlaceInfo:input_type -> datacommons.v1.PlaceInfoRequest
	38,  // 48: datacommons.Mixer.BulkPlaceInfo:input_type -> datacommons.v1.BulkPlaceInfoRequest
	39,  // 49: datacommons.Mixer.VariableInfo:input_type -> datacommons.v1.VariableInfoRequest
	7,   // 50: datacommons.Mixer.BulkVariableInfo:input_type -> datacommons.v1.BulkVariableInfoRequest
	40,  // 51: datacommons.Mixer.VariableGroupInfo:input_type -> datacommons.v1.VariableGroupInfoRequest
	8,   // 52: datacommons.Mixer.BulkVariableGroupInfo:input_type -> datacommons.v1.BulkVariableGroupInfoRequest
	41,  // 53: datacommons.Mixer.ObservationsPoint:input_type -> datacommons.v1.ObservationsPointRequest
	42,  // 54: datacommons.Mixer.BulkObservationsPoint:input_type -> datacommons.v1.BulkObservationsPointRequest
	43,  // 55: datacommons.Mixer.ObservationsSeries:input_type -> datacommons.v1.ObservationsSeriesRequest
	44,  // 56: datacommons.Mixer.BulkObservationsSeries:input_type -> datacommons.v1.BulkObservationsSeriesRequest
	45,  // 57: datacommons.Mixer.BulkObservationsSeriesLinked:input_type -> datacommons.v1.BulkObservationsSeriesLinkedRequest
	46,  // 58: datacommons.Mixer.BulkObservationDatesLinked:input_type -> datacommons.v1.BulkObservationDatesLinkedRequest
	47,  // 59: datacommons.Mixer.PlacePage:input_type -> datacommons.v1.PlacePageRequest
	48,  // 60: datacommons.Mixer.VariableAncestors:input_type -> datacommons.v1.VariableAncestorsRequest
	49,  // 61: datacommons.Mixer.SearchStatVar:input_type -> datacommons.SearchStatVarRequest
	50,  // 62: datacommons.Mixer.ResolveEntities:input_type -> datacommons.ResolveEntitiesRequest
	51,  // 63: datacommons.Mixer.ResolveCoordinates:input_type -> datacommons.ResolveCoordinatesRequest
	52,  // 64: datacommons.Mixer.ResolveIds:input_type -> datacommons.ResolveIdsRequest
	53,  // 65: datacommons.Mixer.FindEntities:input_type -> datacommons.FindEntitiesRequest
	54,  // 66: datacommons.Mixer.BulkFindEntities:input_type -> datacommons.BulkFindEntitiesRequest
	9,   // 67: datacommons.Mixer.RecognizePlaces:input_type -> datacommons.RecognizePlacesRequest
	55,  // 68: datacommons.Mixer.RecognizeEntities:input_type -> datacommons.RecognizeEntitiesRequest
	56,  // 69: datacommons.Mixer.GetImportTableData:input_type -> datacommons.GetImportTableDataRequest
	57,  // 70: datacommons.Mixer.V3Node:output_type -> datacommons.v2.NodeResponse
	58,  // 71: datacommons.Mixer.V3Observation:output_type -> datacommons.v2.ObservationResponse
	59,  // 72: datacommons.Mixer.V3SdmxData:output_type -> google.api.HttpBody
	59,  // 73: datacommons.Mixer.V3SdmxAvailability:output_type -> google.api.HttpBody
	60,  // 74: datacommons.Mixer.V3NodeSearch:output_type -> datacommons.v2.NodeSearchResponse
	61,  // 75: datacommons.Mixer.V3Resolve:output_type -> datacommons.v2.ResolveResponse
	62,  // 76: datacommons.Mixer.V3Event:output_type -> datacommons.v2.EventResponse
	63,  // 77: datacommons.Mixer.V3Sparql:output_type -> datacommons.QueryResponse
	64,  // 78: datacommons.Mixer.V3BulkVariableInfo:output_type -> datacommons.v1.BulkVariableInfoResponse
	65,  // 79: datacommons.Mixer.V3BulkVariableGroupInfo:output_type -> datacommons.v1.BulkVariableGroupInfoResponse
	63,  // 80: datacommons.Mixer.V2Sparql:output_type -> datacommons.QueryResponse
	61,  // 81: datacommons.Mixer.V2Resolve:output_type -> datacommons.v2.ResolveResponse
	57,  // 82: datacommons.Mixer.V2Node:output_type -> datacommons.v2.NodeResponse
	62,  // 83: datacommons.Mixer.V2Event:output_type -> datacommons.v2.EventResponse
	58,  // 84: datacommons.Mixer.V2Observation:output_type -> datacommons.v2.ObservationResponse
	66,  // 85: datacommons.Mixer.V2RecognizePlaces:output_type -> datacommons.RecognizePlacesResponse
	67,  // 86: datacommons.Mixer.FilterStatVarsByEntity:output_type -> datacommons.FilterStatVarsByEntityResponse
	64,  // 87: datacommons.Mixer.V2BulkVariableInfo:output_type -> datacommons.v1.BulkVariableInfoResponse
	65,  // 88: datacommons.Mixer.V2BulkVariableGroupInfo:output_type -> datacommons.v1.BulkVariableGroupInfoResponse
	68,  // 89: datacommons.Mixer.V2AgentSearchIndicators:output_type -> datacommons.v2.SearchIndicatorsResponse
	69,  // 90: datacommons.Mixer.V2AgentGetObservations:output_type -> datacommons.v2.GetObservationsResponse
	70,  // 91: datacommons.Mixer.V2AgentGetVariableMetadata:output_type -> datacommons.v2.GetVariableMetadataResponse
	71,  // 92: datacommons.Mixer.V2GetLocationsRankings:output_type -> datacommons.GetLocationsRankingsResponse
	63,  // 93: datacommons.Mixer.Query:output_type -> datacommons.QueryResponse
	72,  // 94: datacommons.Mixer.GetPropertyLabels:output_type -> datacommons.PayloadResponse
	72,  // 95: datacommons.Mixer.GetPropertyValues:output_type -> datacommons.PayloadResponse
	72,  // 96: datacommons.Mixer.GetTriples:output_type -> datacommons.PayloadResponse
	73,  // 97: datacommons.Mixer.GetPlacesIn:output_type -> datacommons.GetPlacesInResponse
	74,  // 98: datacommons.Mixer.GetStats:output_type -> datacommons.GetStatsResponse
	75,  // 99: datacommons.Mixer.GetStatValue:output_type -> datacommons.GetStatValueResponse
	76,  // 100: datacommons.Mixer.GetStatSeries:output_type -> datacommons.GetStatSeriesResponse
	77,  // 101: datacommons.Mixer.GetStatAll:output_type -> datacommons.GetStatAllResponse
	71,  // 102: datacommons.Mixer.GetLocationsRankings:output_type -> datacommons.GetLocationsRankingsResponse
	78,  // 103: datacommons.Mixer.GetRelatedLocations:output_type -> datacommons.GetRelatedLocationsResponse
	79,  // 104: datacommons.Mixer.GetVersion:output_type -> datacommons.GetVersionResponse
	80,  // 105: datacommons.Mixer.GetPlaceStatVars:output_type -> datacommons.GetPlaceStatVarsResponse
	81,  // 106: datacommons.Mixer.GetEntityStatVarsUnionV1:output_type -> datacommons.GetEntityStatVarsUnionResponse
	63,  // 107: datacommons.Mixer.QueryV1:output_type -> datacommons.QueryResponse
	82,  // 108: datacommons.Mixer.Properties:output_type -> datacommons.v1.PropertiesResponse
	83,  // 109: datacommons.Mixer.BulkProperties:output_type -> datacommons.v1.BulkPropertiesResponse
	84,  // 110: datacommons.Mixer.PropertyValues:output_type -> datacommons.v1.PropertyValuesResponse
	84,  // 111: datacommons.Mixer.LinkedPropertyValues:output_type -> datacommons.v1.PropertyValuesResponse
	85,  // 112: datacommons.Mixer.BulkPropertyValues:output_type -> datacommons.v1.BulkPropertyValuesResponse
	85,  // 113: datacommons.Mixer.BulkLinkedPropertyValues:output_type -> datacommons.v1.BulkPropertyValuesResponse
	86,  // 114: datacommons.Mixer.Triples:output_type -> datacommons.v1.TriplesResponse
	87,  // 115: datacommons.Mixer.BulkTriples:output_type -> datacommons.v1.BulkTriplesResponse
	88,  // 116: datacommons.Mixer.Variables:output_type -> datacommons.v1.VariablesResponse
	89,  // 117: datacommons.Mixer.PlaceInfo:output_type -> datacommons.v1.PlaceInfoResponse
	90,  // 118: datacommons.Mixer.BulkPlaceInfo:output_type -> datacommons.v1.BulkPlaceInfoResponse
	91,  // 119: datacommons.Mixer.VariableInfo:output_type -> datacommons.v1.VariableInfoResponse
	64,  // 120: datacommons.Mixer.BulkVariableInfo:output_type -> datacommons.v1.BulkVariableInfoResponse
	92,  // 121: datacommons.Mixer.VariableGroupInfo:output_type -> datacommons.v1.VariableGroupInfoResponse
	65,  // 122: datacommons.Mixer.BulkVariableGroupInfo:output_type -> datacommons.v1.BulkVariableGroupInfoResponse
	93,  // 123: datacommons.Mixer.ObservationsPoint:output_type -> datacommons.PointStat
	94,  // 124: datacommons.Mixer.BulkObservationsPoint:output_type -> datacommons.v1.BulkObservationsPointResponse
	95,  // 125: datacommons.Mixer.ObservationsSeries:output_type -> datacommons.v1.ObservationsSeriesResponse
	96,  // 126: datacommons.Mixer.BulkObservationsSeries:output_type -> datacommons.v1.BulkObservationsSeriesResponse
	96,  // 127: datacommons.Mixer.BulkObservationsSeriesLinked:output_type -> datacommons.v1.BulkObservationsSeriesResponse
	97,  // 128: datacommons.Mixer.BulkObservationDatesLinked:output_type -> datacommons.v1.BulkObservationDatesLinkedResponse
	98,  // 129: datacommons.Mixer.PlacePage:output_type -> datacommons.v1.PlacePageResponse
	99,  // 130: datacommons.Mixer.VariableAncestors:output_type -> datacommons.v1.VariableAncestorsResponse
	100, // 131: datacommons.Mixer.SearchStatVar:output_type -> datacommons.SearchStatVarResponse
	101, // 132: datacommons.Mixer.ResolveEntities:output_type -> datacommons.ResolveEntitiesResponse
	102, // 133: datacommons.Mixer.ResolveCoordinates:output_type -> datacommons.ResolveCoordinatesResponse
	103, // 134: datacommons.Mixer.ResolveIds:output_type -> datacommons.ResolveIdsResponse
	104, // 135: datacommons.Mixer.FindEntities:output_type -> datacommons.FindEntitiesResponse
	105, // 136: datacommons.Mixer.BulkFindEntities:output_type -> datacommons.BulkFindEntitiesResponse
	66,  // 137: datacommons.Mixer.RecognizePlaces:output_type -> datacommons.RecognizePlacesResponse
	106, // 138: datacommons.Mixer.RecognizeEntities:output_type -> datacommons.RecognizeEntitiesResponse
	107, // 139: datacommons.Mixer.GetImportTableData:output_type -> datacommons.GetImportTableDataResponse
	70,  // [70:140] is the sub-list for method output_type
	0,   // [0:70] is the sub-list for method input_type
	0,   // [0:0] is the sub-list for extension type_name
	0,   // [0:0] is the sub-list for extension extendee
	0,   // [0:0] is the sub-list for field type_name
}

func init() { file_service_mixer_proto_init() }
func file_service_mixer_proto_init() {
	if File_service_mixer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_mixer_proto_rawDesc), len(file_service_mixer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_mixer_proto_goTypes,
		DependencyIndexes: file_service_mixer_proto_depIdxs,
	}.Build()
	File_service_mixer_proto = out.File
	file_service_mixer_proto_goTypes = nil
	file_service_mixer_proto_depIdxs = nil
}
