// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: v3/data.proto

package v3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request envelope for SDMX REST APIs.
type SdmxRestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Tail after the SDMX API family route, for example:
	// dataflow/DATACOMMONS/DF_OBSERVATIONS/1.0.0/*
	Tail string `protobuf:"bytes,1,opt,name=tail,proto3" json:"tail,omitempty"`
}

func (x *SdmxRestRequest) Reset() {
	*x = SdmxRestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v3_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SdmxRestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SdmxRestRequest) ProtoMessage() {}

func (x *SdmxRestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v3_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SdmxRestRequest.ProtoReflect.Descriptor instead.
func (*SdmxRestRequest) Descriptor() ([]byte, []int) {
	return file_v3_data_proto_rawDescGZIP(), []int{0}
}

func (x *SdmxRestRequest) GetTail() string {
	if x != nil {
		return x.Tail
	}
	return ""
}

var File_v3_data_proto protoreflect.FileDescriptor

var file_v3_data_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x76, 0x33, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0e, 0x64, 0x61, 0x74, 0x61, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2e, 0x76, 0x33, 0x22,
	0x25, 0x0a, 0x0f, 0x53, 0x64, 0x6d, 0x78, 0x52, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x61, 0x69, 0x6c, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73,
	0x6f, 0x72, 0x67, 0x2f, 0x6d, 0x69, 0x78, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x33, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_v3_data_proto_rawDescOnce sync.Once
	file_v3_data_proto_rawDescData = file_v3_data_proto_rawDesc
)

func file_v3_data_proto_rawDescGZIP() []byte {
	file_v3_data_proto_rawDescOnce.Do(func() {
		file_v3_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_v3_data_proto_rawDescData)
	})
	return file_v3_data_proto_rawDescData
}

var file_v3_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v3_data_proto_goTypes = []interface{}{
	(*SdmxRestRequest)(nil), // 0: datacommons.v3.SdmxRestRequest
}
var file_v3_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v3_data_proto_init() }
func file_v3_data_proto_init() {
	if File_v3_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v3_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SdmxRestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v3_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v3_data_proto_goTypes,
		DependencyIndexes: file_v3_data_proto_depIdxs,
		MessageInfos:      file_v3_data_proto_msgTypes,
	}.Build()
	File_v3_data_proto = out.File
	file_v3_data_proto_rawDesc = nil
	file_v3_data_proto_goTypes = nil
	file_v3_data_proto_depIdxs = nil
}
