# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# K8s services create hosts for deployments. Meaning that
# other containers in the cluster can refer to a set of deployments
# using the host: <full-name>-<service-name>:<port> (ex: mixer-dev-svg:80)

{{- $index := 0 }}
{{- range $serviceName, $group := .Values.serviceGroups }}
{{- if gt $index 0}}
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mixer.fullname" $ }}-{{ $serviceName }}
  namespace: {{ $.Values.namespace.name }}
  labels:
    service: {{ include "mixer.fullname" $ }}-{{ $serviceName }}
    {{- include "mixer.labels" $ | nindent 4 }}
  annotations:
    # This is to get longer timeout for the Cloud Load Balancer.
    cloud.google.com/backend-config: '{"ports": {"80":"{{ include "mixer.fullname" $ }}-backendconfig"}}'
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    service: {{ include "mixer.fullname" $ }}-{{ $serviceName }}
    {{- include "mixer.selectorLabels" $ | nindent 4 }}
{{- $index = add $index 1 }}
{{- end }}

---

apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "mixer.fullname" . }}-backendconfig
  namespace: {{ .Values.namespace.name }}
spec:
  # Timeout for load balancer and the GKE pod connection
  timeoutSec: 300
  connectionDraining:
    drainingTimeoutSec: 300
