// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: v2/event.proto

package v2

import (
	v1 "github.com/datacommonsorg/mixer/internal/proto/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Two modes are supported:
//
// EventCollection:
//
//	node = 'country/USA'
//	property = '<-location{typeOf:FireEvent, date:2020-10, area:3.1#6.2#Acre}'
//
// NOTE:
//   - burnedArea:3.14#6.28#Acre means filterProp:lowerLimit#upperLimit#unit
//   - The format of 'date' is YYYY-MM.
//
// EventCollectionDate:
//
//	node = 'country/USA'
//	property = ‘<-location{typeOf:FireEvent}->date’,
type EventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Property      string                 `protobuf:"bytes,2,opt,name=property,proto3" json:"property,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRequest) Reset() {
	*x = EventRequest{}
	mi := &file_v2_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRequest) ProtoMessage() {}

func (x *EventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRequest.ProtoReflect.Descriptor instead.
func (*EventRequest) Descriptor() ([]byte, []int) {
	return file_v2_event_proto_rawDescGZIP(), []int{0}
}

func (x *EventRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *EventRequest) GetProperty() string {
	if x != nil {
		return x.Property
	}
	return ""
}

type EventResponse struct {
	state               protoimpl.MessageState  `protogen:"open.v1"`
	EventCollection     *v1.EventCollection     `protobuf:"bytes,1,opt,name=event_collection,json=eventCollection,proto3" json:"event_collection,omitempty"`
	EventCollectionDate *v1.EventCollectionDate `protobuf:"bytes,2,opt,name=event_collection_date,json=eventCollectionDate,proto3" json:"event_collection_date,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_v2_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v2_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_v2_event_proto_rawDescGZIP(), []int{1}
}

func (x *EventResponse) GetEventCollection() *v1.EventCollection {
	if x != nil {
		return x.EventCollection
	}
	return nil
}

func (x *EventResponse) GetEventCollectionDate() *v1.EventCollectionDate {
	if x != nil {
		return x.EventCollectionDate
	}
	return nil
}

var File_v2_event_proto protoreflect.FileDescriptor

const file_v2_event_proto_rawDesc = "" +
	"\n" +
	"\x0ev2/event.proto\x12\x0edatacommons.v2\x1a\x0ev1/event.proto\">\n" +
	"\fEventRequest\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x1a\n" +
	"\bproperty\x18\x02 \x01(\tR\bproperty\"\xb4\x01\n" +
	"\rEventResponse\x12J\n" +
	"\x10event_collection\x18\x01 \x01(\v2\x1f.datacommons.v1.EventCollectionR\x0feventCollection\x12W\n" +
	"\x15event_collection_date\x18\x02 \x01(\v2#.datacommons.v1.EventCollectionDateR\x13eventCollectionDateB3Z1github.com/datacommonsorg/mixer/internal/proto/v2b\x06proto3"

var (
	file_v2_event_proto_rawDescOnce sync.Once
	file_v2_event_proto_rawDescData []byte
)

func file_v2_event_proto_rawDescGZIP() []byte {
	file_v2_event_proto_rawDescOnce.Do(func() {
		file_v2_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v2_event_proto_rawDesc), len(file_v2_event_proto_rawDesc)))
	})
	return file_v2_event_proto_rawDescData
}

var file_v2_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v2_event_proto_goTypes = []any{
	(*EventRequest)(nil),           // 0: datacommons.v2.EventRequest
	(*EventResponse)(nil),          // 1: datacommons.v2.EventResponse
	(*v1.EventCollection)(nil),     // 2: datacommons.v1.EventCollection
	(*v1.EventCollectionDate)(nil), // 3: datacommons.v1.EventCollectionDate
}
var file_v2_event_proto_depIdxs = []int32{
	2, // 0: datacommons.v2.EventResponse.event_collection:type_name -> datacommons.v1.EventCollection
	3, // 1: datacommons.v2.EventResponse.event_collection_date:type_name -> datacommons.v1.EventCollectionDate
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v2_event_proto_init() }
func file_v2_event_proto_init() {
	if File_v2_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2_event_proto_rawDesc), len(file_v2_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v2_event_proto_goTypes,
		DependencyIndexes: file_v2_event_proto_depIdxs,
		MessageInfos:      file_v2_event_proto_msgTypes,
	}.Build()
	File_v2_event_proto = out.File
	file_v2_event_proto_goTypes = nil
	file_v2_event_proto_depIdxs = nil
}
