// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: v2/resolve.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Three modes are supported:
//
//  1. ID to ID:
//     nodes = ["wikidataId/CA", "wikidataId/MA"]
//     property = "<-wikidataId->nutsCode"
//
//  2. Coordinate (latitude#longitude) to DCID:
//     nodes = ["34.56#-23.12", "-22.11#44.55"]
//     property = "<-geoCoordinate->dcid"
//
//  3. Description (name) to DCID:
//     nodes = ["Mountain View", "New York"]
//     property = "<-description->dcid" or "<-description{typeOf:City}->dcid"
type ResolveRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Nodes    []string               `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Property string                 `protobuf:"bytes,2,opt,name=property,proto3" json:"property,omitempty"`
	// Optional name of a specific custom resolver to use.
	// If not provided, defaults to place resolution using the property param.
	// Supported Values:
	// - "indicator": Resolves Statistical Variables and Topics via semantic search.
	// - "topic": Resolves explicit topic tree hierarchies and root topics.
	Resolver string `protobuf:"bytes,3,opt,name=resolver,proto3" json:"resolver,omitempty"`
	// Optional target for the resolution request.
	// This parameter controls which Data Commons instances are used for resolution.
	// Supported Values:
	// - "base_only": Uses only the base Data Commons instance (remote).
	// - "custom_only": Uses only the custom Data Commons instance (local).
	// - "base_and_custom": Uses both base and custom instances.
	Target string `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	// If true, recursively unpacks all descendant Statistical Variables within matching topics.
	// If false, returns immediate children (Statistical Variables and Sub-Topics).
	// Supported on resolver="topic" and resolver="indicator".
	ExpandTopics  bool `protobuf:"varint,5,opt,name=expand_topics,json=expandTopics,proto3" json:"expand_topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_v2_resolve_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v2_resolve_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_v2_resolve_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveRequest) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ResolveRequest) GetProperty() string {
	if x != nil {
		return x.Property
	}
	return ""
}

func (x *ResolveRequest) GetResolver() string {
	if x != nil {
		return x.Resolver
	}
	return ""
}

func (x *ResolveRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ResolveRequest) GetExpandTopics() bool {
	if x != nil {
		return x.ExpandTopics
	}
	return false
}

type ResolveResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Entities      []*ResolveResponse_Entity `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_v2_resolve_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v2_resolve_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_v2_resolve_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveResponse) GetEntities() []*ResolveResponse_Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type ResolveResponse_Entity struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Node          string                              `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Candidates    []*ResolveResponse_Entity_Candidate `protobuf:"bytes,3,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse_Entity) Reset() {
	*x = ResolveResponse_Entity{}
	mi := &file_v2_resolve_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse_Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse_Entity) ProtoMessage() {}

func (x *ResolveResponse_Entity) ProtoReflect() protoreflect.Message {
	mi := &file_v2_resolve_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse_Entity.ProtoReflect.Descriptor instead.
func (*ResolveResponse_Entity) Descriptor() ([]byte, []int) {
	return file_v2_resolve_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ResolveResponse_Entity) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *ResolveResponse_Entity) GetCandidates() []*ResolveResponse_Entity_Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type ResolveResponse_Entity_Candidate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The DCID of the resolved entity.
	Dcid string `protobuf:"bytes,1,opt,name=dcid,proto3" json:"dcid,omitempty"`
	// The dominant type of the entity (e.g. "Place", "StatisticalVariable").
	DominantType string `protobuf:"bytes,2,opt,name=dominant_type,json=dominantType,proto3" json:"dominant_type,omitempty"`
	// Auxiliary information describing the match quality or context.
	// Flexible key-value pairs depending on the resolver used.
	//
	// For resolver="indicator":
	// - "score": The cosine similarity score of the match (e.g. "0.98").
	// - "sentence": The specific description sentence that matched the query.
	Metadata map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// All types associated with this entity.
	TypeOf []string `protobuf:"bytes,4,rep,name=type_of,json=typeOf,proto3" json:"type_of,omitempty"`
	// Canonical display name of the entity.
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	// Observation properties to be used by clients when making subsequent observation API calls.
	ObservationProperties []string `protobuf:"bytes,6,rep,name=observation_properties,json=observationProperties,proto3" json:"observation_properties,omitempty"`
	// Expanded child members (Statistical Variables and Sub-Topics).
	Children      []*ResolveResponse_Entity_Candidate `protobuf:"bytes,7,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse_Entity_Candidate) Reset() {
	*x = ResolveResponse_Entity_Candidate{}
	mi := &file_v2_resolve_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse_Entity_Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse_Entity_Candidate) ProtoMessage() {}

func (x *ResolveResponse_Entity_Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_v2_resolve_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse_Entity_Candidate.ProtoReflect.Descriptor instead.
func (*ResolveResponse_Entity_Candidate) Descriptor() ([]byte, []int) {
	return file_v2_resolve_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *ResolveResponse_Entity_Candidate) GetDcid() string {
	if x != nil {
		return x.Dcid
	}
	return ""
}

func (x *ResolveResponse_Entity_Candidate) GetDominantType() string {
	if x != nil {
		return x.DominantType
	}
	return ""
}

func (x *ResolveResponse_Entity_Candidate) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ResolveResponse_Entity_Candidate) GetTypeOf() []string {
	if x != nil {
		return x.TypeOf
	}
	return nil
}

func (x *ResolveResponse_Entity_Candidate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResolveResponse_Entity_Candidate) GetObservationProperties() []string {
	if x != nil {
		return x.ObservationProperties
	}
	return nil
}

func (x *ResolveResponse_Entity_Candidate) GetChildren() []*ResolveResponse_Entity_Candidate {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_v2_resolve_proto protoreflect.FileDescriptor

const file_v2_resolve_proto_rawDesc = "" +
	"\n" +
	"\x10v2/resolve.proto\x12\x0edatacommons.v2\"\x9b\x01\n" +
	"\x0eResolveRequest\x12\x14\n" +
	"\x05nodes\x18\x01 \x03(\tR\x05nodes\x12\x1a\n" +
	"\bproperty\x18\x02 \x01(\tR\bproperty\x12\x1a\n" +
	"\bresolver\x18\x03 \x01(\tR\bresolver\x12\x16\n" +
	"\x06target\x18\x04 \x01(\tR\x06target\x12#\n" +
	"\rexpand_topics\x18\x05 \x01(\bR\fexpandTopics\"\xde\x04\n" +
	"\x0fResolveResponse\x12B\n" +
	"\bentities\x18\x01 \x03(\v2&.datacommons.v2.ResolveResponse.EntityR\bentities\x1a\x86\x04\n" +
	"\x06Entity\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12P\n" +
	"\n" +
	"candidates\x18\x03 \x03(\v20.datacommons.v2.ResolveResponse.Entity.CandidateR\n" +
	"candidates\x1a\x8f\x03\n" +
	"\tCandidate\x12\x12\n" +
	"\x04dcid\x18\x01 \x01(\tR\x04dcid\x12#\n" +
	"\rdominant_type\x18\x02 \x01(\tR\fdominantType\x12Z\n" +
	"\bmetadata\x18\x03 \x03(\v2>.datacommons.v2.ResolveResponse.Entity.Candidate.MetadataEntryR\bmetadata\x12\x17\n" +
	"\atype_of\x18\x04 \x03(\tR\x06typeOf\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x125\n" +
	"\x16observation_properties\x18\x06 \x03(\tR\x15observationProperties\x12L\n" +
	"\bchildren\x18\a \x03(\v20.datacommons.v2.ResolveResponse.Entity.CandidateR\bchildren\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x02\x10\x03B3Z1github.com/datacommonsorg/mixer/internal/proto/v2b\x06proto3"

var (
	file_v2_resolve_proto_rawDescOnce sync.Once
	file_v2_resolve_proto_rawDescData []byte
)

func file_v2_resolve_proto_rawDescGZIP() []byte {
	file_v2_resolve_proto_rawDescOnce.Do(func() {
		file_v2_resolve_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v2_resolve_proto_rawDesc), len(file_v2_resolve_proto_rawDesc)))
	})
	return file_v2_resolve_proto_rawDescData
}

var file_v2_resolve_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v2_resolve_proto_goTypes = []any{
	(*ResolveRequest)(nil),                   // 0: datacommons.v2.ResolveRequest
	(*ResolveResponse)(nil),                  // 1: datacommons.v2.ResolveResponse
	(*ResolveResponse_Entity)(nil),           // 2: datacommons.v2.ResolveResponse.Entity
	(*ResolveResponse_Entity_Candidate)(nil), // 3: datacommons.v2.ResolveResponse.Entity.Candidate
	nil,                                      // 4: datacommons.v2.ResolveResponse.Entity.Candidate.MetadataEntry
}
var file_v2_resolve_proto_depIdxs = []int32{
	2, // 0: datacommons.v2.ResolveResponse.entities:type_name -> datacommons.v2.ResolveResponse.Entity
	3, // 1: datacommons.v2.ResolveResponse.Entity.candidates:type_name -> datacommons.v2.ResolveResponse.Entity.Candidate
	4, // 2: datacommons.v2.ResolveResponse.Entity.Candidate.metadata:type_name -> datacommons.v2.ResolveResponse.Entity.Candidate.MetadataEntry
	3, // 3: datacommons.v2.ResolveResponse.Entity.Candidate.children:type_name -> datacommons.v2.ResolveResponse.Entity.Candidate
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_v2_resolve_proto_init() }
func file_v2_resolve_proto_init() {
	if File_v2_resolve_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2_resolve_proto_rawDesc), len(file_v2_resolve_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v2_resolve_proto_goTypes,
		DependencyIndexes: file_v2_resolve_proto_depIdxs,
		MessageInfos:      file_v2_resolve_proto_msgTypes,
	}.Build()
	File_v2_resolve_proto = out.File
	file_v2_resolve_proto_goTypes = nil
	file_v2_resolve_proto_depIdxs = nil
}
