// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PlacesInRequest places in request
// swagger:model PlacesInRequest
type PlacesInRequest struct {

	// dcids
	// Required: true
	Dcids []string `json:"dcids"`

	// place type
	// Required: true
	PlaceType *string `json:"placeType"`
}

// Validate validates this places in request
func (m *PlacesInRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDcids(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePlaceType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PlacesInRequest) validateDcids(formats strfmt.Registry) error {

	if err := validate.Required("dcids", "body", m.Dcids); err != nil {
		return err
	}

	return nil
}

func (m *PlacesInRequest) validatePlaceType(formats strfmt.Registry) error {

	if err := validate.Required("placeType", "body", m.PlaceType); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PlacesInRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlacesInRequest) UnmarshalBinary(b []byte) error {
	var res PlacesInRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
