// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PropertyValuesResponse property values response
// swagger:model PropertyValuesResponse
type PropertyValuesResponse map[string]PropertyValuesResponseAnon

// Validate validates this property values response
func (m PropertyValuesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	for k := range m {

		if swag.IsZero(m[k]) { // not required
			continue
		}
		if val, ok := m[k]; ok {
			if err := val.Validate(formats); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// PropertyValuesResponseAnon property values response anon
// swagger:model PropertyValuesResponseAnon
type PropertyValuesResponseAnon struct {

	// in
	In []interface{} `json:"in"`

	// out
	Out []interface{} `json:"out"`
}

// Validate validates this property values response anon
func (m *PropertyValuesResponseAnon) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PropertyValuesResponseAnon) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PropertyValuesResponseAnon) UnmarshalBinary(b []byte) error {
	var res PropertyValuesResponseAnon
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
